#ifndef EFFECTSPANEL_H
#define EFFECTSPANEL_H

//(*Headers(EffectsPanel)
#include <wx/scrolwin.h>
#include <wx/notebook.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/checkbox.h>
#include <wx/filepicker.h>
#include <wx/slider.h>
#include <wx/panel.h>
#include <wx/choice.h>
#include <wx/bmpbuttn.h>
#include <wx/gbsizer.h>
#include <wx/button.h>
#include <wx/fontpicker.h>
#include <wx/choicebk.h>
//*)

#include <wx/filedlg.h>
#include <wx/fontdlg.h>
#include <unordered_map> //-DJ
#include <wx/colordlg.h>

wxDECLARE_EVENT(EVT_SELECTED_EFFECT_CHANGED, wxCommandEvent);


class EffectsPanel: public wxPanel
{
public:

    EffectsPanel(wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL, const wxString &name=wxPanelNameStr);
    virtual ~EffectsPanel();
    bool EffectChanged;
    void SetDefaultPalette();
    wxString* CurrentDir;
    wxString GetEffectString();
    void SetDefaultEffectValues(const wxString &name);
    wxString GetRandomEffectString(int effidx);
    void SetButtonColor(wxButton* btn, const wxColour* c);
    wxString GetEffectStringFromWindow(wxWindow *ParentWin);

    static const int PALETTE_SIZE = 6;

    //(*Declarations(EffectsPanel)
    wxStaticText* StaticText6;
    wxBitmapButton* BitmapButton_Galaxy_End_Width;
    wxBitmapButton* BitmapButton_StrobeDuration;
    wxBitmapButton* BitmapButton_RandomMotion;
    wxBitmapButton* BitmapButton_Wave_FillColors;
    wxBitmapButton* BitmapButton_TwinkleSteps;
    wxBitmapButton* BitmapButton_TextFont2;
    wxStaticText* StaticText19;
    wxStaticText* StaticText120;
    wxScrolledWindow* Panel1_Snowstorm;
    wxBitmapButton* BitmapButton_SnowflakesType;
    wxBitmapButton* BitmapButton_Piano_Clipping;
    wxBitmapButton* BitmapButton_Galaxy_CenterX;
    wxCheckBox* CheckBox_Morph_Start_Link;
    wxBitmapButton* BitmapButton_Fan_Num_Elements;
    wxChoice* Choice_Text_Dir1;
    wxBitmapButton* BitmapButton_GarlandsSpacing;
    wxSlider* Slider_Spirals_Direction;
    wxSlider* Slider_Pinwheel_ArmSize;
    wxSlider* Slider_Number_Strobes;
    wxBitmapButton* BitmapButton_TextCount4;
    wxSlider* Slider_Number_Chases;
    wxNotebook* Notebook1;
    wxBitmapButton* BitmapButton_SpiralsGrow;
    wxChoice* Choice_SingleStrand_Colors;
    wxBitmapButton* BitmapButton_MorphUseHeadEndColor;
    wxBitmapButton* BitmapButton_Piano_MapFilename;
    wxBitmapButton* BitmapButton_NumberStrobes;
    wxStaticText* StaticText4;
    wxStaticText* StaticText38;
    wxStaticText* StaticText86;
    wxStaticText* StaticText42;
    wxBitmapButton* BitmapButton_PicturesSpeed;
    wxScrolledWindow* Panel1_Curtain;
    wxChoice* Choice_Piano_KeyPlacement;
    wxStaticText* StaticText145;
    wxBitmapButton* BitmapButton_Pinwheel_ArmSize;
    wxBitmapButton* BitmapButton_Shockwave_Accel;
    wxStaticText* StaticText140;
    wxButton* ButtonGledFile;
    wxBitmapButton* BitmapButton_TextPosition4;
    wxButton* Button_Piano_CueFilename;
    wxBitmapButton* BitmapButton_TextCount1;
    wxPanel* Panel_Text2;
    wxChoice* Choice_Curtain_Edge;
    wxSlider* Slider_Spirograph_d;
    wxBitmapButton* BitmapButton_Galaxy_End_Radius;
    wxChoice* Choice_Wave_Type;
    wxStaticText* StaticText91;
    wxCheckBox* CheckBox_Circles_Radial_3D;
    wxBitmapButton* BitmapButton_Circles_Linear_Fade;
    wxBitmapButton* BitmapButton_Shockwave_Start_Radius;
    wxSlider* Slider_Fireworks_Number_Explosions;
    wxBitmapButton* BitmapButton_CirclesPlasma;
    wxSlider* Slider_Shimmer_Duty_Factor;
    wxPanel* Panel_Text1;
    wxScrolledWindow* Panel1_Ripple;
    wxBitmapButton* BitmapButton_Wave_Thickness;
    wxBitmapButton* BitmapButton_TextToCenter2;
    wxStaticText* StaticText45;
    wxPanel* Panel3;
    wxStaticText* StaticText11;
    wxBitmapButton* BitmapButton_Glediator_Filename;
    wxBitmapButton* BitmapButton_CirclesBubbles;
    wxBitmapButton* BitmapButton_Fan_CenterX;
    wxStaticText* StaticText18;
    wxStaticText* StaticText131;
    wxStaticText* StaticText30;
    wxPanel* Panel1;
    wxButton* Button_Piano_ShapeFilename;
    wxCheckBox* CheckBox_MorphUseHeadStartColor;
    wxStaticText* StaticText106;
    wxScrolledWindow* Panel1_Circles;
    wxPanel* Panel_Text4;
    wxStaticText* StaticText148;
    wxBitmapButton* BitmapButton_LifeCount;
    wxSlider* Slider_Pinwheel_Arms;
    wxBitmapButton* BitmapButton_Fan_CenterY;
    wxSlider* Slider_Twinkle_Steps;
    wxStaticText* StaticText103;
    wxCheckBox* CheckBox_Chase_3dFade1;
    wxScrolledWindow* Panel1_Piano;
    wxBitmapButton* BitmapButton_CurtainSwag;
    wxCheckBox* CheckBox_Shockwave_Blend_Edges;
    wxBitmapButton* BitmapButton_Morph_Start_X2;
    wxStaticText* StaticText116;
    wxStaticText* StaticText48;
    wxScrolledWindow* Panel1_Faces;
    wxBitmapButton* BitmapButton_MorphUseHeadStartColor;
    wxStaticText* StaticText37;
    wxCheckBox* CheckBox_Spirlas_Shrink;
    wxChoice* Choice_Butterfly_Colors;
    wxBitmapButton* BitmapButton_MeteorsLength;
    wxStaticText* StaticText1;
    wxSlider* Slider_Circles_Size;
    wxBitmapButton* BitmapButton_TextToCenter4;
    wxStaticText* StaticText22;
    wxBitmapButton* BitmapButton_TextPosition3;
    wxCheckBox* CheckBox_Circles_Radial;
    wxBitmapButton* BitmapButton_ButterflyChunks;
    wxBitmapButton* BitmapButton_Galaxy_CenterY;
    wxStaticText* StaticText115;
    wxBitmapButton* BitmapButton_Fan_Blade_Angle;
    wxStaticText* StaticText87;
    wxTextCtrl* TextCtrl_Text_Line3;
    wxCheckBox* CheckBox_Circles_Bounce;
    wxStaticText* StaticText118;
    wxStaticText* StaticText92;
    wxStaticText* StaticText121;
    wxStaticText* StaticText52;
    wxSlider* Slider_Chase_Spacing1;
    wxSlider* Slider_Snowstorm_Length;
    wxPanel* Panel2;
    wxTextCtrl* TextCtrl_Text_Line1;
    wxStaticText* StaticText122;
    wxBitmapButton* BitmapButton_SingleStrand_Colors;
    wxBitmapButton* BitmapButton_Shimmer_Blink_Timing;
    wxStaticText* StaticText10;
    wxCheckBox* CheckBox_Pinwheel_Rotation;
    wxBitmapButton* BitmapButton_Morph_End_Y1;
    wxChoice* Choice_Curtain_Effect;
    wxBitmapButton* BitmapButton_Chase_Group_All;
    wxBitmapButton* BitmapButton_TextPosition1;
    wxChoice* Choice_Text_Effect4;
    wxBitmapButton* BitmapButton_LifeSpeed;
    wxBitmapButton* BitmapButton_Strobe_Type;
    wxScrolledWindow* Panel1_SingleStrand;
    wxStaticText* StaticText166;
    wxSlider* Slider_Garlands_Spacing;
    wxBitmapButton* BitmapButton_CirclesCount;
    wxCheckBox* CheckBox_Mirror_Wave;
    wxBitmapButton* BitmapButton_SpiralsCount;
    wxScrolledWindow* Panel1_Snowflakes;
    wxStaticText* StaticText149;
    wxStaticText* StaticText24;
    wxCheckBox* CheckBox_MorphUseHeadEndColor;
    wxStaticText* StaticText104;
    wxSlider* Slider_Snowflakes_Count;
    wxBitmapButton* BitmapButton_Wave_MirrorWave;
    wxStaticText* StaticText137;
    wxBitmapButton* BitmapButton_Galaxy_Revolutions;
    wxChoice* Choice_Text_Dir3;
    wxBitmapButton* BitmapButton_PinwheelThickness;
    wxBitmapButton* BitmapButton_Galaxy_Start_Angle;
    wxScrolledWindow* Panel1_Fire;
    wxCheckBox* CheckBox_Galaxy_Blend_Edges;
    wxBitmapButton* BitmapButton_Galaxy_Accel;
    wxSlider* Slider_Spirals_Thickness;
    wxBitmapButton* BitmapButton_TextToCenter1;
    wxStaticText* StaticText158;
    wxSlider* Slider_Number_Waves;
    wxStaticText* StaticText142;
    wxStaticText* StaticText13;
    wxBitmapButton* BitmapButton_Galaxy_Start_Width;
    wxSlider* Slider_Meteors_Length;
    wxBitmapButton* BitmapButton_Piano_KeyPlacement;
    wxStaticText* StaticText_Piano_NumRows;
    wxBitmapButton* BitmapButton_CirclesRadial;
    wxBitmapButton* BitmapButton_FireworksNumberExplosions;
    wxBitmapButton* BitmapButton_Morph_End_X2;
    wxStaticText* StaticText152;
    wxPanel* PictureEndPositionPanel;
    wxStaticText* StaticText65;
    wxSlider* Slider_Shimmer_Blinks_Per_Row;
    wxStaticText* StaticText60;
    wxChoice* Choice_Wave_Direction;
    wxBitmapButton* BitmapButton_MeteorsSwirlIntensity;
    wxStaticText* StaticText49;
    wxSlider* Slider_Snowflakes_Type;
    wxStaticText* StaticText64;
    wxBitmapButton* BitmapButton_Chase_Spacing1;
    wxSlider* Slider_Fireworks_Count;
    wxBitmapButton* BitmapButton_CurtainEdge;
    wxStaticText* StaticText32;
    wxStaticText* StaticText36;
    wxStaticText* StaticText14;
    wxNotebook* Notebook_Galaxy;
    wxStaticText* StaticText75;
    wxStaticText* StaticText134;
    wxPanel* Panel5;
    wxStaticText* StaticText56;
    wxStaticText* StaticText8;
    wxStaticText* StaticText25;
    wxSlider* Slider_Strobe_Type;
    wxStaticText* StaticText15_layout_kludge_1;
    wxBitmapButton* BitmapButton_CirclesCollide;
    wxStaticText* StaticText28;
    wxStaticText* StaticText123;
    wxStaticText* StaticText89;
    wxChoice* Choice_Meteors_Type;
    wxStaticText* StaticText23;
    wxStaticText* StaticText63;
    wxCheckBox* CheckBox_Circles_Plasma;
    wxStaticText* StaticText130;
    wxStaticText* StaticText55;
    wxCheckBox* CheckBox_Spirals_3D;
    wxBitmapButton* BitmapButton_ColorWashHFade;
    wxSlider* Slider_Fireworks_Velocity;
    wxStaticText* StaticText15;
    wxSlider* Slider_Ripple_Thickness;
    wxSlider* Slider_Spirals_Count;
    wxSlider* Slider_Piano_NumRows;
    wxChoice* Choice_Text_Dir4;
    wxBitmapButton* BitmapButton_TextToCenter3;
    wxCheckBox* CheckBox_Bars_3D;
    wxNotebook* Notebook3;
    wxCheckBox* CheckBox_Bars_Highlight;
    wxBitmapButton* BitmapButton8;
    wxSlider* Slider_Butterfly_Skip;
    wxBitmapButton* BitmapButton_SnowstormCount;
    wxCheckBox* CheckBox_Fan_Blend_Edges;
    wxSlider* Slider_Spirograph_R;
    wxBitmapButton* BitmapButton_SpiralsShrink;
    wxStaticText* StaticText39;
    wxStaticText* StaticText124;
    wxStaticText* StaticText78;
    wxBitmapButton* BitmapButton_LayerEffect;
    wxStaticText* StaticText67;
    wxScrolledWindow* Panel1_Meteors;
    wxBitmapButton* BitmapButton_MorphAccel;
    wxScrolledWindow* Panel1_Butterfly;
    wxBitmapButton* BitmapButton_Piano_NumRows;
    wxBitmapButton* BitmapButton_Morph_Start_Y1;
    wxBitmapButton* BitmapButton_ButterflySkip;
    wxBitmapButton* BitmapButton_TextCount2;
    wxStaticText* StaticText108;
    wxBitmapButton* BitmapButton_FireHeight;
    wxBitmapButton* BitmapButton_Fan_Accel;
    wxBitmapButton* BitmapButton_FireworksCount;
    wxStaticText* StaticText146;
    wxBitmapButton* BitmapButton_SpiralsDirection;
    wxStaticText* StaticText27;
    wxBitmapButton* BitmapButton_PicturesFilename;
    wxNotebook* Notebook_Morph;
    wxStaticText* StaticText144;
    wxSlider* Slider_Life_Count;
    wxChoice* Choice_Pinwheel_3D;
    wxChoice* Choice_Text_Effect3;
    wxStaticText* StaticText110;
    wxStaticText* StaticText70;
    wxStaticText* StaticText35;
    wxStaticText* StaticText85;
    wxNotebook* Notebook2;
    wxBitmapButton* BitmapButton_GarlandsType;
    wxBitmapButton* BitmapButton_random;
    wxBitmapButton* BitmapButton_PinwheelNumberArms;
    wxStaticText* StaticText153;
    wxSlider* Slider_Bars_BarCount;
    wxCheckBox* CheckBox_Morph_End_Link;
    wxBitmapButton* BitmapButton_MovieIs20FPS;
    wxStaticText* StaticText127;
    wxBitmapButton* BitmapButton_Morph_End_Y2;
    wxBitmapButton* BitmapButton_Pinwheel3D;
    wxBitmapButton* BitmapButton_Ripple3D;
    wxBitmapButton* BitmapButton_TextFont1;
    wxSlider* Slider_Pinwheel_Thickness;
    wxStaticText* StaticText109;
    wxTextCtrl* TextCtrl_Piano_ShapeFilename;
    wxBitmapButton* BitmapButton_PinwheelTwist;
    wxStaticText* StaticText156;
    wxStaticText* StaticText76;
    wxBitmapButton* BitmapButton_Fan_Element_Width;
    wxStaticText* StaticText14_layout_kludge2;
    wxCheckBox* CheckBox_Fire_GrowFire;
    wxBitmapButton* BitmapButton_TextEffect3;
    wxTextCtrl* TextCtrl_Text_Line2;
    wxStaticText* StaticText72;
    wxSlider* Slider_Fire_HueShift;
    wxBitmapButton* BitmapButton_Number_Chases;
    wxBitmapButton* BitmapButton_TextDir2;
    wxBitmapButton* BitmapButton_Fan_Start_Angle;
    wxChoice* Choice_Text_Dir2;
    wxStaticText* StaticText53;
    wxPanel* Panel4;
    wxChoice* Choice_Text_Count4;
    wxBitmapButton* BitmapButton_ButterflyStyle;
    wxScrolledWindow* Panel1_Spirograph;
    wxStaticText* StaticText129;
    wxNotebook* SingleStrandEffectType;
    wxSlider* Slider_Text_Position4;
    wxBitmapButton* BitmapButton_TextEffect4;
    wxBitmapButton* BitmapButton_Skips_BandSize;
    wxCheckBox* CheckBox_Chase_Group_All;
    wxStaticText* StaticText40;
    wxBitmapButton* BitmapButton_TwinkleCount;
    wxChoice* Choice_Meteors_Effect;
    wxStaticText* StaticText21;
    wxSlider* Slider_Wave_Height;
    wxSlider* Slider_Text_Position3;
    wxBitmapButton* BitmapButton_Skips_SkipSize;
    wxBitmapButton* BitmapButton_Highlight;
    wxSlider* Slider_Text_Position1;
    wxBitmapButton* BitmapButton_Morph_Start_X1;
    wxSlider* Slider_Garlands_Type;
    wxBitmapButton* BitmapButton_Piano_NumKeys;
    wxBitmapButton* BitmapButton_ShowHeadAtStart;
    wxStaticText* StaticText57;
    wxBitmapButton* BitmapButton_FireGrow;
    wxBitmapButton* BitmapButton_Morph_Start_Y2;
    wxStaticText* StaticText112;
    wxStaticText* StaticText147;
    wxStaticText* StaticText84;
    wxStaticText* StaticText90;
    wxStaticText* StaticText93;
    wxScrolledWindow* Panel1_Garlands;
    wxBitmapButton* BitmapButton_Color_Mix1;
    wxStaticText* StaticText61;
    wxBitmapButton* BitmapButton_Galaxy_Start_Radius;
    wxStaticText* StaticText62;
    wxStaticText* StaticText150;
    wxCheckBox* CheckBox_Spirals_Grow;
    wxBitmapButton* BitmapButton_PaletteRep;
    wxStaticText* StaticText157;
    wxBitmapButton* BitmapButton_Piano_Style;
    wxBitmapButton* BitmapButton_PinwheelRotation;
    wxBitmapButton* BitmapButton_locked;
    wxButton* Button_Piano_MapFilename;
    wxBitmapButton* BitmapButton_TextPosition2;
    wxBitmapButton* BitmapButton_Morph_End_X1;
    wxBitmapButton* BitmapButton_normal;
    wxTextCtrl* TextCtrl_Text_Line4;
    wxScrolledWindow* Panel1_CoroFaces;
    wxStaticText* StaticText54;
    wxTextCtrl* TextCtrl_Piano_CueFilename;
    wxStaticText* StaticText107;
    wxSlider* Slider_Spirograph_r;
    wxStaticText* StaticText7;
    wxScrolledWindow* Panel1_Galaxy;
    wxBitmapButton* BitmapButton_CurtainEffect;
    wxBitmapButton* BitmapButton_Chase_Type1;
    wxScrolledWindow* Panel1_Fan;
    wxBitmapButton* BitmapButton_Shockwave_End_Radius;
    wxSlider* Slider_Meteors_Swirl_Intensity;
    wxStaticText* StaticText79;
    wxScrolledWindow* Panel1_Wave;
    wxBitmapButton* BitmapButton_Fan_End_Radius;
    wxStaticText* StaticText99;
    wxSlider* Slider_Butterfly_Chunks;
    wxTextCtrl* TextCtrl_Piano_MapFilename;
    wxScrolledWindow* Panel1_Pictures;
    wxBitmapButton* BitmapButton_Fan_Duration;
    wxSlider* Slider_Twinkle_Count;
    wxBitmapButton* BitmapButton_TextFont4;
    wxSlider* Slider_Color_Mix1;
    wxCheckBox* CheckBox_Galaxy_Reverse;
    wxCheckBox* CheckBox_ColorWash_HFade;
    wxStaticText* StaticText132;
    wxBitmapButton* BitmapButton_Direction;
    wxCheckBox* CheckBox_Fan_Reverse;
    wxStaticText* StaticText128;
    wxStaticText* StaticText44;
    wxStaticText* StaticText95;
    wxScrolledWindow* Panel1_Text;
    wxChoice* Choice_Butterfly_Direction;
    wxBitmapButton* BitmapButton_Wave_Height;
    wxStaticText* StaticText98;
    wxSlider* Slider_Meteors_Count;
    wxBitmapButton* BitmapButton_TwinkleStrobe;
    wxStaticText* StaticText105;
    wxStaticText* StaticText88;
    wxStaticText* StaticText135;
    wxScrolledWindow* Panel1_Shockwave;
    wxBitmapButton* BitmapButton_Fan_Revolutions;
    wxStaticText* StaticText59;
    wxChoice* Choice_Text_Effect2;
    wxBitmapButton* BitmapButton_MorphDuration;
    wxBitmapButton* BitmapButton_NumberWaves;
    wxScrolledWindow* Panel1_Life;
    wxStaticText* StaticText_Piano_NumKeys;
    wxStaticText* StaticText68;
    wxBitmapButton* BitmapButton_Shockwave_CenterY;
    wxStaticText* StaticText141;
    wxTextCtrl* TextCtrl_Glediator_Filename;
    wxStaticText* StaticText97;
    wxCheckBox* CheckBox_Pictures_Is20FPS;
    wxStaticText* StaticText71;
    wxSlider* Slider_Curtain_Swag;
    wxStaticText* StaticText43;
    wxStaticText* StaticText151;
    wxCheckBox* CheckBox_Circles_Random_m;
    wxBitmapButton* BitmapButton_TextEffect1;
    wxStaticText* StaticText66;
    wxBitmapButton* BitmapButton_Fan_Num_Blades;
    wxPanel* Panel_Text3;
    wxSlider* Slider_PinwheelXC;
    wxBitmapButton* BitmapButton_Shockwave_CenterX;
    wxChoice* Choice_Piano_Style;
    wxBitmapButton* BitmapButton_ColorWashVFade;
    wxChoice* Choice_Faces_Phoneme;
    wxStaticText* StaticText100;
    wxBitmapButton* BitmapButton20;
    wxScrolledWindow* Panel1_Morph;
    wxBitmapButton* BitmapButton_Shockwave_Start_Width;
    wxSlider* Slider_Circles_Count;
    wxBitmapButton* BitmapButton_MorphStartLength;
    wxBitmapButton* BitmapButton_FireworksFade;
    wxSlider* Slider_Tree_Branches;
    wxBitmapButton* BitmapButton_Spirographd;
    wxBitmapButton* BitmapButton_Ripple_Movement;
    wxSlider* Slider_Butterfly_Style;
    wxBitmapButton* BitmapButton_Wave_Direction;
    wxStaticText* StaticText26;
    wxCheckBox* CheckBox_Piano_Clipping;
    wxStaticText* StaticText139;
    wxChoice* Choice_CoroFaces_Eyes;
    wxBitmapButton* BitmapButton_TextDir3;
    wxBitmapButton* BitmapButton_SpiralsThickness;
    wxCheckBox* CheckBox_Spirograph_Animate;
    wxCheckBox* CheckBox_Ripple3D;
    wxBitmapButton* BitmapButton_ColorWashCount;
    wxBitmapButton* BitmapButton_CirclesRadial3D;
    wxStaticText* StaticText50;
    wxSlider* Slider_Text_Position2;
    wxChoice* Choice_Ripple_Object_To_Draw;
    wxStaticText* StaticText81;
    wxStaticText* StaticText58;
    wxBitmapButton* BitmapButton_TextDir1;
    wxBitmapButton* BitmapButton_CurtainRepeat;
    wxScrolledWindow* Panel1_Fireworks;
    wxCheckBox* CheckBox_Pictures_WrapX;
    wxSlider* Slider_Fire_Height;
    wxStaticText* StaticText17;
    wxBitmapButton* BitmapButton_Fan_Blade_Width;
    wxBitmapButton* BitmapButton_SnowstormLength;
    wxCheckBox* CheckBox_CoroFaces_Outline;
    wxBitmapButton* BitmapButton_PicturesDirection;
    wxBitmapButton* BitmapButton_Shimmer_Duty_Factor;
    wxBitmapButton* BitmapButton_SpiralsBlend;
    wxBitmapButton* BitmapButton_WaveType;
    wxSlider* Slider_Snowstorm_Count;
    wxChoice* Choice_Fill_Colors;
    wxChoice* Choice_Text_Count2;
    wxBitmapButton* BitmapButton_MorphEndLength;
    wxScrolledWindow* Panel1_Glediator;
    wxSlider* Slider_PinwheelYC;
    wxStaticText* StaticText73;
    wxScrolledWindow* Panel1_Pinwheel;
    wxBitmapButton* BitmapButton_ButterflyColors;
    wxBitmapButton* BitmapButton_MeteorsType;
    wxStaticText* StaticText119;
    wxStaticText* StaticText117;
    wxBitmapButton* BitmapButton_Galaxy_Duration;
    wxScrolledWindow* Panel1_Shimmer;
    wxStaticText* StaticText47;
    wxBitmapButton* BitmapButton_Shimmer_Use_All_Colors;
    wxCheckBox* CheckBox_Circles_Collide;
    wxBitmapButton* BitmapButton_Shockwave_End_Width;
    wxStaticText* StaticText69;
    wxStaticText* StaticText3;
    wxSlider* Slider_Life_Seed;
    wxBitmapButton* BitmapButton_Piano_CueFilename;
    wxBitmapButton* BitmapButton_Ripple_Object_To_Draw;
    wxBitmapButton* BitmapButton_CirclesBounce;
    wxChoice* Choice_CoroFaces_Phoneme;
    wxStaticText* StaticText80;
    wxStaticText* StaticText126;
    wxStaticText* StaticText12;
    wxChoice* Choice_Pictures_Direction;
    wxScrolledWindow* Panel1_Twinkle;
    wxStaticText* StaticText31;
    wxChoice* Choice_Bars_Direction;
    wxCheckBox* CheckBox_Galaxy_Inward;
    wxStaticText* StaticText111;
    wxBitmapButton* BitmapButton_RippleThickness;
    wxChoice* Choice_Text_Effect1;
    wxBitmapButton* BitmapButton_SpirographR;
    wxBitmapButton* BitmapButton_MeteorsEffect;
    wxChoice* Choice_Text_Count3;
    wxBitmapButton* BitmapButton_Skips_StartingPosition;
    wxCheckBox* CheckBox_Circles_Linear_Fade;
    wxChoicebook* EffectChoicebook;
    wxStaticText* StaticText143;
    wxCheckBox* CheckBox_Shimmer_Use_All_Colors;
    wxStaticText* StaticText136;
    wxSlider* Slider_Spirals_Rotation;
    wxStaticText* StaticText82;
    wxBitmapButton* BitmapButton_Spirographr;
    wxStaticText* StaticText51;
    wxCheckBox* CheckBox_Spirals_Blend;
    wxStaticText* StaticText33;
    wxBitmapButton* BitmapButton_Fan_Start_Radius;
    wxScrolledWindow* Panel1_ColorWash;
    wxSlider* Slider_Pinwheel_Twist;
    wxCheckBox* CheckBox_ColorWash_VFade;
    wxBitmapButton* BitmapButton_Shimmer_Blinks_Per_Row;
    wxBitmapButton* BitmapButton_SnowflakesCount;
    wxBitmapButton* BitmapButton_TextFont3;
    wxSlider* Slider_Strobe_Duration;
    wxSlider* Slider_Thickness_Percentage;
    wxStaticText* StaticText5;
    wxCheckBox* CheckBox_ShowHeadAtStart;
    wxBitmapButton* BitmapButton_TextEffect2;
    wxBitmapButton* BitmapButton_Skips_Direction;
    wxBitmapButton* BitmapButton_CirclesSize;
    wxBitmapButton* BitmapButton_MeteorsCount;
    wxCheckBox* CheckBox_Curtain_Repeat;
    wxStaticText* StaticText155;
    wxBitmapButton* BitmapButton_FireWidth;
    wxChoice* Choice_Chase_Type1;
    wxStaticText* StaticText16;
    wxChoice* Choice_Skips_Direction;
    wxScrolledWindow* Panel1_On;
    wxSlider* Slider_Fireworks_Fade;
    wxBitmapButton* BitmapButton_Piano_ShapeFilename;
    wxCheckBox* CheckBox_Shimmer_Blink_Timing;
    wxScrolledWindow* Panel1_Spirals;
    wxStaticText* StaticText138;
    wxChoice* Choice_Text_Count1;
    wxBitmapButton* BitmapButton_FireworksVelocity;
    wxSlider* Slider_Piano_NumKeys;
    wxScrolledWindow* Panel1_Bars;
    wxCheckBox* CheckBox_Twinkle_Strobe;
    wxStaticText* StaticText20;
    wxBitmapButton* BitmapButton_Chase_3dFade1;
    wxChoice* Choice_Ripple_Movement;
    wxScrolledWindow* Panel1_Strobe;
    wxStaticText* StaticText94;
    wxStaticText* StaticText46;
    wxBitmapButton* BitmapButton_TextDir4;
    wxStaticText* StaticText77;
    wxCheckBox* CheckBox_Circles_Bubbles;
    wxBitmapButton* BitmapButton_SpiralsRotation;
    wxStaticText* StaticText83;
    wxBitmapButton* BitmapButton_TextCount3;
    wxScrolledWindow* Panel1_Off;
    wxStaticText* StaticText74;
    wxStaticText* StaticText41;
    wxStaticText* StaticText29;
    wxStaticText* StaticText34;
    wxStaticText* StaticText101;
    wxStaticText* StaticText102;
    wxBitmapButton* BitmapButton_3D;
    wxStaticText* StaticText9;
    wxBitmapButton* BitmapButton_TreeBranches;
    wxBitmapButton* BitmapButton_SpirographAnimate;
    wxScrolledWindow* Panel1_Tree;
    wxBitmapButton* BitmapButton_Spirals3D;
    wxStaticText* StaticText159;
    //*)

protected:

    //(*Identifiers(EffectsPanel)
    static const long ID_STATICTEXT100;
    static const long ID_STATICTEXT120;
    static const long ID_PANEL19;
    static const long ID_STATICTEXT75;
    static const long IDD_SLIDER_Eff_On_Start;
    static const long ID_TEXTCTRL_Eff_On_Start;
    static const long IDD_SLIDER_Eff_On_End;
    static const long ID_TEXTCTRL_Eff_On_End;
    static const long ID_PANEL25;
    static const long ID_STATICTEXT25;
    static const long ID_SLIDER_Bars_BarCount;
    static const long ID_BITMAPBUTTON_SLIDER_Bars_BarCount;
    static const long ID_STATICTEXT26;
    static const long ID_CHOICE_Bars_Direction;
    static const long ID_BITMAPBUTTON_CHOICE_Bars_Direction;
    static const long ID_CHECKBOX_Bars_Highlight;
    static const long ID_BITMAPBUTTON_CHECKBOX_Bars_Highlight;
    static const long ID_CHECKBOX_Bars_3D;
    static const long ID_BITMAPBUTTON_CHECKBOX_Bars_3D;
    static const long ID_PANEL8;
    static const long ID_STATICTEXT27;
    static const long ID_CHOICE_Butterfly_Colors;
    static const long ID_BITMAPBUTTON_CHOICE_Butterfly_Color;
    static const long ID_STATICTEXT28;
    static const long ID_SLIDER_Butterfly_Style;
    static const long ID_BITMAPBUTTON_SLIDER_Butterfly_Style;
    static const long ID_STATICTEXT30;
    static const long ID_SLIDER_Butterfly_Chunks;
    static const long ID_BITMAPBUTTON_SLIDER_Butterfly_Chunks;
    static const long ID_STATICTEXT31;
    static const long ID_SLIDER_Butterfly_Skip;
    static const long ID_BITMAPBUTTON_SLIDER_Butterfly_Skip;
    static const long ID_STATICTEXT60;
    static const long ID_CHOICE_Butterfly_Direction;
    static const long ID_BITMAPBUTTON9;
    static const long ID_PANEL10;
    static const long ID_STATICTEXT137;
    static const long ID_SLIDER_Circles_Count;
    static const long ID_BITMAPBUTTON_SLIDER_Circles_Count;
    static const long ID_STATICTEXT138;
    static const long ID_SLIDER_Circles_Size;
    static const long ID_BITMAPBUTTON_SLIDER_Circles_Size;
    static const long ID_CHECKBOX_Circles_Bounce;
    static const long ID_BITMAPBUTTON_CHECKBOX_Circles_Bounce;
    static const long ID_CHECKBOX_Circles_Radial;
    static const long ID_BITMAPBUTTON_CHECKBOX_Circles_Radial;
    static const long ID_CHECKBOX_Circles_Plasma;
    static const long ID_BITMAPBUTTON_CHECKBOX_Circles_Plasma;
    static const long ID_CHECKBOX_Circles_Radial_3D;
    static const long ID_BITMAPBUTTON_CHECKBOX_Circles_Radial_3D;
    static const long ID_CHECKBOX_Circles_Bubbles;
    static const long ID_BITMAPBUTTON_CirclesBubbles;
    static const long ID_CHECKBOX_Circles_Collide;
    static const long ID_BITMAPBUTTON_CHECKBOX_Circles_Collide;
    static const long ID_CHECKBOX_Circles_Random_m;
    static const long ID_BITMAPBUTTON_CHECKBOX_Circles_Random_m;
    static const long ID_CHECKBOX_Circles_Linear_Fade;
    static const long ID_BITMAPBUTTON_CHECKBOX_Circles_Linear_Fade;
    static const long ID_PANEL37;
    static const long ID_STATICTEXT21;
    static const long ID_SLIDER_ColorWash_Count;
    static const long IDD_TEXTCTRL_ColorWash_Count;
    static const long ID_BITMAPBUTTON_SLIDER_ColorWash_Count;
    static const long ID_STATICTEXT33;
    static const long ID_CHECKBOX_ColorWash_VFade;
    static const long ID_BITMAPBUTTON_CHECKBOX_ColorWash_VFade;
    static const long ID_STATICTEXT32;
    static const long ID_CHECKBOX_ColorWash_HFade;
    static const long ID_BITMAPBUTTON_CHECKBOX_ColorWash_HFade;
    static const long ID_CHECKBOX_ColorWash_EntireModel;
    static const long ID_SLIDER_ColorWash_X1;
    static const long IDD_TEXTCTRL_ColorWash_X1;
    static const long IDD_TEXTCTRL_ColorWash_Y1;
    static const long ID_SLIDER_ColorWash_Y1;
    static const long ID_PANEL46;
    static const long ID_SLIDER_ColorWash_X2;
    static const long IDD_TEXTCTRL_ColorWash_X2;
    static const long IDD_TEXTCTRL_ColorWash_Y2;
    static const long ID_SLIDER_ColorWash_Y2;
    static const long ID_PANEL47;
    static const long IDD_NOTEBOOK_ColorWashRect;
    static const long ID_PANEL5;
    static const long ID_STATICTEXT73;
    static const long ID_CHOICE_CoroFaces_Phoneme;
    static const long ID_STATICTEXT64;
    static const long ID_CHOICE_CoroFaces_Eyes;
    static const long ID_STATICTEXT66;
    static const long ID_CHECKBOX_CoroFaces_Outline;
    static const long ID_PANEL28;
    static const long ID_STATICTEXT6;
    static const long ID_CHOICE_Curtain_Edge;
    static const long ID_BITMAPBUTTON_CHOICE_Curtain_Edge;
    static const long ID_STATICTEXT5;
    static const long ID_CHOICE_Curtain_Effect;
    static const long ID_BITMAPBUTTON_CHOICE_Curtain_Effect;
    static const long ID_STATICTEXT7;
    static const long ID_SLIDER_Curtain_Swag;
    static const long ID_BITMAPBUTTON_SLIDER_Curtain_Swag;
    static const long ID_CHECKBOX_Curtain_Repeat;
    static const long ID_BITMAPBUTTON_CHECKBOX_Curtain_Repeat;
    static const long ID_PANEL1;
    static const long ID_STATICTEXT118;
    static const long ID_STATICTEXT15;
    static const long ID_CHOICE_Faces_Phoneme;
    static const long ID_PANEL6;
    static const long ID_SLIDER_Fan_CenterX;
    static const long IDD_TEXTCTRL_Fan_CenterX;
    static const long ID_BITMAPBUTTON_SLIDER_Fan_CenterX;
    static const long ID_STATICTEXT128;
    static const long ID_SLIDER_Fan_CenterY;
    static const long IDD_TEXTCTRL_Fan_CenterY;
    static const long ID_BITMAPBUTTON_SLIDER_Fan_CenterY;
    static const long ID_STATICTEXT136;
    static const long ID_SLIDER_Fan_Start_Radius;
    static const long IDD_TEXTCTRL_Fan_Start_Radius;
    static const long ID_BITMAPBUTTON_SLIDER_Fan_Start_Radius;
    static const long ID_STATICTEXT142;
    static const long ID_SLIDER_Fan_Start_Angle;
    static const long IDD_TEXTCTRL_Fan_Start_Angle;
    static const long ID_BITMAPBUTTON_SLIDER_Fan_Start_Angle;
    static const long ID_STATICTEXT141;
    static const long ID_SLIDER_Fan_End_Radius;
    static const long IDD_TEXTCTRL_Fan_End_Radius;
    static const long ID_BITMAPBUTTON_SLIDER_Fan_End_Radius;
    static const long ID_STATICTEXT145;
    static const long ID_SLIDER_Fan_Revolutions;
    static const long IDD_TEXTCTRL_Fan_Revolutions;
    static const long ID_BITMAPBUTTON_SLIDER_Fan_Revolutions;
    static const long ID_PANEL38;
    static const long ID_STATICTEXT148;
    static const long ID_SLIDER_Fan_Num_Blades;
    static const long IDD_TEXTCTRL_Fan_Num_Blades;
    static const long ID_BITMAPBUTTON_SLIDER_Fan_Num_Blades;
    static const long ID_STATICTEXT149;
    static const long ID_SLIDER_Fan_Blade_Width;
    static const long IDD_TEXTCTRL_Fan_Blade_Width;
    static const long ID_BITMAPBUTTON_SLIDER_Fan_Blade_Width;
    static const long ID_STATICTEXT150;
    static const long ID_SLIDER_Fan_Blade_Angle;
    static const long IDD_TEXTCTRL_Fan_Blade_Angle;
    static const long ID_BITMAPBUTTON_SLIDER_Fan_Blade_Angle;
    static const long ID_STATICTEXT143;
    static const long ID_SLIDER_Fan_Num_Elements;
    static const long IDD_TEXTCTRL_Fan_Num_Elements;
    static const long ID_BITMAPBUTTON_SLIDER_Fan_Num_Elements;
    static const long ID_STATICTEXT144;
    static const long ID_SLIDER_Fan_Element_Width;
    static const long IDD_TEXTCTRL_Fan_Element_Width;
    static const long ID_BITMAPBUTTON_SLIDER_Fan_Element_Width;
    static const long ID_PANEL42;
    static const long ID_STATICTEXT146;
    static const long ID_SLIDER_Fan_Duration;
    static const long IDD_TEXTCTRL_Fan_Duration;
    static const long ID_BITMAPBUTTON_SLIDER_Fan_Duration;
    static const long ID_STATICTEXT147;
    static const long ID_SLIDER_Fan_Accel;
    static const long IDD_TEXTCTRL_Fan_Accel;
    static const long ID_BITMAPBUTTON_SLIDER_Fan_Accel;
    static const long ID_CHECKBOX_Fan_Reverse;
    static const long ID_CHECKBOX_Fan_Blend_Edges;
    static const long ID_PANEL41;
    static const long ID_NOTEBOOK_Fan;
    static const long ID_SCROLLEDWINDOW_FAN;
    static const long ID_STATICTEXT84;
    static const long ID_SLIDER_Fire_Height;
    static const long ID_BITMAPBUTTON_SLIDER_Fire_Height;
    static const long ID_STATICTEXT133;
    static const long ID_SLIDER_Fire_HueShift;
    static const long ID_BITMAPBUTTON_SLIDER_Fire_HueShift;
    static const long ID_STATICTEXT135;
    static const long ID_CHECKBOX_Fire_GrowFire;
    static const long ID_BITMAPBUTTON_CHECKBOX_Fire_GrowFire;
    static const long ID_PANEL12;
    static const long ID_STATICTEXT95;
    static const long ID_SLIDER_Fireworks_Number_Explosions;
    static const long ID_BITMAPBUTTON_SLIDER_Fireworks_Number_Explosions;
    static const long ID_STATICTEXT92;
    static const long ID_SLIDER_Fireworks_Count;
    static const long ID_BITMAPBUTTON_SLIDER_Fireworks_Count;
    static const long ID_STATICTEXT94;
    static const long ID_SLIDER_Fireworks_Velocity;
    static const long ID_BITMAPBUTTON_SLIDER_Fireworks_Velocity;
    static const long ID_STATICTEXT96;
    static const long ID_SLIDER_Fireworks_Fade;
    static const long ID_BITMAPBUTTON_SLIDER_Fireworks_Fade;
    static const long ID_PANEL36;
    static const long ID_SLIDER_Galaxy_CenterX;
    static const long IDD_TEXTCTRL_Galaxy_CenterX;
    static const long ID_BITMAPBUTTON_SLIDER_Galaxy_CenterX;
    static const long ID_STATICTEXT2;
    static const long ID_SLIDER_Galaxy_CenterY;
    static const long IDD_TEXTCTRL_Galaxy_CenterY;
    static const long ID_BITMAPBUTTON_SLIDER_Galaxy_CenterY;
    static const long ID_STATICTEXT125;
    static const long ID_SLIDER_Galaxy_Start_Radius;
    static const long IDD_TEXTCTRL_Galaxy_Start_Radius;
    static const long ID_BITMAPBUTTON_SLIDER_Galaxy_Start_Radius;
    static const long ID_STATICTEXT127;
    static const long ID_SLIDER_Galaxy_Start_Width;
    static const long IDD_TEXTCTRL_Galaxy_Start_Width;
    static const long ID_BITMAPBUTTON_SLIDER_Galaxy_Start_Width;
    static const long ID_STATICTEXT126;
    static const long ID_SLIDER_Galaxy_Start_Angle;
    static const long IDD_TEXTCTRL_Galaxy_Start_Angle;
    static const long ID_BITMAPBUTTON_SLIDER_Galaxy_Start_Angle;
    static const long ID_PANEL29;
    static const long ID_STATICTEXT130;
    static const long ID_SLIDER_Galaxy_End_Radius;
    static const long IDD_TEXTCTRL_Galaxy_End_Radius;
    static const long ID_BITMAPBUTTON_SLIDER_Galaxy_End_Radius;
    static const long ID_STATICTEXT132;
    static const long ID_SLIDER_Galaxy_End_Width;
    static const long IDD_TEXTCTRL_Galaxy_End_Width;
    static const long ID_BITMAPBUTTON_SLIDER_Galaxy_End_Width;
    static const long ID_STATICTEXT134;
    static const long ID_SLIDER_Galaxy_Revolutions;
    static const long IDD_TEXTCTRL_Galaxy_Revolutions;
    static const long ID_BITMAPBUTTON_SLIDER_Galaxy_Revolutions;
    static const long ID_PANEL31;
    static const long ID_STATICTEXT139;
    static const long ID_SLIDER_Galaxy_Duration;
    static const long IDD_TEXTCTRL_Galaxy_Duration;
    static const long ID_BITMAPBUTTON_SLIDER_Galaxy_Duration;
    static const long ID_STATICTEXT140;
    static const long ID_SLIDER_Galaxy_Accel;
    static const long IDD_TEXTCTRL_Galaxy_Accel;
    static const long ID_BITMAPBUTTON_SLIDER_Galaxy_Accel;
    static const long ID_CHECKBOX_Galaxy_Reverse;
    static const long ID_CHECKBOX_Galaxy_Blend_Edges;
    static const long ID_CHECKBOX_Galaxy_Inward;
    static const long ID_PANEL32;
    static const long ID_NOTEBOOK_Galaxy;
    static const long ID_SCROLLEDWINDOW1;
    static const long ID_STATICTEXT34;
    static const long ID_SLIDER_Garlands_Type;
    static const long ID_BITMAPBUTTON_SLIDER_Garlands_Type;
    static const long ID_STATICTEXT35;
    static const long ID_SLIDER_Garlands_Spacing;
    static const long ID_BITMAPBUTTON_SLIDER_Garlands_Spacing;
    static const long ID_PANEL14;
    static const long ID_BUTTON_GLED_FILE;
    static const long ID_BITMAPBUTTON10;
    static const long ID_TEXTCTRL_Glediator_Filename;
    static const long ID_PANEL17;
    static const long ID_STATICTEXT36;
    static const long ID_SLIDER_Life_Count;
    static const long ID_BITMAPBUTTON_SLIDER_Life_Count;
    static const long ID_STATICTEXT37;
    static const long ID_SLIDER_Life_Seed;
    static const long ID_BITMAPBUTTON_SLIDER_Life_Seed;
    static const long ID_PANEL16;
    static const long ID_STATICTEXT39;
    static const long ID_CHOICE_Meteors_Type;
    static const long ID_BITMAPBUTTON_CHOICE_Meteors_Type;
    static const long ID_STATICTEXT129;
    static const long ID_CHOICE_Meteors_Effect;
    static const long ID_BITMAPBUTTON_CHOICE_Meteors_Effect;
    static const long ID_STATICTEXT41;
    static const long ID_SLIDER_Meteors_Count;
    static const long ID_BITMAPBUTTON_SLIDER_Meteors_Count;
    static const long ID_STATICTEXT43;
    static const long ID_SLIDER_Meteors_Length;
    static const long ID_BITMAPBUTTON_SLIDER_Meteors_Length;
    static const long ID_STATICTEXT131;
    static const long ID_SLIDER_Meteors_Swirl_Intensity;
    static const long ID_BITMAPBUTTON_SLIDER_Meteors_Swirl_Intensity;
    static const long ID_PANEL18;
    static const long ID_SLIDER_Morph_Start_X1;
    static const long IDD_TEXTCTRL_Morph_Start_X1;
    static const long ID_BITMAPBUTTON_SLIDER_Morph_Start_X1;
    static const long ID_STATICTEXT3;
    static const long ID_SLIDER_Morph_Start_Y1;
    static const long IDD_TEXTCTRL_Morph_Start_Y1;
    static const long ID_BITMAPBUTTON_SLIDER_Morph_Start_Y1;
    static const long ID_STATICTEXT61;
    static const long ID_SLIDER_Morph_Start_X2;
    static const long IDD_TEXTCTRL_Morph_Start_X2;
    static const long ID_BITMAPBUTTON_SLIDER_Morph_Start_X2;
    static const long ID_STATICTEXT102;
    static const long ID_SLIDER_Morph_Start_Y2;
    static const long IDD_TEXTCTRL_Morph_Start_Y2;
    static const long ID_BITMAPBUTTON_SLIDER_Morph_Start_Y2;
    static const long ID_STATICTEXT115;
    static const long ID_SLIDER_MorphStartLength;
    static const long IDD_TEXTCTRL_MorphStartLength;
    static const long ID_BITMAPBUTTON_SLIDER_MorphStartLength;
    static const long ID_CHECKBOX_Morph_Start_Link;
    static const long ID_PANEL4;
    static const long ID_STATICTEXT116;
    static const long ID_SLIDER_Morph_End_X1;
    static const long IDD_TEXTCTRL_Morph_End_X1;
    static const long ID_BITMAPBUTTON_SLIDER_Morph_End_X1;
    static const long ID_STATICTEXT117;
    static const long ID_SLIDER_Morph_End_Y1;
    static const long IDD_TEXTCTRL_Morph_End_Y1;
    static const long ID_BITMAPBUTTON_SLIDER_Morph_End_Y1;
    static const long ID_STATICTEXT119;
    static const long ID_SLIDER_Morph_End_X2;
    static const long IDD_TEXTCTRL_Morph_End_X2;
    static const long ID_BITMAPBUTTON_SLIDER_Morph_End_X2;
    static const long ID_STATICTEXT121;
    static const long ID_SLIDER_Morph_End_Y2;
    static const long IDD_TEXTCTRL_Morph_End_Y2;
    static const long ID_BITMAPBUTTON_SLIDER_Morph_End_Y2;
    static const long ID_STATICTEXT122;
    static const long ID_SLIDER_MorphEndLength;
    static const long IDD_TEXTCTRL_MorphEndLength;
    static const long ID_BITMAPBUTTON_SLIDER_MorphEndLength;
    static const long ID_CHECKBOX_Morph_End_Link;
    static const long ID_PANEL27;
    static const long ID_STATICTEXT123;
    static const long ID_SLIDER_MorphDuration;
    static const long IDD_TEXTCTRL_MorphDuration;
    static const long ID_BITMAPBUTTON_SLIDER_MorphDuration;
    static const long ID_STATICTEXT124;
    static const long ID_SLIDER_MorphAccel;
    static const long IDD_TEXTCTRL_MorphAccel;
    static const long ID_BITMAPBUTTON_SLIDER_MorphAccel;
    static const long ID_CHECKBOX_ShowHeadAtStart;
    static const long ID_BITMAPBUTTON_CHECKBOX_ShowHeadAtStart;
    static const long ID_CHECKBOX_MorphUseHeadStartColor;
    static const long ID_BITMAPBUTTON_MorphUseHeadStartColor;
    static const long ID_CHECKBOX_MorphUseHeadEndColor;
    static const long ID_BITMAPBUTTON_MorphUseHeadEndColor;
    static const long ID_PANEL30;
    static const long ID_NOTEBOOK_Morph;
    static const long ID_PANEL_Morph;
    static const long ID_STATICTEXT1;
    static const long ID_CHOICE_Piano_Style;
    static const long ID_BITMAPBUTTON_SLIDER_Piano_Style;
    static const long ID_STATICTEXT_Piano_NumKeys;
    static const long ID_SLIDER_Piano_NumKeys;
    static const long ID_BITMAPBUTTON_Piano_NumKeys;
    static const long ID_STATICTEXT_Piano_NumRows;
    static const long ID_SLIDER_Piano_KeyWidth;
    static const long ID_BITMAPBUTTON_Piano_NumRows;
    static const long ID_STATICTEXT20;
    static const long ID_CHOICE_PianoPlacement;
    static const long ID_BITMAPBUTTON_Piano_KeyPlacement;
    static const long ID_BUTTON_Piano_CueFilename;
    static const long ID_BITMAPBUTTON_Piano_Filename;
    static const long ID_STATICTEXT14;
    static const long ID_TEXTCTRL_Piano_CueFilename;
    static const long ID_PANEL9;
    static const long ID_BUTTON1;
    static const long ID_BITMAPBUTTON_Piano_MapFilename;
    static const long ID_STATICTEXT13;
    static const long ID_TEXTCTRL_Piano_MapFilename;
    static const long ID_PANEL11;
    static const long ID_BUTTON2;
    static const long ID_BITMAPBUTTON_Piano_ShapeFilename;
    static const long ID_CHECKBOX1;
    static const long ID_BITMAPBUTTON_Piano_Clipping;
    static const long ID_TEXTCTRL_Piano_ShapeFilename;
    static const long ID_PANEL13;
    static const long ID_NOTEBOOK2;
    static const long ID_PANEL39;
    static const long ID_FILEPICKER_Pictures_Filename;
    static const long ID_BITMAPBUTTON_BUTTON_PICTURES_FILENAME;
    static const long ID_STATICTEXT46;
    static const long ID_CHOICE_Pictures_Direction;
    static const long ID_BITMAPBUTTON_CHOICE_Pictures_Direction;
    static const long ID_SLIDER_Pictures_GifSpeed;
    static const long IDD_TEXTCTRL_Pictures_GifSpeed;
    static const long ID_BITMAPBUTTON_SLIDER_Pictures_GifSpeed;
    static const long ID_STATICTEXT4;
    static const long ID_CHECKBOX_MovieIs20FPS;
    static const long ID_BITMAPBUTTON_CHECKBOX_MovieIs20FPS;
    static const long ID_CHECKBOX_Pictures_PixelOffsets;
    static const long ID_SLIDER_PicturesXC;
    static const long ID_CHECKBOX_Pictures_WrapX;
    static const long IDD_TEXTCTRL_PicturesXC;
    static const long IDD_TEXTCTRL_PicturesYC;
    static const long ID_SLIDER_PicturesYC;
    static const long ID_PANEL43;
    static const long ID_SLIDER_PicturesEndXC;
    static const long IDD_TEXTCTRL_PicturesEndXC;
    static const long IDD_TEXTCTRL_PicturesEndYC;
    static const long ID_SLIDER_PicturesEndYC;
    static const long ID_PANEL45;
    static const long IDD_NOTEBOOK_Pictures_Positions;
    static const long ID_PANEL20;
    static const long ID_STATICTEXT65;
    static const long ID_SLIDER_Pinwheel_Arms;
    static const long ID_BITMAPBUTTON11;
    static const long ID_STATICTEXT98;
    static const long ID_SLIDER_Pinwheel_ArmSize;
    static const long ID_BITMAPBUTTON16;
    static const long ID_STATICTEXT76;
    static const long ID_SLIDER_Pinwheel_Twist;
    static const long ID_BITMAPBUTTON12;
    static const long ID_STATICTEXT77;
    static const long ID_SLIDER_Pinwheel_Thickness;
    static const long ID_BITMAPBUTTON18;
    static const long ID_STATICTEXT78;
    static const long ID_CHECKBOX_Pinwheel_Rotation;
    static const long ID_BITMAPBUTTON19;
    static const long ID_STATICTEXT82;
    static const long ID_CHOICE_Pinwheel_3D;
    static const long ID_BITMAPBUTTON_Pinwheel3D;
    static const long ID_STATICTEXT85;
    static const long ID_SLIDER_PinwheelXC;
    static const long ID_STATICTEXT83;
    static const long ID_SLIDER_PinwheelYC;
    static const long ID_PANEL_Pinwheel;
    static const long ID_STATICTEXT71;
    static const long ID_CHOICE_Ripple_Object_To_Draw;
    static const long ID_BITMAPBUTTON20;
    static const long ID_STATICTEXT72;
    static const long ID_CHOICE_Ripple_Movement;
    static const long ID_BITMAPBUTTON13;
    static const long ID_STATICTEXT74;
    static const long ID_SLIDER_Ripple_Thickness;
    static const long ID_BITMAPBUTTON14;
    static const long ID_CHECKBOX_Ripple3D;
    static const long ID_BITMAPBUTTON17;
    static const long ID_PANELRipple;
    static const long ID_STATICTEXT68;
    static const long ID_SLIDER_Shimmer_Duty_Factor;
    static const long ID_BITMAPBUTTON_DutyFactor;
    static const long ID_STATICTEXT69;
    static const long ID_CHECKBOX_Shimmer_Use_All_Colors;
    static const long ID_BITMAPBUTTON_ShimmerUseAllColors;
    static const long ID_STATICTEXT70;
    static const long ID_CHECKBOX_Shimmer_Blink_Timing;
    static const long ID_BITMAPBUTTON_Shimmer_Blink_Timing;
    static const long ID_STATICTEXT67;
    static const long ID_SLIDER_Shimmer_Blinks_Per_Row;
    static const long ID_BITMAPBUTTON_BlinksPerRow;
    static const long ID_PANELShimmer;
    static const long ID_SLIDER_Shockwave_CenterX;
    static const long IDD_TEXTCTRL_Shockwave_CenterX;
    static const long ID_BITMAPBUTTON_SLIDER_Shockwave_CenterX;
    static const long ID_STATICTEXT151;
    static const long ID_SLIDER_Shockwave_CenterY;
    static const long IDD_TEXTCTRL_Shockwave_CenterY;
    static const long ID_BITMAPBUTTON_SLIDER_Shockwave_CenterY;
    static const long ID_STATICTEXT152;
    static const long ID_SLIDER_Shockwave_Start_Radius;
    static const long IDD_TEXTCTRL_Shockwave_Start_Radius;
    static const long ID_BITMAPBUTTON_SLIDER_Shockwave_Start_Radius;
    static const long ID_STATICTEXT154;
    static const long ID_SLIDER_Shockwave_End_Radius;
    static const long IDD_TEXTCTRL_Shockwave_End_Radius;
    static const long ID_BITMAPBUTTON_SLIDER_Shockwave_End_Radius;
    static const long ID_STATICTEXT153;
    static const long ID_SLIDER_Shockwave_Start_Width;
    static const long IDD_TEXTCTRL_Shockwave_Start_Width;
    static const long ID_BITMAPBUTTON_SLIDER_Shockwave_Start_Width;
    static const long ID_STATICTEXT155;
    static const long ID_SLIDER_Shockwave_End_Width;
    static const long IDD_TEXTCTRL_Shockwave_End_Width;
    static const long ID_BITMAPBUTTON_SLIDER_Shockwave_End_Width;
    static const long ID_PANEL40;
    static const long ID_STATICTEXT162;
    static const long ID_SLIDER_Shockwave_Accel;
    static const long IDD_TEXTCTRL_Shockwave_Accel;
    static const long ID_BITMAPBUTTON_SLIDER_Shockwave_Accel;
    static const long ID_CHECKBOX_Shockwave_Blend_Edges;
    static const long ID_PANEL44;
    static const long ID_NOTEBOOK_Shockwave;
    static const long ID_SCROLLEDWINDOW_SHOCKWAVE;
    static const long ID_STATICTEXT63;
    static const long ID_CHOICE_SingleStrand_Colors;
    static const long ID_BITMAPBUTTON_SingleStrand_Colors;
    static const long ID_STATICTEXT62;
    static const long ID_SLIDER_Number_Chases;
    static const long ID_BITMAPBUTTON_Number_Chases;
    static const long ID_STATICTEXT8;
    static const long ID_SLIDER_Color_Mix1;
    static const long ID_BITMAPBUTTON_SLIDER_Color_Mix1;
    static const long ID_STATICTEXT9;
    static const long ID_SLIDER_Chase_Spacing1;
    static const long ID_BITMAPBUTTON_SLIDER_Chase_Spacing1;
    static const long ID_STATICTEXT10;
    static const long ID_CHOICE_Chase_Type1;
    static const long ID_BITMAPBUTTON_CHOICE_Chase_Type1;
    static const long ID_STATICTEXT11;
    static const long ID_CHECKBOX_Chase_3dFade1;
    static const long ID_BITMAPBUTTON_CHECKBOX_Chase_3dFade1;
    static const long ID_STATICTEXT12;
    static const long ID_CHECKBOX_Chase_Group_All;
    static const long ID_BITMAPBUTTON_Chase_Group_All;
    static const long ID_PANEL3;
    static const long ID_STATICTEXT106;
    static const long ID_SLIDER_Skips_BandSize;
    static const long IDD_TEXTCTRL_Skips_BandSize;
    static const long ID_BITMAPBUTTON44;
    static const long ID_STATICTEXT107;
    static const long ID_SLIDER_Skips_SkipSize;
    static const long IDD_TEXTCTRL_Skips_SkipSize;
    static const long ID_BITMAPBUTTON46;
    static const long ID_STATICTEXT110;
    static const long ID_SLIDER_Skips_StartPos;
    static const long IDD_TEXTCTRL_Skips_StartPos;
    static const long ID_BITMAPBUTTON47;
    static const long ID_STATICTEXT111;
    static const long ID_CHOICE_Skips_Direction;
    static const long ID_BITMAPBUTTON48;
    static const long ID_PANEL21;
    static const long ID_NOTEBOOK_SSEFFECT_TYPE;
    static const long ID_PANEL2;
    static const long ID_STATICTEXT80;
    static const long ID_SLIDER_Snowflakes_Count;
    static const long ID_BITMAPBUTTON_SLIDER_Snowflakes_Count;
    static const long ID_STATICTEXT81;
    static const long ID_SLIDER_Snowflakes_Type;
    static const long ID_BITMAPBUTTON_SLIDER_Snowflakes_Type;
    static const long ID_PANEL22;
    static const long ID_STATICTEXT45;
    static const long ID_SLIDER_Snowstorm_Count;
    static const long ID_BITMAPBUTTON_SLIDER_Snowstorm_Count;
    static const long ID_STATICTEXT51;
    static const long ID_SLIDER_Snowstorm_Length;
    static const long ID_BITMAPBUTTON_SLIDER_Snowstorm_Length;
    static const long ID_PANEL24;
    static const long ID_STATICTEXT38;
    static const long ID_SLIDER_Spirals_Count;
    static const long ID_BITMAPBUTTON_SLIDER_Spirals_Count;
    static const long ID_STATICTEXT40;
    static const long ID_SLIDER_Spirals_Rotation;
    static const long ID_BITMAPBUTTON_SLIDER_Spirals_Rotation;
    static const long ID_STATICTEXT42;
    static const long ID_SLIDER_Spirals_Thickness;
    static const long ID_BITMAPBUTTON_SLIDER_Spirals_Thickness;
    static const long ID_STATICTEXT44;
    static const long ID_SLIDER_Spirals_Direction;
    static const long ID_BITMAPBUTTON_SLIDER_Spirals_Direction;
    static const long ID_CHECKBOX_Spirals_Blend;
    static const long ID_BITMAPBUTTON_CHECKBOX_Spirals_Blend;
    static const long ID_CHECKBOX_Spirals_3D;
    static const long ID_BITMAPBUTTON_CHECKBOX_Spirals_3D;
    static const long ID_CHECKBOX_Spirals_Grow;
    static const long ID_BITMAPBUTTON_CHECKBOX_Spirals_Grow;
    static const long ID_CHECKBOX_Spirals_Shrink;
    static const long ID_BITMAPBUTTON_CHECKBOX_Spirals_Shrink;
    static const long ID_PANEL26;
    static const long ID_STATICTEXT88;
    static const long ID_SLIDER_Spirograph_R;
    static const long ID_BITMAPBUTTON_SLIDER_Spirograph_R;
    static const long ID_STATICTEXT89;
    static const long ID_SLIDER_Spirograph_r;
    static const long ID_BITMAPBUTTON_SLIDER_Spirograph_r;
    static const long ID_STATICTEXT90;
    static const long ID_SLIDER_Spirograph_d;
    static const long ID_BITMAPBUTTON_SLIDER_Spirograph_d;
    static const long ID_STATICTEXT93;
    static const long ID_CHECKBOX_Spirograph_Animate;
    static const long ID_BITMAPBUTTON_CHECKBOX_Spirograph_Animate;
    static const long ID_STATICTEXT91;
    static const long ID_PANEL35;
    static const long ID_STATICTEXT112;
    static const long ID_SLIDER_Number_Strobes;
    static const long ID_BITMAPBUTTON49;
    static const long ID_STATICTEXT113;
    static const long ID_SLIDER_Strobe_Duration;
    static const long ID_BITMAPBUTTON51;
    static const long ID_STATICTEXT114;
    static const long ID_SLIDER_Strobe_Type;
    static const long ID_BITMAPBUTTON50;
    static const long ID_PANEL23;
    static const long ID_STATICTEXT53;
    static const long ID_TEXTCTRL_Text_Line1;
    static const long ID_STATICTEXT54;
    static const long ID_TEXTCTRL_Text_Line2;
    static const long ID_STATICTEXT22;
    static const long ID_TEXTCTRL_Text_Line3;
    static const long ID_STATICTEXT23;
    static const long ID_TEXTCTRL_Text_Line4;
    static const long ID_FONTPICKER_Text_Font1;
    static const long ID_BITMAPBUTTON_FONTPICKER_Text_Font1;
    static const long ID_STATICTEXT79;
    static const long ID_CHOICE_Text_Dir1;
    static const long ID_BITMAPBUTTON_CHOICE_Text_Dir1;
    static const long ID_CHECKBOX_TextToCenter1;
    static const long ID_BITMAPBUTTON_TextToCenter1;
    static const long ID_STATICTEXT108;
    static const long ID_CHOICE_Text_Effect1;
    static const long ID_BITMAPBUTTON_CHOICE_Text_Effect1;
    static const long ID_STATICTEXT99;
    static const long ID_CHOICE_Text_Count1;
    static const long ID_BITMAPBUTTON_CHOICE_Text_Count1;
    static const long ID_STATICTEXT101;
    static const long ID_SLIDER_Text_Position1;
    static const long IDD_TEXTCTRL_Text_Position1;
    static const long ID_BITMAPBUTTON_SLIDER_Text_Position1;
    static const long ID_PANEL_Text1;
    static const long ID_FONTPICKER_Text_Font2;
    static const long ID_BITMAPBUTTON_FONTPICKER_Text_Font2;
    static const long ID_STATICTEXT57;
    static const long ID_CHOICE_Text_Dir2;
    static const long ID_BITMAPBUTTON_CHOICE_Text_Dir2;
    static const long ID_CHECKBOX_TextToCenter2;
    static const long ID_BITMAPBUTTON_Text2Center2;
    static const long ID_STATICTEXT109;
    static const long ID_CHOICE_Text_Effect2;
    static const long ID_BITMAPBUTTON_CHOICE_Text_Effect2;
    static const long ID_STATICTEXT104;
    static const long ID_CHOICE_Text_Count2;
    static const long ID_BITMAPBUTTON_CHOICE_Text_Count2;
    static const long ID_STATICTEXT103;
    static const long ID_SLIDER_Text_Position2;
    static const long IDD_TEXTCTRL_Text_Position2;
    static const long ID_BITMAPBUTTON_SLIDER_Text_Position2;
    static const long ID_PANEL_Text2;
    static const long ID_FONTPICKER_Text_Font3;
    static const long ID_BITMAPBUTTON_FONTPICKER_Text_Font3;
    static const long ID_STATICTEXT16;
    static const long ID_CHOICE_Text_Dir3;
    static const long ID_BITMAPBUTTON_CHOICE_Text_Dir3;
    static const long ID_CHECKBOX_TextToCenter3;
    static const long ID_BITMAPBUTTON_TextToCenter3;
    static const long ID_STATICTEXT17;
    static const long ID_CHOICE_Text_Effect3;
    static const long ID_BITMAPBUTTON_CHOICE_Text_Effect3;
    static const long ID_STATICTEXT18;
    static const long ID_CHOICE_Text_Count3;
    static const long ID_BITMAPBUTTON_CHOICE_Text_Count3;
    static const long ID_STATICTEXT19;
    static const long ID_SLIDER_Text_Position3;
    static const long IDD_TEXTCTRL_Text_Position3;
    static const long ID_BITMAPBUTTON_SLIDER_Text_Position3;
    static const long ID_PANEL_Text3;
    static const long ID_FONTPICKER_Text_Font4;
    static const long ID_BITMAPBUTTON_FONTPICKER_Text_Font4;
    static const long ID_STATICTEXT24;
    static const long ID_CHOICE_Text_Dir4;
    static const long ID_BITMAPBUTTON_CHOICE_Text_Dir4;
    static const long ID_CHECKBOX_TextToCenter4;
    static const long ID_BITMAPBUTTON_TextToCenter4;
    static const long ID_STATICTEXT29;
    static const long ID_CHOICE_Text_Effect4;
    static const long ID_BITMAPBUTTON_CHOICE_Text_Effect4;
    static const long ID_STATICTEXT47;
    static const long ID_CHOICE_Text_Count4;
    static const long ID_BITMAPBUTTON_CHOICE_Text_Count4;
    static const long ID_STATICTEXT48;
    static const long ID_SLIDER_Text_Position4;
    static const long IDD_TEXTCTRL_Text_Position4;
    static const long ID_BITMAPBUTTON_SLIDER_Text_Position4;
    static const long ID_PANEL_Text4;
    static const long IDD_NOTEBOOK_Text;
    static const long ID_PANEL7;
    static const long ID_BITMAPBUTTON40;
    static const long ID_STATICTEXT87;
    static const long ID_SLIDER_Tree_Branches;
    static const long ID_BITMAPBUTTON_SLIDER_Tree_Branches;
    static const long ID_PANEL34;
    static const long ID_STATICTEXT86;
    static const long ID_SLIDER_Twinkle_Count;
    static const long ID_BITMAPBUTTON_SLIDER_Twinkle_Count;
    static const long ID_STATICTEXT105;
    static const long ID_SLIDER_Twinkle_Steps;
    static const long ID_BITMAPBUTTON_SLIDER_Twinkle_Steps;
    static const long ID_CHECKBOX_Twinkle_Strobe;
    static const long ID_BITMAPBUTTON_CHECKBOX_Twinkle_Strobe;
    static const long ID_PANEL33;
    static const long ID_STATICTEXT49;
    static const long ID_CHOICE_Wave_Type;
    static const long ID_BITMAPBUTTON2;
    static const long ID_STATICTEXT50;
    static const long ID_CHOICE_Fill_Colors;
    static const long ID_BITMAPBUTTON3;
    static const long ID_STATICTEXT52;
    static const long ID_CHECKBOX_Mirror_Wave;
    static const long ID_BITMAPBUTTON4;
    static const long ID_STATICTEXT55;
    static const long ID_SLIDER_Number_Waves;
    static const long ID_BITMAPBUTTON5;
    static const long ID_STATICTEXT56;
    static const long ID_SLIDER_Thickness_Percentage;
    static const long ID_BITMAPBUTTON6;
    static const long ID_STATICTEXT58;
    static const long ID_SLIDER_Wave_Height;
    static const long ID_BITMAPBUTTON7;
    static const long ID_STATICTEXT59;
    static const long ID_CHOICE_Wave_Direction;
    static const long ID_BITMAPBUTTON8;
    static const long ID_PANEL15;
    static const long ID_CHOICEBOOK1;
    static const long ID_BITMAPBUTTON_CHOICEBOOK1;
    static const long ID_BITMAPBUTTON87;
    static const long ID_BITMAPBUTTON1;
    static const long ID_BITMAPBUTTON88;
    //*)



private:
    void enableControlsByName(const wxString &name, bool enable);

    //(*Handlers(EffectsPanel)
    void OnButton_pgo_filenameClick(wxCommandEvent& event);
    //    void OnButton_papagayo_output_sequenceClick(wxCommandEvent& event);
    void OnButton_Glediator_FilenameClick(wxCommandEvent& event);
    void OnCheckBox_PaletteClick(wxCommandEvent& event);
    void OnButton_PaletteNumberClick(wxCommandEvent& event);
    void OnPiano_StyleSelect(wxCommandEvent& event);
    void OnSlider_Piano_NumKeysCmdScroll(wxScrollEvent& event);
    void OnTextCtrl_Piano_FilenameText(wxCommandEvent& event);
    void OnButton_Piano_FilenameClick(wxCommandEvent& event);
    void OnSlider_Piano_KeyWidthCmdScroll(wxScrollEvent& event);
    void OnButton_Piano_CueFilenameClick(wxCommandEvent& event);
    void OnButton_Piano_MapFilenameClick(wxCommandEvent& event);
    void OnButton_Piano_ShapeFilenameClick(wxCommandEvent& event);
    void OnTextCtrl_Piano_CueFilenameText(wxCommandEvent& event);
    void OnTextCtrl_Piano_MapFilenameText(wxCommandEvent& event);
    void OnTextCtrl_Piano_ShapeFilenameText(wxCommandEvent& event);
    void OnSlider_Piano_NumRowsCmdScroll(wxScrollEvent& event);
    void OnPaint(wxPaintEvent& event);
    void OnTextCtrl2Text(wxCommandEvent& event);
    void OnTextCtrl1Text(wxCommandEvent& event);
    void OnTextCtrl_Pinwheel_ArmsText(wxCommandEvent& event);
    void OnTextCtrl_Pinwheel_TwistText(wxCommandEvent& event);
    void OnTextCtrl_Pinwheel_ThicknessText(wxCommandEvent& event);
    void OnSlider_Pinwheel_ArmsCmdScroll(wxScrollEvent& event);
    void OnTextCtrl_Eff_On_StartText(wxCommandEvent& event);
    void OnTextCtrl_Eff_On_EndText(wxCommandEvent& event);
    void OnResize(wxSizeEvent& event);
    void OnPaint1(wxPaintEvent& event);
    void OnCheckBox_Morph_Start_LinkClick(wxCommandEvent& event);
    void OnCheckBox_Morph_End_LinkClick(wxCommandEvent& event);
    void OnCheckBox_Galaxy_Start_Radius_x10Click(wxCommandEvent& event);
    void OnCheckBox_Galaxy_Start_Width_x10Click(wxCommandEvent& event);
    void OnCheckBox_Galaxy_End_Radius_x10Click(wxCommandEvent& event);
    void OnCheckBox_Galaxy_End_Width_x10Click(wxCommandEvent& event);
    void OnCheckBox_Galaxy_Revs_x2Click(wxCommandEvent& event);
    void OnLockButtonClick(wxCommandEvent& event);
    void UpdateLinkedSlider(wxCommandEvent& event);
    void UpdateLinkedTextCtrl(wxScrollEvent& event);
    void UpdateLinkedSlider360(wxCommandEvent& event);
    void UpdateLinkedTextCtrl360(wxScrollEvent& event);
    void OnChoicePicturesDirectionSelect(wxCommandEvent& event);
    void EffectSelected(wxChoicebookEvent& event);
    void OnColorWashEntireModelClicked(wxCommandEvent& event);
    //*)

    int GetRandomSliderValue(wxSlider* slider);
    wxString GetAttrPrefix();
    wxString GetRandomEffectStringFromWindow(wxWindow *ParentWin, const wxString &prefix);

//add lock/unlock/random state flags -DJ
//these could be used to make fields read-only, but initially they are just used for partially random effects
//#include <unordered_map>
    typedef enum { Normal, Locked, Random } EditState;
    std::unordered_map<std::string, EditState> buttonState;
    bool isRandom_(wxControl* ctl, const char*debug);
#define isRandom(ctl)  isRandom_(ctl, #ctl) //(buttonState[std::string(ctl->GetName())] == Random)
    void setlock(wxButton* button); //, EditState& islocked);
//friend class xLightsFrame; //debug only
    wxCheckBox* GetPaletteCheckbox(int idx);
    wxButton* GetPaletteButton(int idx);
    wxColourData colorData;

    DECLARE_EVENT_TABLE()
public:
    bool isRandom_(void);

    bool WantOverlayBkg(void); //selectable clear canvas before render -DJ
};

#endif
