#ifndef EFFECTSPANEL_H
#define EFFECTSPANEL_H

//(*Headers(EffectsPanel)
#include <wx/notebook.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/checkbox.h>
#include <wx/slider.h>
#include <wx/panel.h>
#include <wx/choice.h>
#include <wx/bmpbuttn.h>
#include <wx/button.h>
#include <wx/choicebk.h>
//*)

#include <wx/filedlg.h>
#include <wx/fontdlg.h>
#include <unordered_map> //-DJ
#include <wx/colordlg.h>

class EffectsPanel: public wxPanel
{
public:

    EffectsPanel(wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL, const wxString &name=wxPanelNameStr);
    virtual ~EffectsPanel();
    bool PaletteChanged;
    bool EffectChanged;
    void SetDefaultPalette();
    wxString* CurrentDir;
    wxColour GetPaletteColor(int idx);
    void SetPaletteColor(int idx, const wxColour* c);
    wxString GetEffectString();
    wxString GetRandomEffectString(int effidx);
    static const int PALETTE_SIZE = 6;

    //(*Declarations(EffectsPanel)
    wxStaticText* StaticText6;
    wxBitmapButton* BitmapButton_RandomMotion;
    wxBitmapButton* BitmapButton_Wave_FillColors;
    wxBitmapButton* BitmapButton_TwinkleSteps;
    wxBitmapButton* BitmapButton_TextFont2;
    wxStaticText* StaticText19;
    wxPanel* Panel1_Butterfly;
    wxBitmapButton* BitmapButton_Piano_Clipping;
    wxBitmapButton* BitmapButton_SnowflakesType;
    wxBitmapButton* BitmapButton_GarlandsSpacing;
    wxChoice* Choice_Text_Dir1;
    wxSlider* Slider_Spirals_Direction;
    wxBitmapButton* BitmapButton_OverlayBkg;
    wxButton* Button_Pictures_Filename;
    wxBitmapButton* BitmapButton_TextCount4;
    wxPanel* Panel1_Fireworks;
    wxSlider* Slider_Number_Chases;
    wxNotebook* Notebook1;
    wxBitmapButton* BitmapButton_SpiralsGrow;
    wxChoice* Choice_SingleStrand_Colors;
    wxButton* Button_Palette3;
    wxBitmapButton* BitmapButton_TextLine1;
    wxBitmapButton* BitmapButton_Piano_MapFilename;
    wxStaticText* StaticText4;
    wxChoicebook* Choicebook1;
    wxStaticText* StaticText38;
    wxTextCtrl* TextCtrl_Text_Font4;
    wxPanel* Panel1_Life;
    wxStaticText* StaticText86;
    wxStaticText* StaticText42;
    wxBitmapButton* BitmapButton_PicturesSpeed;
    wxChoice* Choice_Piano_KeyPlacement;
    wxBitmapButton* BitmapButton_TextPosition4;
    wxButton* Button_Piano_CueFilename;
    wxBitmapButton* BitmapButton_TextCount1;
    wxPanel* Panel_Text2;
    wxChoice* Choice_Curtain_Edge;
    wxSlider* Slider_Spirograph_d;
    wxChoice* Choice_Wave_Type;
    wxStaticText* StaticText91;
    wxNotebook* Notebook_Text1;
    wxCheckBox* CheckBox_Circles_Radial_3D;
    wxCheckBox* CheckBox_Palette2;
    wxSlider* Slider_Fireworks_Number_Explosions;
    wxBitmapButton* BitmapButton_TextLine4;
    wxBitmapButton* BitmapButton_CirclesPlasma;
    wxBitmapButton* BitmapButton_FadeIn;
    wxPanel* Panel_Text1;
    wxBitmapButton* BitmapButton_Wave_Thickness;
    wxBitmapButton* BitmapButton_TextToCenter2;
    wxStaticText* StaticText45;
    wxPanel* Panel3;
    wxBitmapButton* BitmapButton_Palette6;
    wxStaticText* StaticText11;
    wxBitmapButton* BitmapButton_Glediator_Filename;
    wxStaticText* StaticText18;
    wxStaticText* StaticText30;
    wxCheckBox* CheckBox_FitToTime;
    wxButton* Button_Piano_ShapeFilename;
    wxPanel* Panel1;
    wxPanel* Panel_Text4;
    wxBitmapButton* BitmapButton_LifeCount;
    wxSlider* Slider_Twinkle_Steps;
    wxStaticText* StaticText103;
    wxCheckBox* CheckBox_Chase_3dFade1;
    wxBitmapButton* BitmapButton_CurtainSwag;
    wxButton* Button_Text_Font1;
    wxPanel* Panel1_Fire;
    wxStaticText* StaticText48;
    wxCheckBox* CheckBox_TextToCenter2;
    wxStaticText* StaticText37;
    wxCheckBox* CheckBox_Spirlas_Shrink;
    wxChoice* Choice_Butterfly_Colors;
    wxTextCtrl* TextCtrl_Text_Font1;
    wxBitmapButton* BitmapButton_MeteorsLength;
    wxStaticText* StaticText1;
    wxSlider* Slider_Circles_Size;
    wxBitmapButton* BitmapButton_TextToCenter4;
    wxStaticText* StaticText22;
    wxCheckBox* CheckBox_Circles_Radial;
    wxBitmapButton* BitmapButton_ButterflyChunks;
    wxBitmapButton* BitmapButton_TextPosition3;
    wxStaticText* StaticText87;
    wxCheckBox* CheckBox_Circles_Bounce;
    wxTextCtrl* TextCtrl_Text_Line3;
    wxStaticText* StaticText92;
    wxTextCtrl* TextCtrl_Speed;
    wxStaticText* StaticText52;
    wxSlider* Slider_Chase_Spacing1;
    wxStaticText* StaticText96;
    wxSlider* Slider_Snowstorm_Length;
    wxTextCtrl* TextCtrl_Text_Line1;
    wxBitmapButton* BitmapButton_SingleStrand_Colors;
    wxStaticText* StaticText10;
    wxChoice* Choice_Curtain_Effect;
    wxBitmapButton* BitmapButton_Chase_Group_All;
    wxBitmapButton* BitmapButton_TextPosition1;
    wxChoice* Choice_Text_Effect4;
    wxBitmapButton* BitmapButton_LifeSpeed;
    wxSlider* Slider_Garlands_Spacing;
    wxBitmapButton* BitmapButton_CirclesCount;
    wxCheckBox* CheckBox_Mirror_Wave;
    wxBitmapButton* BitmapButton_SpiralsCount;
    wxStaticText* StaticText24;
    wxStaticText* StaticText104;
    wxSlider* Slider_Snowflakes_Count;
    wxBitmapButton* BitmapButton_Wave_MirrorWave;
    wxStaticText* StaticText137;
    wxChoice* Choice_Text_Dir3;
    wxSlider* Slider_Spirals_Thickness;
    wxBitmapButton* BitmapButton_TextToCenter1;
    wxSlider* Slider_Number_Waves;
    wxStaticText* StaticText13;
    wxSlider* Slider_Meteors_Length;
    wxBitmapButton* BitmapButton_Piano_KeyPlacement;
    wxStaticText* StaticText_Piano_NumRows;
    wxButton* Button_Palette4;
    wxBitmapButton* BitmapButton_CirclesRadial;
    wxBitmapButton* BitmapButton_FireworksNumberExplosions;
    wxStaticText* StaticText60;
    wxChoice* Choice_Wave_Direction;
    wxBitmapButton* BitmapButton_MeteorsSwirlIntensity;
    wxStaticText* StaticText49;
    wxSlider* Slider_Snowflakes_Type;
    wxStaticText* StaticText64;
    wxBitmapButton* BitmapButton_Speed;
    wxBitmapButton* BitmapButton_Chase_Spacing1;
    wxSlider* Slider_Fireworks_Count;
    wxBitmapButton* BitmapButton_CurtainEdge;
    wxTextCtrl* TextCtrl_Fadeout;
    wxStaticText* StaticText32;
    wxPanel* Panel1_SingleStrand;
    wxStaticText* StaticText14;
    wxStaticText* StaticText36;
    wxStaticText* StaticText134;
    wxPanel* Panel5;
    wxStaticText* StaticText56;
    wxStaticText* StaticText8;
    wxButton* Button_Text_Font2;
    wxStaticText* StaticText25;
    wxStaticText* StaticText15_layout_kludge_1;
    wxBitmapButton* BitmapButton_CirclesCollide;
    wxStaticText* StaticText28;
    wxStaticText* StaticText89;
    wxChoice* Choice_Meteors_Type;
    wxStaticText* StaticText23;
    wxCheckBox* CheckBox_Circles_Plasma;
    wxStaticText* StaticText130;
    wxStaticText* StaticText55;
    wxCheckBox* CheckBox_Spirals_3D;
    wxBitmapButton* BitmapButton_ColorWashHFade;
    wxSlider* Slider_Fireworks_Velocity;
    wxStaticText* StaticText15;
    wxSlider* Slider_Spirals_Count;
    wxPanel* Panel1_Curtain;
    wxSlider* Slider_Piano_NumRows;
    wxCheckBox* CheckBox_Bars_3D;
    wxChoice* Choice_Text_Dir4;
    wxBitmapButton* BitmapButton_TextToCenter3;
    wxCheckBox* CheckBox_Bars_Highlight;
    wxBitmapButton* BitmapButton8;
    wxSlider* Slider_Butterfly_Skip;
    wxBitmapButton* BitmapButton_SnowstormCount;
    wxTextCtrl* TextCtrl_Text_Font3;
    wxBitmapButton* BitmapButton_SpiralsShrink;
    wxSlider* Slider_Spirograph_R;
    wxStaticText* StaticText39;
    wxStaticText* StaticText78;
    wxBitmapButton* BitmapButton_LayerEffect;
    wxPanel* Panel1_ColorWash;
    wxBitmapButton* BitmapButton_Piano_NumRows;
    wxBitmapButton* BitmapButton_ButterflySkip;
    wxBitmapButton* BitmapButton_TextCount2;
    wxStaticText* StaticText108;
    wxBitmapButton* BitmapButton_FireHeight;
    wxPanel* Panel1_Bars;
    wxCheckBox* CheckBox_TextToCenter1;
    wxPanel* Panel1_Twinkle;
    wxBitmapButton* BitmapButton_FireworksCount;
    wxBitmapButton* BitmapButton_SpiralsDirection;
    wxStaticText* StaticText27;
    wxBitmapButton* BitmapButton_PicturesFilename;
    wxSlider* Slider_Life_Count;
    wxChoice* Choice_Text_Effect3;
    wxStaticText* StaticText35;
    wxSlider* Slider_ColorWash_Count;
    wxStaticText* StaticText85;
    wxNotebook* Notebook2;
    wxButton* Button_Palette6;
    wxBitmapButton* BitmapButton_GarlandsType;
    wxPanel* Panel1_Garlands;
    wxTextCtrl* TextCtrl_Text_Font2;
    wxBitmapButton* BitmapButton_random;
    wxSlider* Slider_Bars_BarCount;
    wxBitmapButton* BitmapButton_TextFont1;
    wxTextCtrl* TextCtrl_Piano_ShapeFilename;
    wxStaticText* StaticText14_layout_kludge2;
    wxPanel* Panel1_Faces;
    wxCheckBox* CheckBox_Fire_GrowFire;
    wxBitmapButton* BitmapButton_TextEffect3;
    wxTextCtrl* TextCtrl_Text_Line2;
    wxSlider* Slider_Fire_HueShift;
    wxBitmapButton* BitmapButton_Number_Chases;
    wxBitmapButton* BitmapButton_TextDir2;
    wxPanel* Panel4;
    wxStaticText* StaticText53;
    wxChoice* Choice_Text_Dir2;
    wxBitmapButton* BitmapButton_ButterflyStyle;
    wxChoice* Choice_Text_Count4;
    wxSlider* Slider_Text_Position4;
    wxBitmapButton* BitmapButton_TextEffect4;
    wxCheckBox* CheckBox_Chase_Group_All;
    wxStaticText* StaticText40;
    wxBitmapButton* BitmapButton_TwinkleCount;
    wxChoice* Choice_Meteors_Effect;
    wxStaticText* StaticText21;
    wxSlider* Slider_Wave_Height;
    wxSlider* Slider_Text_Position3;
    wxBitmapButton* BitmapButton_Highlight;
    wxSlider* Slider_Text_Position1;
    wxSlider* Slider_Garlands_Type;
    wxBitmapButton* BitmapButton_Piano_NumKeys;
    wxCheckBox* CheckBox_OverlayBkg;
    wxBitmapButton* BitmapButton_FireGrow;
    wxStaticText* StaticText57;
    wxStaticText* StaticText90;
    wxStaticText* StaticText93;
    wxBitmapButton* BitmapButton_Color_Mix1;
    wxStaticText* StaticText61;
    wxStaticText* StaticText62;
    wxButton* Button_Text_Font4;
    wxCheckBox* CheckBox_Spirals_Grow;
    wxBitmapButton* BitmapButton_PaletteRep;
    wxCheckBox* CheckBox_Palette3;
    wxBitmapButton* BitmapButton_Palette3;
    wxBitmapButton* BitmapButton_Piano_Style;
    wxBitmapButton* BitmapButton_locked;
    wxButton* Button_Piano_MapFilename;
    wxBitmapButton* BitmapButton_TextPosition2;
    wxCheckBox* CheckBox_Palette6;
    wxBitmapButton* BitmapButton_normal;
    wxTextCtrl* TextCtrl_Text_Line4;
    wxTextCtrl* TextCtrl_Piano_CueFilename;
    wxStaticText* StaticText54;
    wxSlider* Slider_Spirograph_r;
    wxStaticText* StaticText107;
    wxStaticText* StaticText7;
    wxBitmapButton* BitmapButton_CurtainEffect;
    wxBitmapButton* BitmapButton_Chase_Type1;
    wxSlider* Slider_Meteors_Swirl_Intensity;
    wxStaticText* StaticText79;
    wxSlider* Slider_Butterfly_Chunks;
    wxBitmapButton* BitmapButton_Palette5;
    wxTextCtrl* TextCtrl_Fadein;
    wxTextCtrl* TextCtrl_Piano_MapFilename;
    wxSlider* Slider_Twinkle_Count;
    wxBitmapButton* BitmapButton_TextFont4;
    wxSlider* Slider_Color_Mix1;
    wxCheckBox* CheckBox_Palette5;
    wxCheckBox* CheckBox_ColorWash_HFade;
    wxStaticText* StaticText132;
    wxBitmapButton* BitmapButton_Direction;
    wxStaticText* StaticText128;
    wxStaticText* StaticText44;
    wxStaticText* StaticText95;
    wxChoice* Choice_Butterfly_Direction;
    wxBitmapButton* BitmapButton_Wave_Height;
    wxStaticText* StaticText98;
    wxSlider* Slider_Meteors_Count;
    wxBitmapButton* BitmapButton_TwinkleStrobe;
    wxStaticText* StaticText88;
    wxStaticText* StaticText59;
    wxChoice* Choice_Text_Effect2;
    wxBitmapButton* BitmapButton_NumberWaves;
    wxStaticText* StaticText_Piano_NumKeys;
    wxPanel* Panel1_CoroFaces;
    wxBitmapButton* BitmapButton_FitToTime;
    wxPanel* Panel1_Pictures;
    wxTextCtrl* TextCtrl_Glediator_Filename;
    wxBitmapButton* BitmapButton_Palette4;
    wxStaticText* StaticText71;
    wxSlider* Slider_Curtain_Swag;
    wxStaticText* StaticText43;
    wxCheckBox* CheckBox_Circles_Random_m;
    wxBitmapButton* BitmapButton_TextEffect1;
    wxSlider* Slider_Pictures_GifSpeed;
    wxPanel* Panel_Text3;
    wxChoice* Choice_Piano_Style;
    wxBitmapButton* BitmapButton_ColorWashVFade;
    wxChoice* Choice_Faces_Phoneme;
    wxStaticText* StaticText100;
    wxSlider* Slider_Circles_Count;
    wxBitmapButton* BitmapButton_FireworksFade;
    wxSlider* Slider_Tree_Branches;
    wxCheckBox* CheckBox_TextToCenter3;
    wxBitmapButton* BitmapButton_Spirographd;
    wxPanel* Panel1_Meteors;
    wxSlider* Slider_Butterfly_Style;
    wxBitmapButton* BitmapButton_Wave_Direction;
    wxStaticText* StaticText26;
    wxCheckBox* CheckBox_Palette4;
    wxCheckBox* CheckBox_Piano_Clipping;
    wxChoice* Choice_CoroFaces_Eyes;
    wxBitmapButton* BitmapButton_SpiralsThickness;
    wxBitmapButton* BitmapButton_TextDir3;
    wxCheckBox* CheckBox_Spirograph_Animate;
    wxBitmapButton* BitmapButton_TextLine3;
    wxBitmapButton* BitmapButton_ColorWashCount;
    wxBitmapButton* BitmapButton_CirclesRadial3D;
    wxStaticText* StaticText50;
    wxSlider* Slider_Text_Position2;
    wxStaticText* StaticText58;
    wxBitmapButton* BitmapButton_TextDir1;
    wxBitmapButton* BitmapButton_CurtainRepeat;
    wxSlider* Slider_Fire_Height;
    wxStaticText* StaticText17;
    wxBitmapButton* BitmapButton_SnowstormLength;
    wxCheckBox* CheckBox_CoroFaces_Outline;
    wxBitmapButton* BitmapButton_PicturesDirection;
    wxPanel* Panel1_Circles;
    wxButton* Button_Text_Font3;
    wxBitmapButton* BitmapButton_SpiralsBlend;
    wxBitmapButton* BitmapButton_WaveType;
    wxSlider* Slider_Snowstorm_Count;
    wxChoice* Choice_Fill_Colors;
    wxPanel* Panel1_None;
    wxBitmapButton* BitmapButton_Palette1;
    wxChoice* Choice_Text_Count2;
    wxBitmapButton* BitmapButton_ButterflyColors;
    wxBitmapButton* BitmapButton_MeteorsType;
    wxSlider* Slider_Speed;
    wxBitmapButton* BitmapButton_Palette2;
    wxPanel* Panel1_Snowstorm;
    wxPanel* Panel1_Wave;
    wxStaticText* StaticText47;
    wxCheckBox* CheckBox_Circles_Collide;
    wxStaticText* StaticText3;
    wxSlider* Slider_Life_Seed;
    wxBitmapButton* BitmapButton_Piano_CueFilename;
    wxBitmapButton* BitmapButton_CirclesBounce;
    wxChoice* Choice_CoroFaces_Phoneme;
    wxStaticText* StaticText80;
    wxStaticText* StaticText2;
    wxStaticText* StaticText12;
    wxChoice* Choice_Pictures_Direction;
    wxStaticText* StaticText31;
    wxChoice* Choice_Bars_Direction;
    wxChoice* Choice_Text_Effect1;
    wxBitmapButton* BitmapButton_MeteorsEffect;
    wxBitmapButton* BitmapButton_SpirographR;
    wxChoice* Choice_Text_Count3;
    wxButton* Button1;
    wxPanel* Panel1_Piano;
    wxCheckBox* CheckBox_Palette1;
    wxStaticText* StaticText136;
    wxSlider* Slider_Spirals_Rotation;
    wxButton* Button_Palette5;
    wxStaticText* StaticText51;
    wxBitmapButton* BitmapButton_Spirographr;
    wxCheckBox* CheckBox_Spirals_Blend;
    wxStaticText* StaticText33;
    wxPanel* Panel1_Text;
    wxCheckBox* CheckBox_ColorWash_VFade;
    wxBitmapButton* BitmapButton_SnowflakesCount;
    wxTextCtrl* TextCtrl_Pictures_Filename;
    wxBitmapButton* BitmapButton_TextFont3;
    wxBitmapButton* BitmapButton_FadeOut;
    wxSlider* Slider_Thickness_Percentage;
    wxStaticText* StaticText5;
    wxBitmapButton* BitmapButton_TextEffect2;
    wxPanel* Panel1_Tree;
    wxFlexGridSizer* FlexGridSizer_Palette;
    wxBitmapButton* BitmapButton_CirclesSize;
    wxBitmapButton* BitmapButton_MeteorsCount;
    wxCheckBox* CheckBox_Curtain_Repeat;
    wxButton* Button_Palette1;
    wxPanel* Panel1_Glediator;
    wxBitmapButton* BitmapButton_FireWidth;
    wxChoice* Choice_Chase_Type1;
    wxStaticText* StaticText16;
    wxBitmapButton* BitmapButton_TextLine2;
    wxSlider* Slider_Fireworks_Fade;
    wxBitmapButton* BitmapButton_Piano_ShapeFilename;
    wxChoice* Choice_Text_Count1;
    wxBitmapButton* BitmapButton_FireworksVelocity;
    wxSlider* Slider_Piano_NumKeys;
    wxCheckBox* CheckBox_Twinkle_Strobe;
    wxStaticText* StaticText20;
    wxBitmapButton* BitmapButton_Chase_3dFade1;
    wxButton* Button_Palette2;
    wxStaticText* StaticText94;
    wxStaticText* StaticText46;
    wxBitmapButton* BitmapButton_TextDir4;
    wxBitmapButton* BitmapButton_SpiralsRotation;
    wxStaticText* StaticText83;
    wxBitmapButton* BitmapButton_TextCount3;
    wxStaticText* StaticText41;
    wxStaticText* StaticText29;
    wxStaticText* StaticText34;
    wxPanel* Panel1_Spirals;
    wxPanel* Panel1_Snowflakes;
    wxStaticText* StaticText102;
    wxBitmapButton* BitmapButton_3D;
    wxPanel* Panel1_Spirograph;
    wxStaticText* StaticText9;
    wxBitmapButton* BitmapButton_TreeBranches;
    wxBitmapButton* BitmapButton_SpirographAnimate;
    wxBitmapButton* BitmapButton_Spirals3D;
    wxCheckBox* CheckBox_TextToCenter4;
    //*)

protected:

    //(*Identifiers(EffectsPanel)
    static const long ID_PANEL4;
    static const long ID_STATICTEXT25;
    static const long ID_SLIDER_Bars_BarCount;
    static const long ID_BITMAPBUTTON_SLIDER_Bars_BarCount;
    static const long ID_STATICTEXT26;
    static const long ID_CHOICE_Bars_Direction;
    static const long ID_BITMAPBUTTON_CHOICE_Bars_Direction;
    static const long ID_CHECKBOX_Bars_Highlight;
    static const long ID_BITMAPBUTTON_CHECKBOX_Bars_Highlight;
    static const long ID_CHECKBOX_Bars_3D;
    static const long ID_BITMAPBUTTON_CHECKBOX_Bars_3D;
    static const long ID_PANEL8;
    static const long ID_STATICTEXT27;
    static const long ID_CHOICE_Butterfly_Colors;
    static const long ID_BITMAPBUTTON_CHOICE_Butterfly_Color;
    static const long ID_STATICTEXT28;
    static const long ID_SLIDER_Butterfly_Style;
    static const long ID_BITMAPBUTTON_SLIDER_Butterfly_Style;
    static const long ID_STATICTEXT30;
    static const long ID_SLIDER_Butterfly_Chunks;
    static const long ID_BITMAPBUTTON_SLIDER_Butterfly_Chunks;
    static const long ID_STATICTEXT31;
    static const long ID_SLIDER_Butterfly_Skip;
    static const long ID_BITMAPBUTTON_SLIDER_Butterfly_Skip;
    static const long ID_STATICTEXT60;
    static const long ID_CHOICE_Butterfly_Direction;
    static const long ID_BITMAPBUTTON9;
    static const long ID_PANEL10;
    static const long ID_STATICTEXT137;
    static const long ID_SLIDER_Circles_Count;
    static const long ID_BITMAPBUTTON_SLIDER_Circles_Count;
    static const long ID_STATICTEXT138;
    static const long ID_SLIDER_Circles_Size;
    static const long ID_BITMAPBUTTON_SLIDER_Circles_Size;
    static const long ID_CHECKBOX_Circles_Bounce;
    static const long ID_BITMAPBUTTON_CHECKBOX_Circles_Bounce;
    static const long ID_CHECKBOX_Circles_Collide;
    static const long ID_BITMAPBUTTON_CHECKBOX_Circles_Collide;
    static const long ID_CHECKBOX_Circles_Radial;
    static const long ID_BITMAPBUTTON_CHECKBOX_Circles_Radial;
    static const long ID_CHECKBOX_Circles_Plasma;
    static const long ID_BITMAPBUTTON_CHECKBOX_Circles_Plasma;
    static const long ID_CHECKBOX_Circles_Radial_3D;
    static const long ID_BITMAPBUTTON_CHECKBOX_Circles_Radial_3D;
    static const long ID_CHECKBOX_Circles_Random_m;
    static const long ID_BITMAPBUTTON_CHECKBOX_Circles_Random_m;
    static const long ID_PANEL37;
    static const long ID_STATICTEXT21;
    static const long ID_SLIDER_ColorWash_Count;
    static const long ID_BITMAPBUTTON_SLIDER_ColorWash_Count;
    static const long ID_STATICTEXT32;
    static const long ID_CHECKBOX_ColorWash_HFade;
    static const long ID_BITMAPBUTTON_CHECKBOX_ColorWash_HFade;
    static const long ID_STATICTEXT33;
    static const long ID_CHECKBOX_ColorWash_VFade;
    static const long ID_BITMAPBUTTON_CHECKBOX_ColorWash_VFade;
    static const long ID_PANEL5;
    static const long ID_STATICTEXT73;
    static const long ID_CHOICE_CoroFaces_Phoneme;
    static const long ID_STATICTEXT64;
    static const long ID_CHOICE_CoroFaces_Eyes;
    static const long ID_STATICTEXT66;
    static const long ID_CHECKBOX_CoroFaces_Outline;
    static const long ID_PANEL28;
    static const long ID_STATICTEXT6;
    static const long ID_CHOICE_Curtain_Edge;
    static const long ID_BITMAPBUTTON_CHOICE_Curtain_Edge;
    static const long ID_STATICTEXT5;
    static const long ID_CHOICE_Curtain_Effect;
    static const long ID_BITMAPBUTTON_CHOICE_Curtain_Effect;
    static const long ID_STATICTEXT7;
    static const long ID_SLIDER_Curtain_Swag;
    static const long ID_BITMAPBUTTON_SLIDER_Curtain_Swag;
    static const long ID_CHECKBOX_Curtain_Repeat;
    static const long ID_BITMAPBUTTON_CHECKBOX_Curtain_Repeat;
    static const long ID_PANEL1;
    static const long ID_STATICTEXT15;
    static const long ID_CHOICE_Faces_Phoneme;
    static const long ID_PANEL6;
    static const long ID_STATICTEXT84;
    static const long ID_SLIDER_Fire_Height;
    static const long ID_BITMAPBUTTON_SLIDER_Fire_Height;
    static const long ID_STATICTEXT133;
    static const long ID_SLIDER_Fire_HueShift;
    static const long ID_BITMAPBUTTON_SLIDER_Fire_HueShift;
    static const long ID_STATICTEXT135;
    static const long ID_CHECKBOX_Fire_GrowFire;
    static const long ID_BITMAPBUTTON_CHECKBOX_Fire_GrowFire;
    static const long ID_PANEL12;
    static const long ID_STATICTEXT95;
    static const long ID_SLIDER_Fireworks_Number_Explosions;
    static const long ID_BITMAPBUTTON_SLIDER_Fireworks_Number_Explosions;
    static const long ID_STATICTEXT92;
    static const long ID_SLIDER_Fireworks_Count;
    static const long ID_BITMAPBUTTON_SLIDER_Fireworks_Count;
    static const long ID_STATICTEXT94;
    static const long ID_SLIDER_Fireworks_Velocity;
    static const long ID_BITMAPBUTTON_SLIDER_Fireworks_Velocity;
    static const long ID_STATICTEXT96;
    static const long ID_SLIDER_Fireworks_Fade;
    static const long ID_BITMAPBUTTON_SLIDER_Fireworks_Fade;
    static const long ID_PANEL36;
    static const long ID_STATICTEXT34;
    static const long ID_SLIDER_Garlands_Type;
    static const long ID_BITMAPBUTTON_SLIDER_Garlands_Type;
    static const long ID_STATICTEXT35;
    static const long ID_SLIDER_Garlands_Spacing;
    static const long ID_BITMAPBUTTON_SLIDER_Garlands_Spacing;
    static const long ID_PANEL14;
    static const long ID_BUTTON3;
    static const long ID_BITMAPBUTTON10;
    static const long ID_TEXTCTRL_Glediator_Filename;
    static const long ID_PANEL17;
    static const long ID_STATICTEXT36;
    static const long ID_SLIDER_Life_Count;
    static const long ID_BITMAPBUTTON_SLIDER_Life_Count;
    static const long ID_STATICTEXT37;
    static const long ID_SLIDER_Life_Seed;
    static const long ID_BITMAPBUTTON_SLIDER_Life_Seed;
    static const long ID_PANEL16;
    static const long ID_STATICTEXT39;
    static const long ID_CHOICE_Meteors_Type;
    static const long ID_BITMAPBUTTON_CHOICE_Meteors_Type;
    static const long ID_STATICTEXT129;
    static const long ID_CHOICE_Meteors_Effect;
    static const long ID_BITMAPBUTTON_CHOICE_Meteors_Effect;
    static const long ID_STATICTEXT41;
    static const long ID_SLIDER_Meteors_Count;
    static const long ID_BITMAPBUTTON_SLIDER_Meteors_Count;
    static const long ID_STATICTEXT43;
    static const long ID_SLIDER_Meteors_Length;
    static const long ID_BITMAPBUTTON_SLIDER_Meteors_Length;
    static const long ID_STATICTEXT131;
    static const long ID_SLIDER_Meteors_Swirl_Intensity;
    static const long ID_BITMAPBUTTON_SLIDER_Meteors_Swirl_Intensity;
    static const long ID_PANEL18;
    static const long ID_STATICTEXT1;
    static const long ID_CHOICE_Piano_Style;
    static const long ID_BITMAPBUTTON_SLIDER_Piano_Style;
    static const long ID_STATICTEXT_Piano_NumKeys;
    static const long ID_SLIDER_Piano_NumKeys;
    static const long ID_BITMAPBUTTON_Piano_NumKeys;
    static const long ID_STATICTEXT_Piano_NumRows;
    static const long ID_SLIDER_Piano_KeyWidth;
    static const long ID_BITMAPBUTTON_Piano_NumRows;
    static const long ID_STATICTEXT20;
    static const long ID_CHOICE_PianoPlacement;
    static const long ID_BITMAPBUTTON_Piano_KeyPlacement;
    static const long ID_BUTTON_Piano_CueFilename;
    static const long ID_BITMAPBUTTON_Piano_Filename;
    static const long ID_STATICTEXT14;
    static const long ID_TEXTCTRL_Piano_CueFilename;
    static const long ID_PANEL9;
    static const long ID_BUTTON1;
    static const long ID_BITMAPBUTTON_Piano_MapFilename;
    static const long ID_STATICTEXT13;
    static const long ID_TEXTCTRL_Piano_MapFilename;
    static const long ID_PANEL11;
    static const long ID_BUTTON2;
    static const long ID_BITMAPBUTTON_Piano_ShapeFilename;
    static const long ID_CHECKBOX1;
    static const long ID_BITMAPBUTTON_Piano_Clipping;
    static const long ID_TEXTCTRL_Piano_ShapeFilename;
    static const long ID_PANEL13;
    static const long ID_NOTEBOOK2;
    static const long ID_STATICTEXT4;
    static const long ID_PANEL39;
    static const long ID_BUTTON_PICTURES_FILENAME;
    static const long ID_BITMAPBUTTON_BUTTON_PICTURES_FILENAME;
    static const long ID_TEXTCTRL_Pictures_Filename;
    static const long ID_STATICTEXT46;
    static const long ID_CHOICE_Pictures_Direction;
    static const long ID_BITMAPBUTTON_CHOICE_Pictures_Direction;
    static const long ID_STATICTEXT97;
    static const long ID_SLIDER_Pictures_GifSpeed;
    static const long ID_BITMAPBUTTON_SLIDER_Pictures_GifSpeed;
    static const long ID_PANEL20;
    static const long ID_STATICTEXT63;
    static const long ID_CHOICE_SingleStrand_Colors;
    static const long ID_BITMAPBUTTON_SingleStrand_Colors;
    static const long ID_STATICTEXT62;
    static const long ID_SLIDER_Number_Chases;
    static const long ID_BITMAPBUTTON_Number_Chases;
    static const long ID_STATICTEXT8;
    static const long ID_SLIDER_Color_Mix1;
    static const long ID_BITMAPBUTTON_SLIDER_Color_Mix1;
    static const long ID_STATICTEXT9;
    static const long ID_SLIDER_Chase_Spacing1;
    static const long ID_BITMAPBUTTON_SLIDER_Chase_Spacing1;
    static const long ID_STATICTEXT10;
    static const long ID_CHOICE_Chase_Type1;
    static const long ID_BITMAPBUTTON_CHOICE_Chase_Type1;
    static const long ID_STATICTEXT11;
    static const long ID_CHECKBOX_Chase_3dFade1;
    static const long ID_BITMAPBUTTON_CHECKBOX_Chase_3dFade1;
    static const long ID_STATICTEXT12;
    static const long ID_CHECKBOX_Chase_Group_All;
    static const long ID_BITMAPBUTTON_Chase_Group_All;
    static const long ID_PANEL3;
    static const long ID_NOTEBOOK1;
    static const long ID_PANEL2;
    static const long ID_STATICTEXT80;
    static const long ID_SLIDER_Snowflakes_Count;
    static const long ID_BITMAPBUTTON_SLIDER_Snowflakes_Count;
    static const long ID_STATICTEXT81;
    static const long ID_SLIDER_Snowflakes_Type;
    static const long ID_BITMAPBUTTON_SLIDER_Snowflakes_Type;
    static const long ID_PANEL22;
    static const long ID_STATICTEXT45;
    static const long ID_SLIDER_Snowstorm_Count;
    static const long ID_BITMAPBUTTON_SLIDER_Snowstorm_Count;
    static const long ID_STATICTEXT51;
    static const long ID_SLIDER_Snowstorm_Length;
    static const long ID_BITMAPBUTTON_SLIDER_Snowstorm_Length;
    static const long ID_PANEL24;
    static const long ID_STATICTEXT38;
    static const long ID_SLIDER_Spirals_Count;
    static const long ID_BITMAPBUTTON_SLIDER_Spirals_Count;
    static const long ID_STATICTEXT40;
    static const long ID_SLIDER_Spirals_Rotation;
    static const long ID_BITMAPBUTTON_SLIDER_Spirals_Rotation;
    static const long ID_STATICTEXT42;
    static const long ID_SLIDER_Spirals_Thickness;
    static const long ID_BITMAPBUTTON_SLIDER_Spirals_Thickness;
    static const long ID_STATICTEXT44;
    static const long ID_SLIDER_Spirals_Direction;
    static const long ID_BITMAPBUTTON_SLIDER_Spirals_Direction;
    static const long ID_CHECKBOX_Spirals_Blend;
    static const long ID_BITMAPBUTTON_CHECKBOX_Spirals_Blend;
    static const long ID_CHECKBOX_Spirals_3D;
    static const long ID_BITMAPBUTTON_CHECKBOX_Spirals_3D;
    static const long ID_CHECKBOX_Spirals_Grow;
    static const long ID_BITMAPBUTTON_CHECKBOX_Spirals_Grow;
    static const long ID_CHECKBOX_Spirals_Shrink;
    static const long ID_BITMAPBUTTON_CHECKBOX_Spirals_Shrink;
    static const long ID_PANEL26;
    static const long ID_STATICTEXT88;
    static const long ID_SLIDER_Spirograph_R;
    static const long ID_BITMAPBUTTON_SLIDER_Spirograph_R;
    static const long ID_STATICTEXT89;
    static const long ID_SLIDER_Spirograph_r;
    static const long ID_BITMAPBUTTON_SLIDER_Spirograph_r;
    static const long ID_STATICTEXT90;
    static const long ID_SLIDER_Spirograph_d;
    static const long ID_BITMAPBUTTON_SLIDER_Spirograph_d;
    static const long ID_STATICTEXT93;
    static const long ID_CHECKBOX_Spirograph_Animate;
    static const long ID_BITMAPBUTTON_CHECKBOX_Spirograph_Animate;
    static const long ID_STATICTEXT91;
    static const long ID_PANEL35;
    static const long ID_STATICTEXT53;
    static const long ID_TEXTCTRL_Text_Line1;
    static const long ID_BITMAPBUTTON_TEXTCTRL_Text_Line1;
    static const long ID_STATICTEXT54;
    static const long ID_TEXTCTRL_Text_Line2;
    static const long ID_BITMAPBUTTON_TEXTCTRL_Text_Line2;
    static const long ID_STATICTEXT22;
    static const long ID_TEXTCTRL_Text_Line3;
    static const long ID_BITMAPBUTTON_TEXTCTRL_Text_Line3;
    static const long ID_STATICTEXT23;
    static const long ID_TEXTCTRL_Text_Line4;
    static const long ID_BITMAPBUTTON_TEXTCTRL_Text_Line4;
    static const long ID_BUTTON_TEXT_FONT1;
    static const long ID_TEXTCTRL_Text_Font1;
    static const long ID_BITMAPBUTTON_TEXTCTRL_Text_Font1;
    static const long ID_STATICTEXT79;
    static const long ID_CHOICE_Text_Dir1;
    static const long ID_BITMAPBUTTON_CHOICE_Text_Dir1;
    static const long ID_CHECKBOX_TextToCenter1;
    static const long ID_BITMAPBUTTON_TextToCenter1;
    static const long ID_STATICTEXT108;
    static const long ID_CHOICE_Text_Effect1;
    static const long ID_BITMAPBUTTON_CHOICE_Text_Effect1;
    static const long ID_STATICTEXT99;
    static const long ID_CHOICE_Text_Count1;
    static const long ID_BITMAPBUTTON_CHOICE_Text_Count1;
    static const long ID_STATICTEXT101;
    static const long ID_SLIDER_Text_Position1;
    static const long ID_BITMAPBUTTON_SLIDER_Text_Position1;
    static const long ID_PANEL_Text1;
    static const long ID_BUTTON_TEXT_FONT2;
    static const long ID_TEXTCTRL_Text_Font2;
    static const long ID_BITMAPBUTTON_TEXTCTRL_Text_Font2;
    static const long ID_STATICTEXT57;
    static const long ID_CHOICE_Text_Dir2;
    static const long ID_BITMAPBUTTON_CHOICE_Text_Dir2;
    static const long ID_CHECKBOX_TextToCenter2;
    static const long ID_BITMAPBUTTON_Text2Center2;
    static const long ID_STATICTEXT109;
    static const long ID_CHOICE_Text_Effect2;
    static const long ID_BITMAPBUTTON_CHOICE_Text_Effect2;
    static const long ID_STATICTEXT104;
    static const long ID_CHOICE_Text_Count2;
    static const long ID_BITMAPBUTTON_CHOICE_Text_Count2;
    static const long ID_STATICTEXT103;
    static const long ID_SLIDER_Text_Position2;
    static const long ID_BITMAPBUTTON_SLIDER_Text_Position2;
    static const long ID_PANEL_Text2;
    static const long ID_BUTTON_TEXT_FONT3;
    static const long ID_TEXTCTRL_Text_Font3;
    static const long ID_BITMAPBUTTON_TEXTCTRL_Text_Font3;
    static const long ID_STATICTEXT16;
    static const long ID_CHOICE_Text_Dir3;
    static const long ID_BITMAPBUTTON_CHOICE_Text_Dir3;
    static const long ID_CHECKBOX_TextToCenter3;
    static const long ID_BITMAPBUTTON_TextToCenter3;
    static const long ID_STATICTEXT17;
    static const long ID_CHOICE_Text_Effect3;
    static const long ID_BITMAPBUTTON_CHOICE_Text_Effect3;
    static const long ID_STATICTEXT18;
    static const long ID_CHOICE_Text_Count3;
    static const long ID_BITMAPBUTTON_CHOICE_Text_Count3;
    static const long ID_STATICTEXT19;
    static const long ID_SLIDER_Text_Position3;
    static const long ID_BITMAPBUTTON_SLIDER_Text_Position3;
    static const long ID_PANEL_Text3;
    static const long ID_BUTTON_TEXT_FONT4;
    static const long ID_TEXTCTRL_Text_Font4;
    static const long ID_BITMAPBUTTON_TEXTCTRL_Text_Font4;
    static const long ID_STATICTEXT24;
    static const long ID_CHOICE_Text_Dir4;
    static const long ID_BITMAPBUTTON_CHOICE_Text_Dir4;
    static const long ID_CHECKBOX_TextToCenter4;
    static const long ID_BITMAPBUTTON_TextToCenter4;
    static const long ID_STATICTEXT29;
    static const long ID_CHOICE_Text_Effect4;
    static const long ID_BITMAPBUTTON_CHOICE_Text_Effect4;
    static const long ID_STATICTEXT47;
    static const long ID_CHOICE_Text_Count4;
    static const long ID_BITMAPBUTTON_CHOICE_Text_Count4;
    static const long ID_STATICTEXT48;
    static const long ID_SLIDER_Text_Position4;
    static const long ID_BITMAPBUTTON_SLIDER_Text_Position4;
    static const long ID_PANEL_Text4;
    static const long ID_NOTEBOOK_Text1;
    static const long ID_PANEL7;
    static const long ID_STATICTEXT87;
    static const long ID_SLIDER_Tree_Branches;
    static const long ID_BITMAPBUTTON_SLIDER_Tree_Branches;
    static const long ID_PANEL34;
    static const long ID_STATICTEXT86;
    static const long ID_SLIDER_Twinkle_Count;
    static const long ID_BITMAPBUTTON_SLIDER_Twinkle_Count;
    static const long ID_STATICTEXT105;
    static const long ID_SLIDER_Twinkle_Steps;
    static const long ID_BITMAPBUTTON_SLIDER_Twinkle_Steps;
    static const long ID_CHECKBOX_Twinkle_Strobe;
    static const long ID_BITMAPBUTTON_CHECKBOX_Twinkle_Strobe;
    static const long ID_PANEL33;
    static const long ID_STATICTEXT49;
    static const long ID_CHOICE_Wave_Type;
    static const long ID_BITMAPBUTTON2;
    static const long ID_STATICTEXT50;
    static const long ID_CHOICE_Fill_Colors;
    static const long ID_BITMAPBUTTON3;
    static const long ID_STATICTEXT52;
    static const long ID_CHECKBOX_Mirror_Wave;
    static const long ID_BITMAPBUTTON4;
    static const long ID_STATICTEXT55;
    static const long ID_SLIDER_Number_Waves;
    static const long ID_BITMAPBUTTON5;
    static const long ID_STATICTEXT56;
    static const long ID_SLIDER_Thickness_Percentage;
    static const long ID_BITMAPBUTTON6;
    static const long ID_STATICTEXT58;
    static const long ID_SLIDER_Wave_Height;
    static const long ID_BITMAPBUTTON7;
    static const long ID_STATICTEXT59;
    static const long ID_CHOICE_Wave_Direction;
    static const long ID_BITMAPBUTTON8;
    static const long ID_PANEL15;
    static const long ID_CHOICEBOOK1;
    static const long ID_BITMAPBUTTON_CHOICEBOOK1;
    static const long ID_BITMAPBUTTON87;
    static const long ID_BITMAPBUTTON1;
    static const long ID_BITMAPBUTTON88;
    static const long ID_CHECKBOX_Palette1;
    static const long ID_BUTTON_Palette1;
    static const long ID_BITMAPBUTTON_BUTTON_Palette1;
    static const long ID_CHECKBOX_Palette2;
    static const long ID_BUTTON_Palette2;
    static const long ID_BITMAPBUTTON_BUTTON_Palette2;
    static const long ID_CHECKBOX_Palette3;
    static const long ID_BUTTON_Palette3;
    static const long ID_BITMAPBUTTON_BUTTON_Palette3;
    static const long ID_CHECKBOX_Palette4;
    static const long ID_BUTTON_Palette4;
    static const long ID_BITMAPBUTTON_BUTTON_Palette4;
    static const long ID_CHECKBOX_Palette5;
    static const long ID_BUTTON_Palette5;
    static const long ID_BITMAPBUTTON_BUTTON_Palette5;
    static const long ID_CHECKBOX_Palette6;
    static const long ID_BUTTON_Palette6;
    static const long ID_BITMAPBUTTON_BUTTON_Palette6;
    static const long ID_STATICTEXT61;
    static const long ID_SLIDER_Speed;
    static const long ID_BITMAPBUTTON_SLIDER_Speed;
    static const long ID_TEXTCTRL_Speed;
    static const long ID_STATICTEXT2;
    static const long ID_TEXTCTRL_Fadein;
    static const long ID_BITMAPBUTTON_TEXTCTRL_Fadein;
    static const long ID_STATICTEXT3;
    static const long ID_TEXTCTRL_Fadeout;
    static const long ID_BITMAPBUTTON_TEXTCTRL_Fadeout;
    static const long ID_CHECKBOX_FitToTime;
    static const long ID_BITMAPBUTTON_CHECKBOX_FitToTime;
    static const long ID_CHECKBOX_OverlayBkg;
    static const long ID_BITMAPBUTTON_OverlayBkg;
    //*)

private:

    //(*Handlers(EffectsPanel)
    void OnButton_Pictures_FilenameClick(wxCommandEvent& event);
    void OnButton_pgo_filenameClick(wxCommandEvent& event);
    //    void OnButton_papagayo_output_sequenceClick(wxCommandEvent& event);
    void OnButton_Glediator_FilenameClick(wxCommandEvent& event);
    void OnButton_Text_Font1Click(wxCommandEvent& event);
    void OnButton_Text_Font2Click(wxCommandEvent& event);
    void OnCheckBox_PaletteClick(wxCommandEvent& event);
    void OnButton_PaletteNumberClick(wxCommandEvent& event);
    void OnChoicebook1PageChanged(wxChoicebookEvent& event);
    void OnButton_PaletteClick(wxCommandEvent& event);
    void OnSlider_SpeedCmdScroll(wxScrollEvent& event);
    void OnBitmapButton_FireworksCountClick(wxCommandEvent& event);
    void OnBitmapButton_LayerEffectClick(wxCommandEvent& event);
    void OnBitmapButton_Palette1Click(wxCommandEvent& event);
    void OnBitmapButton_Palette2Click(wxCommandEvent& event);
    void OnBitmapButton_Palette3Click(wxCommandEvent& event);
    void OnBitmapButton_Palette4Click(wxCommandEvent& event);
    void OnBitmapButton_Palette5Click(wxCommandEvent& event);
    void OnBitmapButton_Palette6Click(wxCommandEvent& event);
    void OnBitmapButton_SpeedClick(wxCommandEvent& event);
    void OnBitmapButton_FadeOutClick(wxCommandEvent& event);
    void OnBitmapButton_FadeInClick(wxCommandEvent& event);
    void OnBitmapButton_FitToTimeClick(wxCommandEvent& event);
    void OnBitmapButton_PaletteRepClick(wxCommandEvent& event);
    void OnBitmapButton_DirectionClick(wxCommandEvent& event);
    void OnBitmapButton_HighlightClick(wxCommandEvent& event);
    void OnBitmapButton_3DClick(wxCommandEvent& event);
    void OnBitmapButton_ButterflyColorsClick(wxCommandEvent& event);
    void OnBitmapButton_ButterflyStyleClick(wxCommandEvent& event);
    void OnBitmapButton_ButterflyChunksClick(wxCommandEvent& event);
    void OnBitmapButton_ButterflySkipClick(wxCommandEvent& event);
    void OnBitmapButton_CirclesCountClick(wxCommandEvent& event);
    void OnBitmapButton_CirclesSizeClick(wxCommandEvent& event);
    void OnBitmapButton_CirclesBounceClick(wxCommandEvent& event);
    void OnBitmapButton_CirclesRadialClick(wxCommandEvent& event);
    void OnBitmapButton_CirclesRadial3DClick(wxCommandEvent& event);
    void OnBitmapButton_CirclesCollideClick(wxCommandEvent& event);
    void OnBitmapButton_CirclesPlasmaClick(wxCommandEvent& event);
    void OnBitmapButton_RandomMotionClick(wxCommandEvent& event);
    void OnBitmapButton_ColorWashCountClick(wxCommandEvent& event);
    void OnBitmapButton_ColorWashHFadeClick(wxCommandEvent& event);
    void OnBitmapButton_ColorWashVFadeClick(wxCommandEvent& event);
    void OnBitmapButton_CurtainEdgeClick(wxCommandEvent& event);
    void OnBitmapButton_CurtainEffectClick(wxCommandEvent& event);
    void OnBitmapButton_CurtainSwagClick(wxCommandEvent& event);
    void OnBitmapButton_CurtainRepeatClick(wxCommandEvent& event);
    void OnBitmapButton_FireHeightClick(wxCommandEvent& event);
    void OnBitmapButton_FireWidthClick(wxCommandEvent& event);
    void OnBitmapButton_FireGrowClick(wxCommandEvent& event);
    void OnBitmapButton_FireworksNumberExplosionsClick(wxCommandEvent& event);
    void OnBitmapButton_FireworksVelocityClick(wxCommandEvent& event);
    void OnBitmapButton_FireworksFadeClick(wxCommandEvent& event);
    void OnBitmapButton_GarlandsTypeClick(wxCommandEvent& event);
    void OnBitmapButton_GarlandsSpacingClick(wxCommandEvent& event);
    void OnBitmapButton_LifeCountClick(wxCommandEvent& event);
    void OnBitmapButton_LifeSpeedClick(wxCommandEvent& event);
    void OnBitmapButton_MeteorsTypeClick(wxCommandEvent& event);
    void OnBitmapButton_MeteorsEffectClick(wxCommandEvent& event);
    void OnBitmapButton_MeteorsCountClick(wxCommandEvent& event);
    void OnBitmapButton_MeteorsLengthClick(wxCommandEvent& event);
    void OnBitmapButton_MeteorsSwirlIntensityClick(wxCommandEvent& event);
    void OnBitmapButton_PianoKeyboardClick(wxCommandEvent& event);
    void OnBitmapButton_PicturesFilenameClick(wxCommandEvent& event);
    void OnBitmapButton_PicturesDirectionClick(wxCommandEvent& event);
    void OnBitmapButton_PicturesSpeedClick(wxCommandEvent& event);
    void OnBitmapButton_SnowflakesCountClick(wxCommandEvent& event);
    void OnBitmapButton_SnowflakesTypeClick(wxCommandEvent& event);
    void OnBitmapButton_SnowstormCountClick(wxCommandEvent& event);
    void OnBitmapButton_SnowstormLengthClick(wxCommandEvent& event);
    void OnBitmapButton_SpiralsCountClick(wxCommandEvent& event);
    void OnBitmapButton_SpiralsRotationClick(wxCommandEvent& event);
    void OnBitmapButton_SpiralsThicknessClick(wxCommandEvent& event);
    void OnBitmapButton_SpiralsDirectionClick(wxCommandEvent& event);
    void OnBitmapButton_Spirals3DClick(wxCommandEvent& event);
    void OnBitmapButton_SpiralsShrinkClick(wxCommandEvent& event);
    void OnBitmapButton_SpiralsBlendClick(wxCommandEvent& event);
    void OnBitmapButton_SpiralsGrowClick(wxCommandEvent& event);
    void OnBitmapButton_SpirographRClick(wxCommandEvent& event);
    void OnBitmapButton_SpirographrClick(wxCommandEvent& event);
    void OnBitmapButton_SpirographAnimateClick(wxCommandEvent& event);
    void OnBitmapButton_SpirographdClick(wxCommandEvent& event);
    void OnBitmapButton_TextLine1Click(wxCommandEvent& event);
    void OnBitmapButton_TextLine2Click(wxCommandEvent& event);
    void OnBitmapButton_TextFont1Click(wxCommandEvent& event);
    void OnBitmapButton_TextDir1Click(wxCommandEvent& event);
    void OnBitmapButton_TextEffect1Click(wxCommandEvent& event);
    void OnBitmapButton_TextCount1Click(wxCommandEvent& event);
    void OnBitmapButton_TextPosition1Click(wxCommandEvent& event);
    void OnBitmapButton_TextFont2Click(wxCommandEvent& event);
    void OnBitmapButton_TextDir2Click(wxCommandEvent& event);
    void OnBitmapButton_TextEffect2Click(wxCommandEvent& event);
    void OnBitmapButton_TextCount2Click(wxCommandEvent& event);
    void OnBitmapButton_TextPosition2Click(wxCommandEvent& event);
    void OnBitmapButton_TreeBranchesClick(wxCommandEvent& event);
    void OnBitmapButton_TwinkleCountClick(wxCommandEvent& event);
    void OnBitmapButton_TwinkleStepsClick(wxCommandEvent& event);
    void OnBitmapButton_TwinkleStrobeClick(wxCommandEvent& event);
    void OnPiano_StyleSelect(wxCommandEvent& event);
    void OnSlider_Piano_NumKeysCmdScroll(wxScrollEvent& event);
    void OnTextCtrl_Piano_FilenameText(wxCommandEvent& event);
    void OnButton_Piano_FilenameClick(wxCommandEvent& event);
    void OnBitmapButton_Piano_StyleClick(wxCommandEvent& event);
    void OnBitmapButton_Piano_NumKeysClick(wxCommandEvent& event);
    void OnBitmapButton_Piano_FilenameClick(wxCommandEvent& event);
    void OnSlider_Piano_KeyWidthCmdScroll(wxScrollEvent& event);
    void OnBitmapButton_Piano_KeyWidthClick(wxCommandEvent& event);
    void OnButton_Piano_CueFilenameClick(wxCommandEvent& event);
    void OnButton_Piano_MapFilenameClick(wxCommandEvent& event);
    void OnButton_Piano_ShapeFilenameClick(wxCommandEvent& event);
    void OnBitmapButton_Piano_CueFilenameClick(wxCommandEvent& event);
    void OnBitmapButton_Piano_MapFilenameClick(wxCommandEvent& event);
    void OnBitmapButton_Piano_ShapeFilenameClick(wxCommandEvent& event);
    void OnTextCtrl_Piano_CueFilenameText(wxCommandEvent& event);
    void OnTextCtrl_Piano_MapFilenameText(wxCommandEvent& event);
    void OnTextCtrl_Piano_ShapeFilenameText(wxCommandEvent& event);
    void OnSlider_Piano_NumRowsCmdScroll(wxScrollEvent& event);
    void OnBitmapButton_Piano_NumRowsClick(wxCommandEvent& event);
    void OnBitmapButton_Piano_PlacementClick(wxCommandEvent& event);
    void OnBitmapButton_Piano_KeyPlacementClick(wxCommandEvent& event);
    void OnBitmapButton_Piano_ClippingClick(wxCommandEvent& event);
    void OnBitmapButton_Color_Mix1Click(wxCommandEvent& event);
    void OnBitmapButton_Chase_Spacing1Click(wxCommandEvent& event);
    void OnBitmapButton_Chase_Type1Click(wxCommandEvent& event);
    void OnBitmapButton_Chase_3dFade1Click(wxCommandEvent& event);
    void OnBitmapButton_R_TO_L1Click(wxCommandEvent& event);
    void OnBitmapButton_OverlayBkgClick(wxCommandEvent& event);
    void OnButton_Text_Font3Click(wxCommandEvent& event);
    void OnButton_Text_Font4Click(wxCommandEvent& event);
    void OnBitmapButton_TextLine3Click(wxCommandEvent& event);
    void OnBitmapButton_TextLine4Click(wxCommandEvent& event);
    void OnBitmapButton_TextFont3Click(wxCommandEvent& event);
    void OnBitmapButton_TextDir3Click(wxCommandEvent& event);
    void OnBitmapButton_TextEffect3Click(wxCommandEvent& event);
    void OnBitmapButton_TextCount3Click(wxCommandEvent& event);
    void OnBitmapButton_TextPosition3Click(wxCommandEvent& event);
    void OnBitmapButton_TextFont4Click(wxCommandEvent& event);
    void OnBitmapButton_TextEffect4Click(wxCommandEvent& event);
    void OnBitmapButton1Click(wxCommandEvent& event);
    void OnBitmapButton_TextCount4Click(wxCommandEvent& event);
    void OnBitmapButton_TextPosition4Click(wxCommandEvent& event);
    void OnBitmapButton_TextDir4Click(wxCommandEvent& event);
    void OnPaint(wxPaintEvent& event);
    void OnChoice_Bars_DirectionSelect(wxCommandEvent& event);
    void OnBitmapButton_TextToCenter1Click(wxCommandEvent& event);
    void OnBitmapButton_TextToCenter2Click(wxCommandEvent& event);
    void OnBitmapButton_TextToCenter3Click(wxCommandEvent& event);
    void OnBitmapButton_TextToCenter4Click(wxCommandEvent& event);
    void OnBitmapButton1Click1(wxCommandEvent& event);
    void OnBitmapButton2Click(wxCommandEvent& event);
    void OnBitmapButton3Click(wxCommandEvent& event);
    void OnBitmapButton4Click(wxCommandEvent& event);
    void OnBitmapButton5Click(wxCommandEvent& event);
    void OnBitmap_WaveTypeClick(wxCommandEvent& event);
    void OnBitmap_Wave_FillColorsClick(wxCommandEvent& event);
    void OnBitmap_Wave_MirrorWaveClick(wxCommandEvent& event);
    void OnBitmap_NumberWavesClick(wxCommandEvent& event);
    void OnBitmap_Wave_ThicknessClick(wxCommandEvent& event);
    void OnBitmap_Wave_HeightClick(wxCommandEvent& event);
    void OnBitmap_Wave_DirectionClick(wxCommandEvent& event);
    void OnBitmap_Glediator_FilenameClick(wxCommandEvent& event);
    void OnBitmapButton_Glediator_FilenameClick(wxCommandEvent& event);
    void OnBitmap_WaveTypeClick1(wxCommandEvent& event);
    void OnBitmap_Wave_FillColorsClick1(wxCommandEvent& event);
    void OnBitmap_Wave_MirrorWaveClick1(wxCommandEvent& event);
    void OnBitmap_NumberWavesClick1(wxCommandEvent& event);
    void OnBitmap_Wave_ThicknessClick1(wxCommandEvent& event);
    void OnBitmap_Wave_HeightClick1(wxCommandEvent& event);
    void OnBitmap_Wave_DirectionClick1(wxCommandEvent& event);
    void OnBitmapButton_WaveTypeClick(wxCommandEvent& event);
    void OnBitmapButton_Wave_FillColorsClick(wxCommandEvent& event);
    void OnBitmapButton_Wave_MirrorWaveClick(wxCommandEvent& event);
    void OnBitmapButton_NumberWavesClick(wxCommandEvent& event);
    void OnBitmapButton_Wave_ThicknessClick(wxCommandEvent& event);
    void OnBitmapButton_Wave_HeightClick(wxCommandEvent& event);
    void OnBitmapButton_Wave_DirectionClick(wxCommandEvent& event);
    void OnSlider_Wave_HeightCmdScroll(wxScrollEvent& event);
    void OnBitmapButton_Number_ChasesClick(wxCommandEvent& event);
    void OnBitmapButton_Chase_Group_AllClick(wxCommandEvent& event);
    void OnBitmapButton_SingleStrand_ColorsClick(wxCommandEvent& event);
    void OnTextCtrl2Text(wxCommandEvent& event);
    void OnTextCtrl1Text(wxCommandEvent& event);
    //*)

    void UpdateFont(wxTextCtrl* FontCtrl);
    void SetButtonColor(wxButton* btn, const wxColour* c);
    int GetRandomSliderValue(wxSlider* slider);
    wxString GetAttrPrefix();
    wxString GetEffectStringFromWindow(wxWindow *ParentWin);

//add lock/unlock/random state flags -DJ
//these could be used to make fields read-only, but initially they are just used for partially random effects
//#include <unordered_map>
    typedef enum { Normal, Locked, Random } EditState;
    std::unordered_map<std::string, EditState> buttonState;
    bool isRandom_(wxControl* ctl, const char*debug);
#define isRandom(ctl)  isRandom_(ctl, #ctl) //(buttonState[std::string(ctl->GetName())] == Random)
    void setlock(wxButton* button); //, EditState& islocked);
//friend class xLightsFrame; //debug only
    wxCheckBox* GetPaletteCheckbox(int idx);
    wxButton* GetPaletteButton(int idx);
    wxColourData colorData;

    DECLARE_EVENT_TABLE()
public:
    bool isRandom_(void);
    void UpdateSpeedText();
    bool WantOverlayBkg(void); //selectable clear canvas before render -DJ
};

#endif
