//
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#pragma once
#include <stdint.h>

#if !defined(__cplusplus)
#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L)
#include <stdbool.h>
#else
typedef int bool;
#endif
#endif



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus
///////////////////////////////////////////////////////////////////////////
// Vector types with external visibility from ispc code
///////////////////////////////////////////////////////////////////////////

#ifndef __ISPC_VECTOR_uint8_t4__
#define __ISPC_VECTOR_uint8_t4__
#ifdef _MSC_VER
__declspec( align(4) ) struct uint8_t4 { uint8_t v[4]; };
#else
struct uint8_t4 { uint8_t v[4]; } __attribute__ ((aligned(4)));
#endif
#endif



/* Portable alignment macro that works across different compilers and standards */
#if defined(__cplusplus) && __cplusplus >= 201103L
/* C++11 or newer - use alignas keyword */
#define __ISPC_ALIGN__(x) alignas(x)
#elif defined(__GNUC__) || defined(__clang__)
/* GCC or Clang - use __attribute__ */
#define __ISPC_ALIGN__(x) __attribute__((aligned(x)))
#elif defined(_MSC_VER)
/* Microsoft Visual C++ - use __declspec */
#define __ISPC_ALIGN__(x) __declspec(align(x))
#else
/* Unknown compiler/standard - alignment not supported */
#define __ISPC_ALIGN__(x)
#warning "Alignment not supported on this compiler"
#endif // defined(__cplusplus) && __cplusplus >= 201103L
#ifndef __ISPC_ALIGNED_STRUCT__
#if defined(__clang__) || !defined(_MSC_VER) || _MSC_VER > 1943
// Clang, GCC, ICC, Visual Studio
#define __ISPC_ALIGNED_STRUCT__(s) struct __ISPC_ALIGN__(s)
#else
// Older Visual Studio
#define __ISPC_ALIGNED_STRUCT__(s) __ISPC_ALIGN__(s) struct
#endif // defined(__clang__) || !defined(_MSC_VER) || _MSC_VER > 1943
#endif // __ISPC_ALIGNED_STRUCT__

#ifndef __ISPC_STRUCT_WarpData__
#define __ISPC_STRUCT_WarpData__
struct WarpData {
    uint32_t width;
    uint32_t height;
    int32_t warpMode;
    float progress;
    float cx;
    float cy;
    float speed;
    float frequency;
    int32_t dissolveW;
    int32_t dissolveH;
};
#endif


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
extern "C" {
#endif // __cplusplus
    extern void WarpBandedSwirl(const struct WarpData * data, int32_t startIdx, int32_t endIdx, const uint8_t4   * src, uint8_t4   * dst, bool inward);
    extern void WarpCircleReveal(const struct WarpData * data, int32_t startIdx, int32_t endIdx, const uint8_t4   * src, uint8_t4   * dst, bool inward);
    extern void WarpCircularSwirl(const struct WarpData * data, int32_t startIdx, int32_t endIdx, const uint8_t4   * src, uint8_t4   * dst);
    extern void WarpCopy(const struct WarpData * data, int32_t startIdx, int32_t endIdx, const uint32_t * src, uint32_t * dst);
    extern void WarpDissolve(const struct WarpData * data, int32_t startIdx, int32_t endIdx, const uint8_t4   * src, uint8_t4   * dst, const uint8_t * dissolve, bool inward);
    extern void WarpDrop(const struct WarpData * data, int32_t startIdx, int32_t endIdx, const uint32_t * src, uint32_t * dst, const uint8_t * dissolve);
    extern void WarpFlip(const struct WarpData * data, int32_t startIdx, int32_t endIdx, const uint32_t * src, uint32_t * dst);
    extern void WarpMirror(const struct WarpData * data, int32_t startIdx, int32_t endIdx, const uint32_t * src, uint32_t * dst);
    extern void WarpRipple(const struct WarpData * data, int32_t startIdx, int32_t endIdx, const uint8_t4   * src, uint8_t4   * dst, bool inward);
    extern void WarpSingleWaterDrop(const struct WarpData * data, int32_t startIdx, int32_t endIdx, const uint32_t * src, uint32_t * dst);
    extern void WarpWaterDrops(const struct WarpData * data, int32_t startIdx, int32_t endIdx, const uint32_t * src, uint32_t * dst);
    extern void WarpWavy(const struct WarpData * data, int32_t startIdx, int32_t endIdx, const uint32_t * src, uint32_t * dst, const uint8_t * dissolve);
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus
