#include "DMXPanel.h"

#include "EffectPanelUtils.h"
//(*InternalHeaders(DMXPanel)
#include <wx/notebook.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/checkbox.h>
#include <wx/slider.h>
#include <wx/choice.h>
#include <wx/intl.h>
#include <wx/string.h>
//*)

//(*IdInit(DMXPanel)
const long DMXPanel::ID_SLIDER_DMX1 = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX1 = wxNewId();
const long DMXPanel::ID_SLIDER_DMX2 = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX2 = wxNewId();
const long DMXPanel::ID_SLIDER_DMX3 = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX3 = wxNewId();
const long DMXPanel::ID_SLIDER_DMX4 = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX4 = wxNewId();
const long DMXPanel::ID_SLIDER_DMX5 = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX5 = wxNewId();
const long DMXPanel::ID_SLIDER_DMX6 = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX6 = wxNewId();
const long DMXPanel::ID_SLIDER_DMX7 = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX7 = wxNewId();
const long DMXPanel::ID_SLIDER_DMX8 = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX8 = wxNewId();
const long DMXPanel::ID_SLIDER_DMX9 = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX9 = wxNewId();
const long DMXPanel::ID_CHOICE_Num_Dmx_Channels = wxNewId();
const long DMXPanel::ID_CHECKBOX_Use_Dmx_Ramps = wxNewId();
const long DMXPanel::ID_PANEL6 = wxNewId();
const long DMXPanel::ID_SLIDER_DMX10 = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX10 = wxNewId();
const long DMXPanel::ID_SLIDER_DMX11 = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX11 = wxNewId();
const long DMXPanel::ID_SLIDER_DMX12 = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX12 = wxNewId();
const long DMXPanel::ID_SLIDER_DMX13 = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX13 = wxNewId();
const long DMXPanel::ID_SLIDER_DMX14 = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX14 = wxNewId();
const long DMXPanel::ID_SLIDER_DMX15 = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX15 = wxNewId();
const long DMXPanel::ID_PANEL28 = wxNewId();
const long DMXPanel::ID_SLIDER_DMX1_Ramp = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX1_Ramp = wxNewId();
const long DMXPanel::ID_SLIDER_DMX2_Ramp = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX2_Ramp = wxNewId();
const long DMXPanel::ID_SLIDER_DMX3_Ramp = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX3_Ramp = wxNewId();
const long DMXPanel::ID_SLIDER_DMX4_Ramp = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX4_Ramp = wxNewId();
const long DMXPanel::ID_SLIDER_DMX5_Ramp = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX5_Ramp = wxNewId();
const long DMXPanel::ID_SLIDER_DMX6_Ramp = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX6_Ramp = wxNewId();
const long DMXPanel::ID_SLIDER_DMX7_Ramp = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX7_Ramp = wxNewId();
const long DMXPanel::ID_SLIDER_DMX8_Ramp = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX8_Ramp = wxNewId();
const long DMXPanel::ID_SLIDER_DMX9_Ramp = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX9_Ramp = wxNewId();
const long DMXPanel::ID_PANEL48 = wxNewId();
const long DMXPanel::ID_SLIDER_DMX10_Ramp = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX10_Ramp = wxNewId();
const long DMXPanel::ID_SLIDER_DMX11_Ramp = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX11_Ramp = wxNewId();
const long DMXPanel::ID_SLIDER_DMX12_Ramp = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX12_Ramp = wxNewId();
const long DMXPanel::ID_SLIDER_DMX13_Ramp = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX13_Ramp = wxNewId();
const long DMXPanel::ID_SLIDER_DMX14_Ramp = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX14_Ramp = wxNewId();
const long DMXPanel::ID_SLIDER_DMX15_Ramp = wxNewId();
const long DMXPanel::IDD_TEXTCTRL_DMX15_Ramp = wxNewId();
const long DMXPanel::ID_PANEL49 = wxNewId();
const long DMXPanel::ID_NOTEBOOK1 = wxNewId();
//*)

BEGIN_EVENT_TABLE(DMXPanel,wxPanel)
	//(*EventTable(DMXPanel)
	//*)
END_EVENT_TABLE()

DMXPanel::DMXPanel(wxWindow* parent)
{
	//(*Initialize(DMXPanel)
	wxStaticText* StaticText215;
	wxStaticText* StaticText217;
	wxStaticText* StaticText243;
	wxStaticText* StaticText223;
	wxStaticText* StaticText219;
	wxTextCtrl* TextCtrl_DMX6_Ramp;
	wxStaticText* StaticText224;
	wxStaticText* StaticText218;
	wxSlider* Slider_DMX15_Ramp;
	wxTextCtrl* TextCtrl1_DMX5;
	wxSlider* Slider_DMX3;
	wxTextCtrl* TextCtrl1_DMX9;
	wxSlider* Slider_DMX4_Ramp;
	wxStaticText* StaticText239;
	wxSlider* Slider_DMX6;
	wxTextCtrl* TextCtrl_DMX14_Ramp;
	wxFlexGridSizer* FlexGridSizer149;
	wxTextCtrl* TextCtrl1_DMX6;
	wxStaticText* StaticText237;
	wxStaticText* StaticText220;
	wxTextCtrl* TextCtrl_DMX5_Ramp;
	wxStaticText* StaticText230;
	wxSlider* Slider_DMX14;
	wxSlider* Slider_DMX2;
	wxSlider* Slider_DMX11_Ramp;
	wxSlider* Slider_DMX1_Ramp;
	wxSlider* Slider_DMX4;
	wxTextCtrl* TextCtrl_DMX3_Ramp;
	wxStaticText* StaticText232;
	wxSlider* Slider_DMX9_Ramp;
	wxTextCtrl* TextCtrl1_DMX7;
	wxTextCtrl* TextCtrl_DMX15_Ramp;
	wxSlider* Slider_DMX15;
	wxStaticText* StaticText226;
	wxSlider* Slider_DMX14_Ramp;
	wxFlexGridSizer* FlexGridSizer146;
	wxStaticText* StaticText233;
	wxSlider* Slider_DMX7_Ramp;
	wxTextCtrl* TextCtrl_DMX9_Ramp;
	wxStaticText* StaticText227;
	wxTextCtrl* TextCtrl_DMX1_Ramp;
	wxSlider* Slider_DMX1;
	wxTextCtrl* TextCtrl_DMX12_Ramp;
	wxStaticText* StaticText238;
	wxTextCtrl* TextCtrl1_DMX1;
	wxTextCtrl* TextCtrl_DMX11_Ramp;
	wxStaticText* StaticText234;
	wxTextCtrl* TextCtrl_DMX13;
	wxStaticText* StaticText225;
	wxSlider* Slider_DMX13_Ramp;
	wxStaticText* StaticText236;
	wxTextCtrl* TextCtrl1_DMX2;
	wxTextCtrl* TextCtrl_DMX15;
	wxStaticText* StaticText228;
	wxTextCtrl* TextCtrl_DMX8_Ramp;
	wxTextCtrl* TextCtrl_DMX14;
	wxStaticText* StaticText242;
	wxFlexGridSizer* FlexGridSizer148;
	wxStaticText* StaticText229;
	wxSlider* Slider_DMX11;
	wxSlider* Slider_DMX7;
	wxStaticText* StaticText235;
	wxTextCtrl* TextCtrl_DMX13_Ramp;
	wxTextCtrl* TextCtrl_DMX11;
	wxTextCtrl* TextCtrl_DMX4;
	wxStaticText* StaticText216;
	wxSlider* Slider_DMX5_Ramp;
	wxSlider* Slider_DMX8_Ramp;
	wxSlider* Slider_DMX12_Ramp;
	wxStaticText* StaticText100;
	wxSlider* Slider_DMX10_Ramp;
	wxSlider* Slider_DMX13;
	wxTextCtrl* TextCtrl_DMX10;
	wxTextCtrl* TextCtrl1_DMX8;
	wxStaticText* StaticText231;
	wxStaticText* StaticText222;
	wxStaticText* StaticText240;
	wxStaticText* StaticText241;
	wxSlider* Slider_DMX9;
	wxTextCtrl* TextCtrl_DMX2_Ramp;
	wxTextCtrl* TextCtrl_DMX10_Ramp;
	wxSlider* Slider_DMX3_Ramp;
	wxStaticText* StaticText221;
	wxSlider* Slider_DMX8;
	wxTextCtrl* TextCtrl_DMX4_Ramp;
	wxTextCtrl* TextCtrl1_DMX3;
	wxSlider* Slider_DMX2_Ramp;
	wxFlexGridSizer* FlexGridSizer150;
	wxTextCtrl* TextCtrl_DMX7_Ramp;
	wxTextCtrl* TextCtrl_DMX12;
	wxSlider* Slider_DMX10;
	wxSlider* Slider_DMX5;
	wxSlider* Slider_DMX6_Ramp;
	wxFlexGridSizer* FlexGridSizer147;
	wxSlider* Slider_DMX12;

	Create(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL, _T("wxID_ANY"));
	FlexGridSizer146 = new wxFlexGridSizer(0, 1, 0, 0);
	FlexGridSizer146->AddGrowableCol(0);
	Notebook7 = new wxNotebook(this, ID_NOTEBOOK1, wxDefaultPosition, wxDefaultSize, 0, _T("ID_NOTEBOOK1"));
	Panel18 = new wxPanel(Notebook7, ID_PANEL6, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL, _T("ID_PANEL6"));
	FlexGridSizer149 = new wxFlexGridSizer(0, 3, 0, 0);
	FlexGridSizer149->AddGrowableCol(1);
	StaticText215 = new wxStaticText(Panel18, wxID_ANY, _("Channel 1:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer149->Add(StaticText215, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX1 = new wxSlider(Panel18, ID_SLIDER_DMX1, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX1"));
	FlexGridSizer149->Add(Slider_DMX1, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl1_DMX1 = new wxTextCtrl(Panel18, IDD_TEXTCTRL_DMX1, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel18,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX1"));
	FlexGridSizer149->Add(TextCtrl1_DMX1, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	StaticText100 = new wxStaticText(Panel18, wxID_ANY, _("Channel 2:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer149->Add(StaticText100, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX2 = new wxSlider(Panel18, ID_SLIDER_DMX2, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX2"));
	FlexGridSizer149->Add(Slider_DMX2, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl1_DMX2 = new wxTextCtrl(Panel18, IDD_TEXTCTRL_DMX2, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel18,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX2"));
	FlexGridSizer149->Add(TextCtrl1_DMX2, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	StaticText216 = new wxStaticText(Panel18, wxID_ANY, _("Channel 3:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer149->Add(StaticText216, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX3 = new wxSlider(Panel18, ID_SLIDER_DMX3, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX3"));
	FlexGridSizer149->Add(Slider_DMX3, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl1_DMX3 = new wxTextCtrl(Panel18, IDD_TEXTCTRL_DMX3, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel18,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX3"));
	FlexGridSizer149->Add(TextCtrl1_DMX3, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	StaticText217 = new wxStaticText(Panel18, wxID_ANY, _("Channel 4:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer149->Add(StaticText217, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX4 = new wxSlider(Panel18, ID_SLIDER_DMX4, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX4"));
	FlexGridSizer149->Add(Slider_DMX4, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl_DMX4 = new wxTextCtrl(Panel18, IDD_TEXTCTRL_DMX4, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel18,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX4"));
	FlexGridSizer149->Add(TextCtrl_DMX4, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	StaticText218 = new wxStaticText(Panel18, wxID_ANY, _("Channel 5:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer149->Add(StaticText218, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX5 = new wxSlider(Panel18, ID_SLIDER_DMX5, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX5"));
	FlexGridSizer149->Add(Slider_DMX5, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl1_DMX5 = new wxTextCtrl(Panel18, IDD_TEXTCTRL_DMX5, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel18,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX5"));
	FlexGridSizer149->Add(TextCtrl1_DMX5, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	StaticText219 = new wxStaticText(Panel18, wxID_ANY, _("Channel 6:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer149->Add(StaticText219, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX6 = new wxSlider(Panel18, ID_SLIDER_DMX6, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX6"));
	FlexGridSizer149->Add(Slider_DMX6, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl1_DMX6 = new wxTextCtrl(Panel18, IDD_TEXTCTRL_DMX6, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel18,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX6"));
	FlexGridSizer149->Add(TextCtrl1_DMX6, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	StaticText220 = new wxStaticText(Panel18, wxID_ANY, _("Channel 7:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer149->Add(StaticText220, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX7 = new wxSlider(Panel18, ID_SLIDER_DMX7, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX7"));
	FlexGridSizer149->Add(Slider_DMX7, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl1_DMX7 = new wxTextCtrl(Panel18, IDD_TEXTCTRL_DMX7, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel18,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX7"));
	FlexGridSizer149->Add(TextCtrl1_DMX7, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	StaticText221 = new wxStaticText(Panel18, wxID_ANY, _("Channel 8:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer149->Add(StaticText221, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX8 = new wxSlider(Panel18, ID_SLIDER_DMX8, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX8"));
	FlexGridSizer149->Add(Slider_DMX8, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl1_DMX8 = new wxTextCtrl(Panel18, IDD_TEXTCTRL_DMX8, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel18,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX8"));
	FlexGridSizer149->Add(TextCtrl1_DMX8, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	StaticText222 = new wxStaticText(Panel18, wxID_ANY, _("Channel 9:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer149->Add(StaticText222, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX9 = new wxSlider(Panel18, ID_SLIDER_DMX9, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX9"));
	FlexGridSizer149->Add(Slider_DMX9, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl1_DMX9 = new wxTextCtrl(Panel18, IDD_TEXTCTRL_DMX9, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel18,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX9"));
	FlexGridSizer149->Add(TextCtrl1_DMX9, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	FlexGridSizer149->Add(-1,-1,1, wxALL|wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 5);
	Choice_Num_Dmx_Channels = new wxChoice(Panel18, ID_CHOICE_Num_Dmx_Channels, wxDefaultPosition, wxDefaultSize, 0, 0, 0, wxDefaultValidator, _T("ID_CHOICE_Num_Dmx_Channels"));
	Choice_Num_Dmx_Channels->SetSelection( Choice_Num_Dmx_Channels->Append(_("Use 1 channel")) );
	Choice_Num_Dmx_Channels->Append(_("Use 2 channels"));
	Choice_Num_Dmx_Channels->Append(_("Use 3 channels"));
	Choice_Num_Dmx_Channels->Append(_("Use 4 channels"));
	Choice_Num_Dmx_Channels->Append(_("Use 5 channels"));
	Choice_Num_Dmx_Channels->Append(_("Use 6 channels"));
	Choice_Num_Dmx_Channels->Append(_("Use 7 channels"));
	Choice_Num_Dmx_Channels->Append(_("Use 8 channels"));
	Choice_Num_Dmx_Channels->Append(_("Use 9 channels"));
	Choice_Num_Dmx_Channels->Append(_("Use 10 channels"));
	Choice_Num_Dmx_Channels->Append(_("Use 11 channels"));
	Choice_Num_Dmx_Channels->Append(_("Use 12 channels"));
	Choice_Num_Dmx_Channels->Append(_("Use 13 channels"));
	Choice_Num_Dmx_Channels->Append(_("Use 14 channels"));
	Choice_Num_Dmx_Channels->Append(_("Use 15 channels"));
	FlexGridSizer149->Add(Choice_Num_Dmx_Channels, 1, wxALL|wxEXPAND|wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 5);
	FlexGridSizer149->Add(-1,-1,1, wxALL|wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 5);
	FlexGridSizer149->Add(-1,-1,1, wxALL|wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 5);
	CheckBox_Use_Dmx_Ramps = new wxCheckBox(Panel18, ID_CHECKBOX_Use_Dmx_Ramps, _("Use Ramps"), wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_CHECKBOX_Use_Dmx_Ramps"));
	CheckBox_Use_Dmx_Ramps->SetValue(false);
	FlexGridSizer149->Add(CheckBox_Use_Dmx_Ramps, 1, wxALL|wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 5);
	Panel18->SetSizer(FlexGridSizer149);
	FlexGridSizer149->Fit(Panel18);
	FlexGridSizer149->SetSizeHints(Panel18);
	Panel19 = new wxPanel(Notebook7, ID_PANEL28, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL, _T("ID_PANEL28"));
	FlexGridSizer147 = new wxFlexGridSizer(0, 3, 0, 0);
	FlexGridSizer147->AddGrowableCol(1);
	StaticText223 = new wxStaticText(Panel19, wxID_ANY, _("Channel 10:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer147->Add(StaticText223, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX10 = new wxSlider(Panel19, ID_SLIDER_DMX10, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX10"));
	FlexGridSizer147->Add(Slider_DMX10, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl_DMX10 = new wxTextCtrl(Panel19, IDD_TEXTCTRL_DMX10, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel19,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX10"));
	FlexGridSizer147->Add(TextCtrl_DMX10, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	StaticText224 = new wxStaticText(Panel19, wxID_ANY, _("Channel 11:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer147->Add(StaticText224, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX11 = new wxSlider(Panel19, ID_SLIDER_DMX11, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX11"));
	FlexGridSizer147->Add(Slider_DMX11, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl_DMX11 = new wxTextCtrl(Panel19, IDD_TEXTCTRL_DMX11, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel19,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX11"));
	FlexGridSizer147->Add(TextCtrl_DMX11, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	StaticText225 = new wxStaticText(Panel19, wxID_ANY, _("Channel 12:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer147->Add(StaticText225, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX12 = new wxSlider(Panel19, ID_SLIDER_DMX12, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX12"));
	FlexGridSizer147->Add(Slider_DMX12, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl_DMX12 = new wxTextCtrl(Panel19, IDD_TEXTCTRL_DMX12, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel19,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX12"));
	FlexGridSizer147->Add(TextCtrl_DMX12, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	StaticText238 = new wxStaticText(Panel19, wxID_ANY, _("Channel 13:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer147->Add(StaticText238, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX13 = new wxSlider(Panel19, ID_SLIDER_DMX13, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX13"));
	FlexGridSizer147->Add(Slider_DMX13, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl_DMX13 = new wxTextCtrl(Panel19, IDD_TEXTCTRL_DMX13, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel19,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX13"));
	FlexGridSizer147->Add(TextCtrl_DMX13, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	StaticText239 = new wxStaticText(Panel19, wxID_ANY, _("Channel 14:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer147->Add(StaticText239, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX14 = new wxSlider(Panel19, ID_SLIDER_DMX14, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX14"));
	FlexGridSizer147->Add(Slider_DMX14, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl_DMX14 = new wxTextCtrl(Panel19, IDD_TEXTCTRL_DMX14, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel19,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX14"));
	FlexGridSizer147->Add(TextCtrl_DMX14, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	StaticText240 = new wxStaticText(Panel19, wxID_ANY, _("Channel 15:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer147->Add(StaticText240, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX15 = new wxSlider(Panel19, ID_SLIDER_DMX15, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX15"));
	FlexGridSizer147->Add(Slider_DMX15, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl_DMX15 = new wxTextCtrl(Panel19, IDD_TEXTCTRL_DMX15, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel19,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX15"));
	FlexGridSizer147->Add(TextCtrl_DMX15, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	Panel19->SetSizer(FlexGridSizer147);
	FlexGridSizer147->Fit(Panel19);
	FlexGridSizer147->SetSizeHints(Panel19);
	Panel20 = new wxPanel(Notebook7, ID_PANEL48, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL, _T("ID_PANEL48"));
	FlexGridSizer148 = new wxFlexGridSizer(0, 3, 0, 0);
	FlexGridSizer148->AddGrowableCol(1);
	StaticText226 = new wxStaticText(Panel20, wxID_ANY, _("Channel 1:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer148->Add(StaticText226, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX1_Ramp = new wxSlider(Panel20, ID_SLIDER_DMX1_Ramp, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX1_Ramp"));
	FlexGridSizer148->Add(Slider_DMX1_Ramp, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl_DMX1_Ramp = new wxTextCtrl(Panel20, IDD_TEXTCTRL_DMX1_Ramp, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel20,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX1_Ramp"));
	FlexGridSizer148->Add(TextCtrl_DMX1_Ramp, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	StaticText227 = new wxStaticText(Panel20, wxID_ANY, _("Channel 2:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer148->Add(StaticText227, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX2_Ramp = new wxSlider(Panel20, ID_SLIDER_DMX2_Ramp, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX2_Ramp"));
	FlexGridSizer148->Add(Slider_DMX2_Ramp, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl_DMX2_Ramp = new wxTextCtrl(Panel20, IDD_TEXTCTRL_DMX2_Ramp, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel20,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX2_Ramp"));
	FlexGridSizer148->Add(TextCtrl_DMX2_Ramp, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	StaticText228 = new wxStaticText(Panel20, wxID_ANY, _("Channel 3:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer148->Add(StaticText228, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX3_Ramp = new wxSlider(Panel20, ID_SLIDER_DMX3_Ramp, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX3_Ramp"));
	FlexGridSizer148->Add(Slider_DMX3_Ramp, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl_DMX3_Ramp = new wxTextCtrl(Panel20, IDD_TEXTCTRL_DMX3_Ramp, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel20,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX3_Ramp"));
	FlexGridSizer148->Add(TextCtrl_DMX3_Ramp, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	StaticText229 = new wxStaticText(Panel20, wxID_ANY, _("Channel 4:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer148->Add(StaticText229, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX4_Ramp = new wxSlider(Panel20, ID_SLIDER_DMX4_Ramp, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX4_Ramp"));
	FlexGridSizer148->Add(Slider_DMX4_Ramp, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl_DMX4_Ramp = new wxTextCtrl(Panel20, IDD_TEXTCTRL_DMX4_Ramp, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel20,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX4_Ramp"));
	FlexGridSizer148->Add(TextCtrl_DMX4_Ramp, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	StaticText230 = new wxStaticText(Panel20, wxID_ANY, _("Channel 5:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer148->Add(StaticText230, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX5_Ramp = new wxSlider(Panel20, ID_SLIDER_DMX5_Ramp, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX5_Ramp"));
	FlexGridSizer148->Add(Slider_DMX5_Ramp, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl_DMX5_Ramp = new wxTextCtrl(Panel20, IDD_TEXTCTRL_DMX5_Ramp, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel20,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX5_Ramp"));
	FlexGridSizer148->Add(TextCtrl_DMX5_Ramp, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	StaticText231 = new wxStaticText(Panel20, wxID_ANY, _("Channel 6:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer148->Add(StaticText231, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX6_Ramp = new wxSlider(Panel20, ID_SLIDER_DMX6_Ramp, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX6_Ramp"));
	FlexGridSizer148->Add(Slider_DMX6_Ramp, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl_DMX6_Ramp = new wxTextCtrl(Panel20, IDD_TEXTCTRL_DMX6_Ramp, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel20,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX6_Ramp"));
	FlexGridSizer148->Add(TextCtrl_DMX6_Ramp, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	StaticText232 = new wxStaticText(Panel20, wxID_ANY, _("Channel 7:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer148->Add(StaticText232, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX7_Ramp = new wxSlider(Panel20, ID_SLIDER_DMX7_Ramp, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX7_Ramp"));
	FlexGridSizer148->Add(Slider_DMX7_Ramp, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl_DMX7_Ramp = new wxTextCtrl(Panel20, IDD_TEXTCTRL_DMX7_Ramp, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel20,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX7_Ramp"));
	FlexGridSizer148->Add(TextCtrl_DMX7_Ramp, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	StaticText233 = new wxStaticText(Panel20, wxID_ANY, _("Channel 8:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer148->Add(StaticText233, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX8_Ramp = new wxSlider(Panel20, ID_SLIDER_DMX8_Ramp, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX8_Ramp"));
	FlexGridSizer148->Add(Slider_DMX8_Ramp, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl_DMX8_Ramp = new wxTextCtrl(Panel20, IDD_TEXTCTRL_DMX8_Ramp, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel20,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX8_Ramp"));
	FlexGridSizer148->Add(TextCtrl_DMX8_Ramp, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	StaticText234 = new wxStaticText(Panel20, wxID_ANY, _("Channel 9:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer148->Add(StaticText234, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX9_Ramp = new wxSlider(Panel20, ID_SLIDER_DMX9_Ramp, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX9_Ramp"));
	FlexGridSizer148->Add(Slider_DMX9_Ramp, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl_DMX9_Ramp = new wxTextCtrl(Panel20, IDD_TEXTCTRL_DMX9_Ramp, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel20,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX9_Ramp"));
	FlexGridSizer148->Add(TextCtrl_DMX9_Ramp, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	Panel20->SetSizer(FlexGridSizer148);
	FlexGridSizer148->Fit(Panel20);
	FlexGridSizer148->SetSizeHints(Panel20);
	Panel21 = new wxPanel(Notebook7, ID_PANEL49, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL, _T("ID_PANEL49"));
	FlexGridSizer150 = new wxFlexGridSizer(0, 3, 0, 0);
	FlexGridSizer150->AddGrowableCol(1);
	StaticText235 = new wxStaticText(Panel21, wxID_ANY, _("Channel 10:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer150->Add(StaticText235, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX10_Ramp = new wxSlider(Panel21, ID_SLIDER_DMX10_Ramp, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX10_Ramp"));
	FlexGridSizer150->Add(Slider_DMX10_Ramp, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl_DMX10_Ramp = new wxTextCtrl(Panel21, IDD_TEXTCTRL_DMX10_Ramp, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel21,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX10_Ramp"));
	FlexGridSizer150->Add(TextCtrl_DMX10_Ramp, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	StaticText236 = new wxStaticText(Panel21, wxID_ANY, _("Channel 11:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer150->Add(StaticText236, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX11_Ramp = new wxSlider(Panel21, ID_SLIDER_DMX11_Ramp, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX11_Ramp"));
	FlexGridSizer150->Add(Slider_DMX11_Ramp, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl_DMX11_Ramp = new wxTextCtrl(Panel21, IDD_TEXTCTRL_DMX11_Ramp, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel21,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX11_Ramp"));
	FlexGridSizer150->Add(TextCtrl_DMX11_Ramp, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	StaticText237 = new wxStaticText(Panel21, wxID_ANY, _("Channel 12:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer150->Add(StaticText237, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX12_Ramp = new wxSlider(Panel21, ID_SLIDER_DMX12_Ramp, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX12_Ramp"));
	FlexGridSizer150->Add(Slider_DMX12_Ramp, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl_DMX12_Ramp = new wxTextCtrl(Panel21, IDD_TEXTCTRL_DMX12_Ramp, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel21,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX12_Ramp"));
	FlexGridSizer150->Add(TextCtrl_DMX12_Ramp, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	StaticText241 = new wxStaticText(Panel21, wxID_ANY, _("Channel 13:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer150->Add(StaticText241, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX13_Ramp = new wxSlider(Panel21, ID_SLIDER_DMX13_Ramp, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX13_Ramp"));
	FlexGridSizer150->Add(Slider_DMX13_Ramp, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl_DMX13_Ramp = new wxTextCtrl(Panel21, IDD_TEXTCTRL_DMX13_Ramp, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel21,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX13_Ramp"));
	FlexGridSizer150->Add(TextCtrl_DMX13_Ramp, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	StaticText242 = new wxStaticText(Panel21, wxID_ANY, _("Channel 14:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer150->Add(StaticText242, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX14_Ramp = new wxSlider(Panel21, ID_SLIDER_DMX14_Ramp, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX14_Ramp"));
	FlexGridSizer150->Add(Slider_DMX14_Ramp, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl_DMX14_Ramp = new wxTextCtrl(Panel21, IDD_TEXTCTRL_DMX14_Ramp, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel21,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX14_Ramp"));
	FlexGridSizer150->Add(TextCtrl_DMX14_Ramp, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	StaticText243 = new wxStaticText(Panel21, wxID_ANY, _("Channel 15:"), wxDefaultPosition, wxDefaultSize, 0, _T("wxID_ANY"));
	FlexGridSizer150->Add(StaticText243, 1, wxALL|wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 2);
	Slider_DMX15_Ramp = new wxSlider(Panel21, ID_SLIDER_DMX15_Ramp, 0, 0, 255, wxDefaultPosition, wxDefaultSize, 0, wxDefaultValidator, _T("ID_SLIDER_DMX15_Ramp"));
	FlexGridSizer150->Add(Slider_DMX15_Ramp, 1, wxALL|wxEXPAND|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	TextCtrl_DMX15_Ramp = new wxTextCtrl(Panel21, IDD_TEXTCTRL_DMX15_Ramp, _("0"), wxDefaultPosition, wxDLG_UNIT(Panel21,wxSize(20,-1)), wxTE_PROCESS_ENTER, wxDefaultValidator, _T("IDD_TEXTCTRL_DMX15_Ramp"));
	FlexGridSizer150->Add(TextCtrl_DMX15_Ramp, 1, wxALL|wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL, 2);
	Panel21->SetSizer(FlexGridSizer150);
	FlexGridSizer150->Fit(Panel21);
	FlexGridSizer150->SetSizeHints(Panel21);
	Notebook7->AddPage(Panel18, _("Channels 1-9"), false);
	Notebook7->AddPage(Panel19, _("Channels 10-15"), false);
	Notebook7->AddPage(Panel20, _("Ch 1-9 Ramp"), false);
	Notebook7->AddPage(Panel21, _("Ch 10-15 Ramp"), false);
	FlexGridSizer146->Add(Notebook7, 1, wxALL|wxEXPAND|wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 2);
	SetSizer(FlexGridSizer146);
	FlexGridSizer146->Fit(this);
	FlexGridSizer146->SetSizeHints(this);

	Connect(ID_SLIDER_DMX1,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX1,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	Connect(ID_SLIDER_DMX2,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX2,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	Connect(ID_SLIDER_DMX3,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX3,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	Connect(ID_SLIDER_DMX4,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX4,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	Connect(ID_SLIDER_DMX5,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX5,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	Connect(ID_SLIDER_DMX6,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX6,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	Connect(ID_SLIDER_DMX7,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX7,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	Connect(ID_SLIDER_DMX8,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX8,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	Connect(ID_SLIDER_DMX9,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX9,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	Connect(ID_SLIDER_DMX10,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX10,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	Connect(ID_SLIDER_DMX11,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX11,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	Connect(ID_SLIDER_DMX12,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX12,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	Connect(ID_SLIDER_DMX13,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX13,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	Connect(ID_SLIDER_DMX14,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX14,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	Connect(ID_SLIDER_DMX15,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX15,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	Connect(ID_SLIDER_DMX1_Ramp,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX1_Ramp,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	Connect(ID_SLIDER_DMX2_Ramp,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX2_Ramp,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	Connect(ID_SLIDER_DMX3_Ramp,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX3_Ramp,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	Connect(ID_SLIDER_DMX4_Ramp,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX4_Ramp,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	Connect(ID_SLIDER_DMX5_Ramp,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX5_Ramp,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	Connect(ID_SLIDER_DMX6_Ramp,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX6_Ramp,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	Connect(ID_SLIDER_DMX7_Ramp,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX7_Ramp,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	Connect(ID_SLIDER_DMX8_Ramp,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX8_Ramp,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	Connect(ID_SLIDER_DMX9_Ramp,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX9_Ramp,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	Connect(ID_SLIDER_DMX10_Ramp,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX10_Ramp,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	Connect(ID_SLIDER_DMX11_Ramp,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX11_Ramp,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	Connect(ID_SLIDER_DMX12_Ramp,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX12_Ramp,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	Connect(ID_SLIDER_DMX13_Ramp,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX13_Ramp,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	Connect(ID_SLIDER_DMX14_Ramp,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX14_Ramp,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	Connect(ID_SLIDER_DMX15_Ramp,wxEVT_COMMAND_SLIDER_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedTextCtrl);
	Connect(IDD_TEXTCTRL_DMX15_Ramp,wxEVT_COMMAND_TEXT_UPDATED,(wxObjectEventFunction)&DMXPanel::UpdateLinkedSlider);
	//*)
    SetName("ID_PANEL_DMX");
}

DMXPanel::~DMXPanel()
{
	//(*Destroy(DMXPanel)
	//*)
}

PANEL_EVENT_HANDLERS(DMXPanel)