//
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#pragma once
#include <stdint.h>

#if !defined(__cplusplus)
#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L)
#include <stdbool.h>
#else
typedef int bool;
#endif
#endif



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus
///////////////////////////////////////////////////////////////////////////
// Vector types with external visibility from ispc code
///////////////////////////////////////////////////////////////////////////

#ifndef __ISPC_VECTOR_uint8_t4__
#define __ISPC_VECTOR_uint8_t4__
#ifdef _MSC_VER
__declspec( align(4) ) struct uint8_t4 { uint8_t v[4]; };
#else
struct uint8_t4 { uint8_t v[4]; } __attribute__ ((aligned(4)));
#endif
#endif



/* Portable alignment macro that works across different compilers and standards */
#if defined(__cplusplus) && __cplusplus >= 201103L
/* C++11 or newer - use alignas keyword */
#define __ISPC_ALIGN__(x) alignas(x)
#elif defined(__GNUC__) || defined(__clang__)
/* GCC or Clang - use __attribute__ */
#define __ISPC_ALIGN__(x) __attribute__((aligned(x)))
#elif defined(_MSC_VER)
/* Microsoft Visual C++ - use __declspec */
#define __ISPC_ALIGN__(x) __declspec(align(x))
#else
/* Unknown compiler/standard - alignment not supported */
#define __ISPC_ALIGN__(x)
#warning "Alignment not supported on this compiler"
#endif // defined(__cplusplus) && __cplusplus >= 201103L
#ifndef __ISPC_ALIGNED_STRUCT__
#if defined(__clang__) || !defined(_MSC_VER)
// Clang, GCC, ICC
#define __ISPC_ALIGNED_STRUCT__(s) struct __ISPC_ALIGN__(s)
#else
// Visual Studio
#define __ISPC_ALIGNED_STRUCT__(s) __ISPC_ALIGN__(s) struct
#endif // defined(__clang__) || !defined(_MSC_VER)
#endif // __ISPC_ALIGNED_STRUCT__

#ifndef __ISPC_STRUCT_ButterflyData__
#define __ISPC_STRUCT_ButterflyData__
struct ButterflyData {
    uint8_t4  colors[8];
    float offset;
    int32_t chunks;
    int32_t skip;
    int32_t curState;
    uint16_t colorScheme;
    uint16_t width;
    uint16_t height;
    uint16_t numColors;
    float plasmaTime;
    int32_t plasmaStyle;
};
#endif


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
extern "C" {
#endif // __cplusplus
#if defined(__cplusplus)
    extern void ButterflyEffectPlasmaStyles(const struct ButterflyData &data, int32_t startIdx, int32_t endIdx, uint8_t4   * result);
#else
    extern void ButterflyEffectPlasmaStyles(const struct ButterflyData *data, int32_t startIdx, int32_t endIdx, uint8_t4   * result);
#endif // ButterflyEffectPlasmaStyles function declaraion
#if defined(__cplusplus)
    extern void ButterflyEffectStyle1(const struct ButterflyData &data, int32_t startIdx, int32_t endIdx, uint8_t4   * result);
#else
    extern void ButterflyEffectStyle1(const struct ButterflyData *data, int32_t startIdx, int32_t endIdx, uint8_t4   * result);
#endif // ButterflyEffectStyle1 function declaraion
#if defined(__cplusplus)
    extern void ButterflyEffectStyle2(const struct ButterflyData &data, int32_t startIdx, int32_t endIdx, uint8_t4   * result);
#else
    extern void ButterflyEffectStyle2(const struct ButterflyData *data, int32_t startIdx, int32_t endIdx, uint8_t4   * result);
#endif // ButterflyEffectStyle2 function declaraion
#if defined(__cplusplus)
    extern void ButterflyEffectStyle3(const struct ButterflyData &data, int32_t startIdx, int32_t endIdx, uint8_t4   * result);
#else
    extern void ButterflyEffectStyle3(const struct ButterflyData *data, int32_t startIdx, int32_t endIdx, uint8_t4   * result);
#endif // ButterflyEffectStyle3 function declaraion
#if defined(__cplusplus)
    extern void ButterflyEffectStyle4(const struct ButterflyData &data, int32_t startIdx, int32_t endIdx, uint8_t4   * result);
#else
    extern void ButterflyEffectStyle4(const struct ButterflyData *data, int32_t startIdx, int32_t endIdx, uint8_t4   * result);
#endif // ButterflyEffectStyle4 function declaraion
#if defined(__cplusplus)
    extern void ButterflyEffectStyle5(const struct ButterflyData &data, int32_t startIdx, int32_t endIdx, uint8_t4   * result);
#else
    extern void ButterflyEffectStyle5(const struct ButterflyData *data, int32_t startIdx, int32_t endIdx, uint8_t4   * result);
#endif // ButterflyEffectStyle5 function declaraion
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus
