# bars.bat
mkdir "01 - Carol of the Bells"
gawk -f bars4.awk -v filename="01 - Carol of the Bells_bars.txt" "01 - Carol of the Bells_bars.txt"
move /Y "01 - Carol of the Bells*.*" "01 - Carol of the Bells"
mkdir "01 - Joy To The World"
gawk -f bars4.awk -v filename="01 - Joy To The World_bars.txt" "01 - Joy To The World_bars.txt"
move /Y "01 - Joy To The World*.*" "01 - Joy To The World"
mkdir "01 - The House On Christmas Street"
gawk -f bars4.awk -v filename="01 - The House On Christmas Street_bars.txt" "01 - The House On Christmas Street_bars.txt"
move /Y "01 - The House On Christmas Street*.*" "01 - The House On Christmas Street"
mkdir "01-01- Disneys Electrical Parade (Original Version)"
gawk -f bars4.awk -v filename="01-01- Disneys Electrical Parade (Original Version)_bars.txt" "01-01- Disneys Electrical Parade (Original Version)_bars.txt"
move /Y "01-01- Disneys Electrical Parade (Original Version)*.*" "01-01- Disneys Electrical Parade (Original Version)"
mkdir "01-01- Its Beginning To Look A Lot Like Christmas"
gawk -f bars4.awk -v filename="01-01- Its Beginning To Look A Lot Like Christmas_bars.txt" "01-01- Its Beginning To Look A Lot Like Christmas_bars.txt"
move /Y "01-01- Its Beginning To Look A Lot Like Christmas*.*" "01-01- Its Beginning To Look A Lot Like Christmas"
mkdir "01-01- Sandstorm (Radio Edit)"
gawk -f bars4.awk -v filename="01-01- Sandstorm (Radio Edit)_bars.txt" "01-01- Sandstorm (Radio Edit)_bars.txt"
move /Y "01-01- Sandstorm (Radio Edit)*.*" "01-01- Sandstorm (Radio Edit)"
mkdir "01-01- The Fox (What Does The Fox Say)"
gawk -f bars4.awk -v filename="01-01- The Fox (What Does The Fox Say)_bars.txt" "01-01- The Fox (What Does The Fox Say)_bars.txt"
move /Y "01-01- The Fox (What Does The Fox Say)*.*" "01-01- The Fox (What Does The Fox Say)"
mkdir "01-02- The Christmas Song (Merry Christmas To You)"
gawk -f bars4.awk -v filename="01-02- The Christmas Song (Merry Christmas To You)_bars.txt" "01-02- The Christmas Song (Merry Christmas To You)_bars.txt"
move /Y "01-02- The Christmas Song (Merry Christmas To You)*.*" "01-02- The Christmas Song (Merry Christmas To You)"
mkdir "01-03- (It Mustve Been Ol) Santa Claus"
gawk -f bars4.awk -v filename="01-03- (It Mustve Been Ol) Santa Claus_bars.txt" "01-03- (It Mustve Been Ol) Santa Claus_bars.txt"
move /Y "01-03- (It Mustve Been Ol) Santa Claus*.*" "01-03- (It Mustve Been Ol) Santa Claus"
mkdir "01-03- Carol Of The Bells"
gawk -f bars4.awk -v filename="01-03- Carol Of The Bells_bars.txt" "01-03- Carol Of The Bells_bars.txt"
move /Y "01-03- Carol Of The Bells*.*" "01-03- Carol Of The Bells"
mkdir "01-04- Its The Most Wonderful Time Of The Year"
gawk -f bars4.awk -v filename="01-04- Its The Most Wonderful Time Of The Year_bars.txt" "01-04- Its The Most Wonderful Time Of The Year_bars.txt"
move /Y "01-04- Its The Most Wonderful Time Of The Year*.*" "01-04- Its The Most Wonderful Time Of The Year"
mkdir "01-04- Linus And Lucy"
gawk -f bars4.awk -v filename="01-04- Linus And Lucy_bars.txt" "01-04- Linus And Lucy_bars.txt"
move /Y "01-04- Linus And Lucy*.*" "01-04- Linus And Lucy"
mkdir "01-04- Pour Elise (State Of Trance Remix)"
gawk -f bars4.awk -v filename="01-04- Pour Elise (State Of Trance Remix)_bars.txt" "01-04- Pour Elise (State Of Trance Remix)_bars.txt"
move /Y "01-04- Pour Elise (State Of Trance Remix)*.*" "01-04- Pour Elise (State Of Trance Remix)"
mkdir "01-04- Sleigh Ride (Album Version)"
gawk -f bars4.awk -v filename="01-04- Sleigh Ride (Album Version)_bars.txt" "01-04- Sleigh Ride (Album Version)_bars.txt"
move /Y "01-04- Sleigh Ride (Album Version)*.*" "01-04- Sleigh Ride (Album Version)"
mkdir "01-06- 12 Days of Christmas"
gawk -f bars4.awk -v filename="01-06- 12 Days of Christmas_bars.txt" "01-06- 12 Days of Christmas_bars.txt"
move /Y "01-06- 12 Days of Christmas*.*" "01-06- 12 Days of Christmas"
mkdir "01-06- Have Yourself A Merry Little Christmas (1999 - Remaster)"
gawk -f bars4.awk -v filename="01-06- Have Yourself A Merry Little Christmas (1999 - Remaster)_bars.txt" "01-06- Have Yourself A Merry Little Christmas (1999 - Remaster)_bars.txt"
move /Y "01-06- Have Yourself A Merry Little Christmas (1999 - Remaster)*.*" "01-06- Have Yourself A Merry Little Christmas (1999 - Remaster)"
mkdir "01-07- Let it snow! Let it snow! Let it snow!"
gawk -f bars4.awk -v filename="01-07- Let it snow! Let it snow! Let it snow!_bars.txt" "01-07- Let it snow! Let it snow! Let it snow!_bars.txt"
move /Y "01-07- Let it snow! Let it snow! Let it snow!*.*" "01-07- Let it snow! Let it snow! Let it snow!"
mkdir "01-12- Sleigh Ride (2004 Digital Remaster)"
gawk -f bars4.awk -v filename="01-12- Sleigh Ride (2004 Digital Remaster)_bars.txt" "01-12- Sleigh Ride (2004 Digital Remaster)_bars.txt"
move /Y "01-12- Sleigh Ride (2004 Digital Remaster)*.*" "01-12- Sleigh Ride (2004 Digital Remaster)"
mkdir "01-15- The 12 Days Of Christmas"
gawk -f bars4.awk -v filename="01-15- The 12 Days Of Christmas_bars.txt" "01-15- The 12 Days Of Christmas_bars.txt"
move /Y "01-15- The 12 Days Of Christmas*.*" "01-15- The 12 Days Of Christmas"
mkdir "02 - Music Box Dancer (Radio Version)"
gawk -f bars4.awk -v filename="02 - Music Box Dancer (Radio Version)_bars.txt" "02 - Music Box Dancer (Radio Version)_bars.txt"
move /Y "02 - Music Box Dancer (Radio Version)*.*" "02 - Music Box Dancer (Radio Version)"
mkdir "04 - Baby, It's Cold Outside (Glee Cast Version)"
gawk -f bars4.awk -v filename="04 - Baby, It's Cold Outside (Glee Cast Version)_bars.txt" "04 - Baby, It's Cold Outside (Glee Cast Version)_bars.txt"
move /Y "04 - Baby, It's Cold Outside (Glee Cast Version)*.*" "04 - Baby, It's Cold Outside (Glee Cast Version)"
mkdir "04 - White Christmas (Duet With Shania Twain)"
gawk -f bars4.awk -v filename="04 - White Christmas (Duet With Shania Twain)_bars.txt" "04 - White Christmas (Duet With Shania Twain)_bars.txt"
move /Y "04 - White Christmas (Duet With Shania Twain)*.*" "04 - White Christmas (Duet With Shania Twain)"
mkdir "04 - Wizards In Winter (Instrumental)"
gawk -f bars4.awk -v filename="04 - Wizards In Winter (Instrumental)_bars.txt" "04 - Wizards In Winter (Instrumental)_bars.txt"
move /Y "04 - Wizards In Winter (Instrumental)*.*" "04 - Wizards In Winter (Instrumental)"
mkdir "04 - You're A Mean One, Mr. Grinch"
gawk -f bars4.awk -v filename="04 - You're A Mean One, Mr. Grinch_bars.txt" "04 - You're A Mean One, Mr. Grinch_bars.txt"
move /Y "04 - You're A Mean One, Mr. Grinch*.*" "04 - You're A Mean One, Mr. Grinch"
mkdir "06 - A Mad Russian's Christmas (Instrumental)"
gawk -f bars4.awk -v filename="06 - A Mad Russian's Christmas (Instrumental)_bars.txt" "06 - A Mad Russian's Christmas (Instrumental)_bars.txt"
move /Y "06 - A Mad Russian's Christmas (Instrumental)*.*" "06 - A Mad Russian's Christmas (Instrumental)"
mkdir "07 - Amazing Grace (2008 Party Version)"
gawk -f bars4.awk -v filename="07 - Amazing Grace (2008 Party Version)_bars.txt" "07 - Amazing Grace (2008 Party Version)_bars.txt"
move /Y "07 - Amazing Grace (2008 Party Version)*.*" "07 - Amazing Grace (2008 Party Version)"
mkdir "08 - Christmas Canon"
gawk -f bars4.awk -v filename="08 - Christmas Canon_bars.txt" "08 - Christmas Canon_bars.txt"
move /Y "08 - Christmas Canon*.*" "08 - Christmas Canon"
mkdir "08 - Christmas Song (Chestnuts Roasting On An Open Fire)"
gawk -f bars4.awk -v filename="08 - Christmas Song (Chestnuts Roasting On An Open Fire)_bars.txt" "08 - Christmas Song (Chestnuts Roasting On An Open Fire)_bars.txt"
move /Y "08 - Christmas Song (Chestnuts Roasting On An Open Fire)*.*" "08 - Christmas Song (Chestnuts Roasting On An Open Fire)"
mkdir "08 - Christmas_ Sarajevo 12_24 (Instrumental)"
gawk -f bars4.awk -v filename="08 - Christmas_ Sarajevo 12_24 (Instrumental)_bars.txt" "08 - Christmas_ Sarajevo 12_24 (Instrumental)_bars.txt"
move /Y "08 - Christmas_ Sarajevo 12_24 (Instrumental)*.*" "08 - Christmas_ Sarajevo 12_24 (Instrumental)"
mkdir "08 - Queen Of The Winter Night (Album Version)"
gawk -f bars4.awk -v filename="08 - Queen Of The Winter Night (Album Version)_bars.txt" "08 - Queen Of The Winter Night (Album Version)_bars.txt"
move /Y "08 - Queen Of The Winter Night (Album Version)*.*" "08 - Queen Of The Winter Night (Album Version)"
mkdir "09 - Carol Of The Bells (Instrumental)"
gawk -f bars4.awk -v filename="09 - Carol Of The Bells (Instrumental)_bars.txt" "09 - Carol Of The Bells (Instrumental)_bars.txt"
move /Y "09 - Carol Of The Bells (Instrumental)*.*" "09 - Carol Of The Bells (Instrumental)"
mkdir "09 - Overture From Miracle On 34th Street"
gawk -f bars4.awk -v filename="09 - Overture From Miracle On 34th Street_bars.txt" "09 - Overture From Miracle On 34th Street_bars.txt"
move /Y "09 - Overture From Miracle On 34th Street*.*" "09 - Overture From Miracle On 34th Street"
mkdir "12 - All I Want For Christmas Is You"
gawk -f bars4.awk -v filename="12 - All I Want For Christmas Is You_bars.txt" "12 - All I Want For Christmas Is You_bars.txt"
move /Y "12 - All I Want For Christmas Is You*.*" "12 - All I Want For Christmas Is You"
mkdir "21 - Christmas Canon Rock"
gawk -f bars4.awk -v filename="21 - Christmas Canon Rock_bars.txt" "21 - Christmas Canon Rock_bars.txt"
move /Y "21 - Christmas Canon Rock*.*" "21 - Christmas Canon Rock"
mkdir "24 - Nutrocker"
gawk -f bars4.awk -v filename="24 - Nutrocker_bars.txt" "24 - Nutrocker_bars.txt"
move /Y "24 - Nutrocker*.*" "24 - Nutrocker"
mkdir "Do You Hear What I Hear"
gawk -f bars4.awk -v filename="Do You Hear What I Hear_bars.txt" "Do You Hear What I Hear_bars.txt"
move /Y "Do You Hear What I Hear*.*" "Do You Hear What I Hear"
mkdir "Snow Miser - Heat Miser"
gawk -f bars4.awk -v filename="Snow Miser - Heat Miser_bars.txt" "Snow Miser - Heat Miser_bars.txt"
move /Y "Snow Miser - Heat Miser*.*" "Snow Miser - Heat Miser"
