<#
.SYNOPSIS
    Build (and optionally sign) an xLights MSIX package from existing Windows
    build outputs.

.DESCRIPTION
    Packages the same files the Inno installer ships (see
    build_scripts/msw/xLights_4_64bit_VS.iss) into an MSIX using the Windows SDK
    MakeAppx tool. A mapping file references the build outputs in place, so no
    multi-GB copy of the tree is made.

    Two things differ from the classic installer and are handled here:
      * The VC++ redistributable cannot be run inside a package, so the VC
        runtime DLLs are bundled app-locally (see -SkipVCRuntime / -VCRedistDir).
      * File associations and the app icon move into the manifest (assets are
        generated by GenerateAssets.ps1).

    Identity: for a sideload / nightly build the Publisher MUST match the signing
    certificate subject; for a Store build use the Partner-Center-reserved Name
    and the "CN=<GUID>" Publisher (the Store re-signs). See README.md.

.PARAMETER Version
    4-part Major.Minor.Build.Revision. Defaults to the Year/Version parsed from
    xLights_common.iss with Build/Revision = the numeric "Other" suffix / 0.
    For nightlies pass a monotonically increasing Revision (e.g. a run number).

.PARAMETER SelfSign
    Mint a self-signed code-signing cert whose subject == -Publisher and sign the
    package with it. For LOCAL sideload testing only. Combine with -InstallCert
    (admin) to trust it so the package installs.

.EXAMPLE
    # Local sideload test build, self-signed and trusted:
    pwsh -File BuildMSIX.ps1 -SelfSign -InstallCert

.EXAMPLE
    # CI: produce an unsigned package; Trusted Signing signs the .msix afterward.
    pwsh -File BuildMSIX.ps1 -Version 2026.11.1.20260629 -OutFile xLights-x64.msix
#>
[CmdletBinding()]
param(
    [ValidateSet('VS', 'CMake')]
    [string]$Layout = 'VS',

    # Build the Microsoft Store variant: uses the Partner Center-reserved identity
    # and leaves the package UNSIGNED (the Store re-signs on ingestion). Overrides
    # -IdentityName/-Publisher/-PublisherDisplayName and forces the revision to 0.
    [switch]$Store,

    [string]$Version,

    # Used only when -Version isn't given: sets the 4th (Revision) component.
    # CI passes a monotonically increasing number (e.g. the workflow run number)
    # so App Installer detects each nightly as newer.
    [int]$Revision = 0,

    # Identity. Sideload defaults; override for Store builds. Empty values fall
    # back to the defaults (so CI can pass through unset repo variables).
    [string]$IdentityName        = 'KulpLightsLLC.xLights',
    # Must match the Azure Trusted Signing (kulplights-public) cert subject exactly.
    [string]$Publisher           = 'CN=Kulp Lights LLC, O=Kulp Lights LLC, L=Framingham, S=Massachusetts, C=US',
    [string]$PublisherDisplayName = 'Kulp Lights LLC',
    [string]$DisplayName         = 'xLights',

    [string]$OutDir,
    [string]$OutFile,

    # VC++ runtime DLLs to bundle (VC_redist.exe can't run inside a package).
    [switch]$SkipVCRuntime,
    [string]$VCRedistDir,

    # Tools (auto-detected from the latest Windows SDK if not given).
    [string]$SdkBinDir,

    # Signing.
    [switch]$SelfSign,
    [switch]$InstallCert,
    [string]$CertThumbprint,
    [string]$TimestampUrl = 'http://timestamp.acs.microsoft.com'
)

$ErrorActionPreference = 'Stop'
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repo      = (Resolve-Path (Join-Path $scriptDir '..\..\..')).Path
$mswDir    = (Resolve-Path (Join-Path $scriptDir '..')).Path

if (-not $OutDir)  { $OutDir = Join-Path $mswDir 'output' }
New-Item -ItemType Directory -Force -Path $OutDir | Out-Null

# ---------------------------------------------------------------------------
# Microsoft Store variant identity (from the Partner Center reservation)
# ---------------------------------------------------------------------------
if ($Store) {
    $IdentityName         = 'KulpLightsLLC.xLights'
    $Publisher            = 'CN=1FED2C12-F7F6-45DF-A649-E647058AAA5F'
    $PublisherDisplayName = 'Kulp Lights LLC'
    $Revision             = 0   # the Store reserves the revision component; it must be 0
    if ($SelfSign -or $CertThumbprint) {
        Write-Warning "Store packages are submitted unsigned (the Store re-signs); ignoring signing options."
    }
    $SelfSign = $false
    $CertThumbprint = $null
    if (-not $OutFile) { $OutFile = 'xLights-Store-x64.msix' }
}

# ---------------------------------------------------------------------------
# Locate Windows SDK tools (makeappx, signtool)
# ---------------------------------------------------------------------------
function Find-SdkTool([string]$name) {
    if ($SdkBinDir) {
        $p = Join-Path $SdkBinDir $name
        if (Test-Path $p) { return $p }
    }
    $cmd = Get-Command $name -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }
    $roots = @("${env:ProgramFiles(x86)}\Windows Kits\10\bin", "$env:ProgramFiles\Windows Kits\10\bin")
    foreach ($root in $roots) {
        if (Test-Path $root) {
            $hit = Get-ChildItem -Path $root -Recurse -Filter $name -ErrorAction SilentlyContinue |
                Where-Object { $_.FullName -match '\\x64\\' } |
                Sort-Object FullName -Descending | Select-Object -First 1
            if ($hit) { return $hit.FullName }
        }
    }
    throw "Could not find $name. Install the Windows SDK or pass -SdkBinDir."
}

$makeappx = Find-SdkTool 'makeappx.exe'
Write-Host "makeappx : $makeappx"

# ---------------------------------------------------------------------------
# Version
# ---------------------------------------------------------------------------
if (-not $Version) {
    $commonIss = Get-Content (Join-Path $mswDir 'xLights_common.iss') -Raw
    $year  = [int]([regex]::Match($commonIss, '(?m)^\s*#define\s+Year\s+(\d+)').Groups[1].Value)
    $minor = [int]([regex]::Match($commonIss, '(?m)^\s*#define\s+Version\s+(\d+)').Groups[1].Value)
    $other = [regex]::Match($commonIss, '(?m)^\s*#define\s+Other\s+"([^"]*)"').Groups[1].Value
    # Only a clean "_N" suffix is a build number; a nightly's "_nightly-<sha>" is not.
    $build = 0
    $m = [regex]::Match($other, '^_(\d+)$')
    if ($m.Success) { $build = [int]$m.Groups[1].Value }
    $Version = "$year.$minor.$build.$Revision"
}
if ($Version -notmatch '^\d+\.\d+\.\d+\.\d+$') {
    throw "Version must be 4-part numeric Major.Minor.Build.Revision (got '$Version')."
}

# Empty identity values fall back to defaults (lets CI pass unset repo variables).
if ([string]::IsNullOrWhiteSpace($IdentityName))         { $IdentityName = 'KulpLightsLLC.xLights' }
if ([string]::IsNullOrWhiteSpace($PublisherDisplayName)) { $PublisherDisplayName = 'Kulp Lights LLC' }
if ([string]::IsNullOrWhiteSpace($DisplayName))          { $DisplayName = 'xLights' }
if ([string]::IsNullOrWhiteSpace($Publisher))            { $Publisher = 'CN=Kulp Lights LLC, O=Kulp Lights LLC, L=Framingham, S=Massachusetts, C=US' }
Write-Host "Version  : $Version"
Write-Host "Identity : $IdentityName  Publisher: $Publisher"

if (-not $OutFile) { $OutFile = "xLights-$Version-x64.msix" }
$outPath = Join-Path $OutDir $OutFile

# Record the resolved version so the .appinstaller step can reuse it verbatim.
[System.IO.File]::WriteAllText((Join-Path $OutDir 'msix_version.txt'), $Version, (New-Object System.Text.UTF8Encoding($false)))

# ---------------------------------------------------------------------------
# Generate the manifest from the template
# ---------------------------------------------------------------------------
$manifestTemplate = Get-Content (Join-Path $scriptDir 'AppxManifest.template.xml') -Raw
$manifest = $manifestTemplate `
    -replace '\{\{IDENTITY_NAME\}\}',          [regex]::Escape($IdentityName).Replace('\','') `
    -replace '\{\{PUBLISHER\}\}',              $Publisher `
    -replace '\{\{PUBLISHER_DISPLAY_NAME\}\}', $PublisherDisplayName `
    -replace '\{\{VERSION\}\}',                $Version `
    -replace '\{\{DISPLAY_NAME\}\}',           $DisplayName
$manifestPath = Join-Path $OutDir 'AppxManifest.xml'
# UTF-8 without BOM (MakeAppx rejects a BOM on the manifest).
[System.IO.File]::WriteAllText($manifestPath, $manifest, (New-Object System.Text.UTF8Encoding($false)))

# ---------------------------------------------------------------------------
# Assets (regenerate if missing)
# ---------------------------------------------------------------------------
$assetsDir = Join-Path $scriptDir 'Assets'
if (-not (Test-Path (Join-Path $assetsDir 'Square150x150Logo.png'))) {
    Write-Host "Assets missing - running GenerateAssets.ps1"
    & (Join-Path $scriptDir 'GenerateAssets.ps1')
}

# ---------------------------------------------------------------------------
# Build the file map (Src -> Dest-in-package), mirroring the .iss inventory
# ---------------------------------------------------------------------------
$files = [System.Collections.Generic.List[object]]::new()
function Add-File([string]$src, [string]$dest, [switch]$Optional) {
    $full = Join-Path $repo $src
    if (-not (Test-Path $full)) {
        if ($Optional) { Write-Warning "skip (missing): $src"; return }
        throw "Required file not found: $full"
    }
    $files.Add([pscustomobject]@{ Src = (Resolve-Path $full).Path; Dest = $dest })
}
function Add-Glob([string]$srcGlob, [string]$destDir, [switch]$Optional) {
    $items = Get-ChildItem -Path (Join-Path $repo $srcGlob) -File -ErrorAction SilentlyContinue
    if (-not $items) { if (-not $Optional) { throw "No files matched: $srcGlob" }; return }
    foreach ($it in $items) { $files.Add([pscustomobject]@{ Src = $it.FullName; Dest = (Join-Path $destDir $it.Name) }) }
}
function Add-Dir([string]$srcDir, [string]$destDir, [switch]$Optional) {
    $base = Join-Path $repo $srcDir
    if (-not (Test-Path $base)) { if (-not $Optional) { throw "Dir not found: $base" }; return }
    $base = (Resolve-Path $base).Path
    Get-ChildItem -Path $base -Recurse -File | ForEach-Object {
        $rel = $_.FullName.Substring($base.Length).TrimStart('\')
        $files.Add([pscustomobject]@{ Src = $_.FullName; Dest = (Join-Path $destDir $rel) })
    }
}

if ($Layout -eq 'VS') {
    Add-File 'xlights/x64/Release/xLights.exe'              'xLights.exe'
    Add-File 'xlDo/x64/Release/xlDo.exe'                    'xlDo.exe'              -Optional
    Add-File 'fseq_convert/cmake_vs/Release/fseq_convert.exe' 'fseq_convert.exe'   -Optional
    Add-File 'bin/special.options'                          'special.options'      -Optional

    # Runtime DLLs (exact set the installer ships).
    $bin64dlls = @(
        'libgcc_s_seh-1.dll',
        'avcodec-60.dll','avdevice-60.dll','avfilter-9.dll','avformat-60.dll',
        'avutil-58.dll','postproc-57.dll','swresample-4.dll','swscale-7.dll',
        'SDL2.dll','libcurl-x64.dll','hidapi.dll','onnxruntime.dll','klightmapper.dll'
    )
    foreach ($d in $bin64dlls) { Add-File "bin64/$d" $d }
    # Vamp plugins are intentionally NOT bundled. The Vamp Plugin Pack is
    # GPL/AGPL; rather than redistribute it, xLights directs the user to install
    # the official pack on their own machine (DownloadVamp in wxUtilities.cpp) and
    # finds it via VAMP_PATH (default %ProgramFiles%\Vamp Plugins, plus a per-user
    # location for Store installs). Keeping the package free of GPL/AGPL plugin
    # binaries also keeps the MSIX clean for the Microsoft Store.
} else {
    # CMake/Ninja: bin\ holds the exe + all runtime DLLs (mirrors /DCMAKEBUILD).
    Add-Dir 'bin' '' # resources excluded below are re-added from resources\ for both layouts
}

# Icons, docs, license, readme (common to both layouts).
Add-File 'include/xlights64.ico'            'xlights64.ico'
Add-File 'include/xLights_nutcracker.ico'   'xLights_nutcracker.ico'
Add-File 'documentation/xlDo Commands.txt'  'xlDo Commands.txt'  -Optional
Add-File 'License.txt'                      'License.txt'
Add-File 'README.txt'                       'README.txt'
Add-File 'bin/german_dictionary'            'german_dictionary'  -Optional

# Resource folders (single source of truth in resources\, like the .iss).
Add-Dir 'resources/dictionaries'   'dictionaries'
Add-Dir 'resources/effectmetadata' 'effectmetadata'
Add-Dir 'resources/controllers'    'controllers'
Add-Dir 'resources/prompts'        'prompts'
Add-Dir 'resources/html'           'html'
Add-Dir 'resources/colorcurves'    'colorcurves'
Add-Dir 'resources/valuecurves'    'valuecurves'
Add-Dir 'resources/meshobjects'    'meshobjects'
Add-Dir 'resources/mhpresets'      'mhpresets'
Add-Dir 'resources/palettes'       'palettes'

# ---------------------------------------------------------------------------
# VC++ runtime DLLs (app-local; replaces VC_redist.exe)
# ---------------------------------------------------------------------------
if (-not $SkipVCRuntime) {
    if (-not $VCRedistDir) {
        $search = @()
        if ($env:VCToolsRedistDir) { $search += (Join-Path $env:VCToolsRedistDir 'x64') }
        $search += Get-ChildItem -Path "$env:ProgramFiles\Microsoft Visual Studio","${env:ProgramFiles(x86)}\Microsoft Visual Studio" `
            -Directory -ErrorAction SilentlyContinue | ForEach-Object {
                Get-ChildItem -Path "$($_.FullName)\*\VC\Redist\MSVC\*\x64" -Directory -ErrorAction SilentlyContinue
            } | ForEach-Object { $_.FullName }
        foreach ($s in $search) {
            $crt = Get-ChildItem -Path $s -Directory -Filter 'Microsoft.VC*.CRT' -ErrorAction SilentlyContinue |
                Sort-Object Name -Descending | Select-Object -First 1
            if ($crt) { $VCRedistDir = $crt.FullName; break }
        }
    }
    if ($VCRedistDir -and (Test-Path $VCRedistDir)) {
        Write-Host "VC runtime: $VCRedistDir"
        Get-ChildItem -Path $VCRedistDir -Filter '*.dll' | ForEach-Object {
            $files.Add([pscustomobject]@{ Src = $_.FullName; Dest = $_.Name })
        }
    } else {
        Write-Warning "VC runtime redist DLLs not found - package may fail to launch. Pass -VCRedistDir or -SkipVCRuntime to silence."
    }
}

# Assets + manifest.
Add-Dir (Join-Path 'build_scripts/msw/msix' 'Assets') 'Assets'
$files.Add([pscustomobject]@{ Src = $manifestPath; Dest = 'AppxManifest.xml' })

# ---------------------------------------------------------------------------
# Write the mapping file and pack
# ---------------------------------------------------------------------------
$mappingPath = Join-Path $OutDir 'msix_mapping.txt'
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('[Files]')
foreach ($f in $files) { [void]$sb.AppendLine(('"{0}" "{1}"' -f $f.Src, $f.Dest)) }
[System.IO.File]::WriteAllText($mappingPath, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Mapped $($files.Count) files -> $mappingPath"

if (Test-Path $outPath) { Remove-Item $outPath -Force }
Write-Host "Packing  : $outPath"
& $makeappx pack /o /f $mappingPath /p $outPath
if ($LASTEXITCODE -ne 0) { throw "makeappx failed ($LASTEXITCODE)" }

# ---------------------------------------------------------------------------
# Sign (optional)
# ---------------------------------------------------------------------------
if ($SelfSign -or $CertThumbprint) {
    $signtool = Find-SdkTool 'signtool.exe'
    if ($SelfSign) {
        $existing = Get-ChildItem Cert:\CurrentUser\My | Where-Object { $_.Subject -eq $Publisher } | Select-Object -First 1
        if (-not $existing) {
            Write-Host "Creating self-signed cert: $Publisher"
            $existing = New-SelfSignedCertificate -Type CodeSigningCert -Subject $Publisher `
                -KeyUsage DigitalSignature -FriendlyName 'xLights MSIX test (self-signed)' `
                -CertStoreLocation Cert:\CurrentUser\My `
                -TextExtension @('2.5.29.37={text}1.3.6.1.5.5.7.3.3', '2.5.29.19={text}')
        }
        $CertThumbprint = $existing.Thumbprint
        if ($InstallCert) {
            Write-Host "Trusting cert in LocalMachine\TrustedPeople (needs admin)"
            $cerPath = Join-Path $OutDir 'xLights-msix-test.cer'
            Export-Certificate -Cert $existing -FilePath $cerPath | Out-Null
            Import-Certificate -FilePath $cerPath -CertStoreLocation Cert:\LocalMachine\TrustedPeople | Out-Null
        }
    }
    Write-Host "Signing  : $outPath (thumbprint $CertThumbprint)"
    & $signtool sign /fd SHA256 /sha1 $CertThumbprint /tr $TimestampUrl /td SHA256 $outPath
    if ($LASTEXITCODE -ne 0) { throw "signtool failed ($LASTEXITCODE)" }
} elseif ($Store) {
    Write-Host "NOTE: Store package left UNSIGNED by design - upload to Partner Center and the Store re-signs it."
} else {
    Write-Host "NOTE: package left UNSIGNED. CI signs via Azure Trusted Signing; for local install use -SelfSign -InstallCert."
}

Write-Host ""
Write-Host "Done: $outPath"
