name: Ubuntu CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/*.yml'
      - '.github/ISSUE_TEMPLATE/*.md'
      - 'build_scripts/**'
      - 'cmudict/**'
      - 'documentation/**'
      - 'download/**'
      - 'resources/**'
      - 'lib/windows/**'
      - 'lib/windows64/**'
      - 'songs/**'
      - 'TipOfDay/**'
      - '*.md'
      - '*.yml'
      - '*.txt'
      - '*.docx'
      - 'README.*'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/*.yml'
      - '.github/ISSUE_TEMPLATE/*.md'
      - 'build_scripts/**'
      - 'cmudict/**'
      - 'documentation/**'
      - 'download/**'
      - 'resources/**'
      - 'songs/**'
      - 'TipOfDay/**'
      - '*.md'
      - '*.yml'
      - '*.txt'
      - '*.docx'
      - 'README.*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-24.04

    container:
      image: ghcr.io/xlightssequencer/xlights-build-docker:master

    steps:
    - uses: actions/checkout@v4
      with:
          submodules: 'true'
    - name: Make
      run: make -j $(nproc)
