name: Windows xLights CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/*.yml'
      - '.github/ISSUE_TEMPLATE/*.md'
      - 'build_scripts/**'
      - 'ci_scripts/**'
      - 'cmudict/**'
      - 'documentation/**'
      - 'download/**'
      - 'resources/**'
      - 'lib/windows/**'
      - 'lib/windows64/**'
      - 'songs/**'
      - 'TipOfDay/**'
      - 'xlDo/**'
      - '*.md'
      - '*.yml'
      - '*.txt'
      - '*.docx'
      - 'README.*'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/*.yml'
      - '.github/ISSUE_TEMPLATE/*.md'
      - 'build_scripts/**'
      - 'ci_scripts/**'
      - 'cmudict/**'
      - 'documentation/**'
      - 'download/**'
      - 'resources/**'
      - 'songs/**'
      - 'TipOfDay/**'
      - 'xlDo/**'
      - '*.md'
      - '*.yml'
      - '*.txt'
      - '*.docx'
      - 'README.*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:

  call-workflow:
    uses: xLightsSequencer/xLights/.github/workflows/wx_win.yml@master
  build:
    runs-on: windows-2022
    
    env:
      WX_VERSION: xlights_2026.04
    
    steps:
    - name: Checkout xLights
      uses: actions/checkout@master
      with:
          submodules: 'true'
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1
      
    - name: install ISPC
      uses: ispc/install-ispc-action@main
      with:
        version: 1.30.0
        
    - name: Cache wxWidgets
      id: cache-wx
      uses: actions/cache@v4
      with:
        path: ..\wxWidgets\
        key: ${{ runner.os }}-wx-${{ env.WX_VERSION }}

    - name: xLights
      working-directory: xLights
      run: msbuild /m:10 xLights.sln /p:Configuration="Release" -p:Platform="x64"
      
    - name: Upload xLights Exe
      uses: actions/upload-artifact@v4
      with:
        name: xLights_Exe
        path: 'xLights\x64\Release\**'
