name: Build wxWidgets

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    env:
      WX_VERSION: xlights_2026.04

    steps:

    # 1. Cache wxWidgets Build
    - name: Cache wxWidgets
      id: cache-wx
      uses: actions/cache@v4
      with:
        path: ..\wxWidgets\
        key: ${{ runner.os }}-wx-${{ env.WX_VERSION }}
        
    - name: Setup msbuild
      if: steps.cache-wx.outputs.cache-hit != 'true'
      uses: microsoft/setup-msbuild@v3

    # 2. Download wxWidgets (if cache miss)
    - name: Download and Build wxWidgets
      if: steps.cache-wx.outputs.cache-hit != 'true'
      run:
        git clone --depth=1 --shallow-submodules  --recurse-submodules -b master https://github.com/xLightsSequencer/wxWidgets ..\wxWidgets\
    
    - name: Build wxWidgets
      if: steps.cache-wx.outputs.cache-hit != 'true'
      working-directory: ..\wxWidgets\
      run: msbuild /m .\build\msw\wx_vc17.sln /p:Configuration="Release" /p:Platform="x64"
      
    # Optional: Upload DLLs as artifacts
    - name: Upload wxWidgets DLLs
      uses: actions/upload-artifact@v4
      with:
        name: wx-dlls
        path: ..\wxWidgets\build\lib\*.dll