name: Build wxWidgets

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    env:
      WX_VERSION: xlights_2026.04

    steps:
    - uses: actions/checkout@v4

    # 1. Cache wxWidgets Build
    - name: Cache wxWidgets
      id: cache-wx
      uses: actions/cache@v4
      with:
        path: ${{ env.WX_DIR }}
        key: ${{ runner.os }}-wx-${{ env.WX_VERSION }}

    # 2. Download & Build wxWidgets (if cache miss)
    - name: Download and Build wxWidgets
      if: steps.cache-wx.outputs.cache-hit != 'true'
      run: |
        git clone --depth=1 --shallow-submodules  --recurse-submodules -b {{ env.WX_VERSION }} https://github.com/xLightsSequencer/wxWidgets ..\wxWidgets\
        cd ..\wxWidgets\
        msbuild /m .\build\msw\wx_vc17.sln /p:Configuration="Release" /p:Platform="x64"
        
    # Optional: Upload DLLs as artifacts
    - name: Upload wxWidgets DLLs
      uses: actions/upload-artifact@v4
      with:
        name: wx-dlls
        path: ..\wxWidgets\build\lib\*.dll